### ISSUE TITLE
Make 'inherit' value work correctly for shorthand properties

### ISSUE THREAD

**Issue by liZe** [Kozea/WeasyPrint#1007]
From [Cascading and Inheritance](https://www.w3.org/TR/css-cascade-3/#shorthand):

> If a shorthand is specified as one of the CSS-wide keywords, it sets all of its sub-properties to that keyword […].

It should be probably handled by the `expander` decorator.

**Comment by liZe** [comment]
For example, `text-decoration: inherit` is currently rejected. Some other shorthand properties probably set `inherit` only for one of the expanded properties.

**Comment by Smylers** [comment]
> For example, `text-decoration: inherit` is currently rejected.

This is a regression bug, breaking previously correct behaviour.

We've just tried upgrading WeasyPrint from 44 to 51, and discovered we're now getting a warning that we didn't before:

    WARNING: Ignored `text-decoration: inherit` at 136:3, invalid value.

and that some links are now getting underlines that they didn't have before the upgrade. Changing `inherit` to `none` restores the previous behaviour of no underlines. Presumably `text-decoration-line: inherit` would work, too.

This regression is particularly unfortunate for the `text-decoration` property, which didn't even used to *be* a shorthand: in CSS2, [`text-decoration` took values directly](https://www.w3.org/TR/CSS2/text.html#lining-striking-props), and MDN says Edge still [doesn't support the individual `text-decoration-*` properties](https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line#Browser_compatibility). So there's likely to be a lot of CSS out there setting `text-decoration` directly, rather than the individual properties.

**Comment by liZe** [comment]
> This regression is particularly unfortunate for the `text-decoration` property, which didn't even used to _be_ a shorthand

Yes, that’s exactly why this is a regression: `text-decoration` used to be a simple property in WeasyPrint, but it’s been transformed into a shortand by 9a73fff.

> So there's likely to be a lot of CSS out there setting `text-decoration` directly, rather than the individual properties.

Yes, it’s infortunate. I’ll try to fix this as soon as I can. If anyone is interested, I can also help someone to fix it, the patch should be pretty small and it’s a good way to learn how WeasyPrint works.

**Comment by dannyduncan** [comment]
Hey @liZe I believe I've come across this issue as well. Any updates on a fix? See my error below when using the sample report.css file from the gh-page branch.

```
WARNING: Ignored `text-decoration: inherit` at 153:11, invalid value.
```
Has anyone already addressed? Happy to help if you can provide some guidance.

**Comment by ckepper** [comment]
Hey @liZe, I have just submitted [this pull request](https://github.com/Kozea/WeasyPrint/pull/1522). Please review

**Comment by liZe** [comment]
#1524 is the draft pull request to solve this issue.
