### ISSUE TITLE
Weasyprint now included with print-css.rocks

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1026]
Just to let you now:

print-css.rocks now includes Weasyprint (currently without having checked and value the test results). But feel free to test the Weasysprint results compared to other tools.

**Comment by liZe** [comment]
Hello @zopyx,

Thanks a lot, that’s very useful!

I’ve launched the tests with WeasyPrint and compared the results with Prince. I’ve found unknown bugs in WeasyPrint that I’ll report (and some missing features that are already reported).

Can I send you a pull request with WeasyPrint’s results? I’ll probably change a couple of tests too, as some of them only use proprietary properties that WeasyPrint doesn’t understand.

**Comment by zopyx** [comment]
Please send PR for HTML and CSS. I will recreate the PDFs with the latest weasyprint version

**Comment by zopyx** [comment]
I updated print-css.rocks for Weasyprint after validating my "BASIC" tests...there are a few issues here

https://www.print-css.rocks/lessons

**Comment by liZe** [comment]
Here are the problems I’ve found for tests in the `lessons` folder:

## Because of bugs in WeasyPrint

- [lesson-background-repeated](https://www.print-css.rocks/lesson/lesson-background-repeated): fixed in e442165
- [lesson-center-vertical](https://www.print-css.rocks/lesson/lesson-center-vertical): problem in line height of tables with fixed height
- [lesson-css-transformations](https://www.print-css.rocks/lesson/lesson-css-transformations): missing border around images
- [lesson-multi-column](https://www.print-css.rocks/lesson/lesson-multi-columns): uneven repartition of text between columns
- [lesson-page-areas](https://www.print-css.rocks/lesson/lesson-page-areas): horizontal margin boxes don’t expand, see #58

## Because of problems in lessons stylesheets

- [lesson-hyphenation-long-words](https://www.print-css.rocks/lesson/lesson-hyphenation-long-words): missing encoding + nonstandard property
- [lesson-ligatures](https://www.print-css.rocks/lesson/lesson-ligatures): nonstandard property
- [lesson-named-pages](https://www.print-css.rocks/lesson/lesson-named-pages): wrong CSS
- [lesson-page-areas](https://www.print-css.rocks/lesson/lesson-page-areas): nonstandard property for bleed

## Because of missing features

- [lesson-box-styling](https://www.print-css.rocks/lesson/lesson-box-styling): `box-shadow`, see #149
- [lesson-cmyk](https://www.print-css.rocks/lesson/lesson-cmyk): CMYK
- [lesson-footnotes](https://www.print-css.rocks/lesson/lesson-footnotes), [lesson-footnotes-multi-columns](https://www.print-css.rocks/lesson/lesson-footnotes-multi-columns): footnotes, see #298
- [lesson-mathml-native](https://www.print-css.rocks/lesson/lesson-mathml-native), [lesson-mathml-torture-test](https://www.print-css.rocks/lesson/lesson-mathml-torture-test): MathML, see #59
- [lesson-typography](https://www.print-css.rocks/lesson/lesson-typography): `:first-line`
- [lesson-chart-js](https://www.print-css.rocks/lesson/lesson-chart-js), [lesson-flotr2-js](https://www.print-css.rocks/lesson/lesson-flotr2-js): JavaScript
- [lesson-right-to-left](https://www.print-css.rocks/lesson/lesson-right-to-left): RTL, see #106

**Comment by liZe** [comment]
An issue has been open for each bug, it’s time to close this issue!
