### ISSUE TITLE
B/W vs. colored emojis with SVGinOT font

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1048]
I have this Emoji test with the TwitterEmoji font (SVGinOT type) which produces a black&white result on Linux 

https://www.print-css.rocks/lesson/lesson-fonts-emoji

but this on Mac

<img width="934" alt="Bildschirmfoto 2020-01-31 um 13 27 39" src="https://user-images.githubusercontent.com/594239/73539501-cbb3d980-442d-11ea-8063-9a0115d121a5.png">

Where is the difference coming from? Is this related to the underlaying libcairo versions?

**Comment by liZe** [comment]
> Is this related to the underlaying libcairo versions?

It probably is, as the same example works on my Linux laptop.

I think that color emojis need at least:
- [Cairo 1.15.8](https://www.cairographics.org/news/cairo-1.15.8/),
- [Pango 1.40.8](http://ftp.acc.umu.se/pub/GNOME/sources/pango/1.40/pango-1.40.8.news),
- [Fontconfig 2.12.5](https://www.freedesktop.org/software/fontconfig/release/ChangeLog-2.12.5).

**Comment by zopyx** [comment]
My versions on Linux are even newer:

- libcairo2/bionic-updates,now 1.15.10-2ubuntu0.1 amd64 
- libpango-1.0-0/bionic-updates,bionic-security,now 1.40.14-1ubuntu0.1 amd64
- libfontconfig1-dev/bionic,now 2.12.6-0ubuntu2 amd64
-

**Comment by liZe** [comment]
> My versions on Linux are even newer

Well… I think that I have a computer with Bionic at home, I’ll try during the week-end.

**Comment by Tontyna** [comment]
On my Bionic I get colored and sized emojis. I get colored emojis even without applying the stylesheet. Besides their size, they look all the same, no matter whether `TwitterEmoji` is applied or not.

I see same colored emojis even when opening index.html in gedit. That's probably the builtin `Nono Color Emoji` font.

Opening `TwitterEmoji.ttf` with the Fonts application -- all letters are black-and-white. Clicking on *Info* it tells me **Color Glyphs: no**.

Same library versions like @zopyx here.

**Comment by Tontyna** [comment]
@zopyx is package `fonts-noto-color-emoji` installed on your system where the emojis are B/W?

BTW: The colored glyphs in your screenshot from Mac look identical to the glyphs I see. And I have the impression that they don't look like the TwitterEmojis at all, but like the ones from Google Noto.

**Comment by Tontyna** [comment]
Quoting https://github.com/eosrei/twemoji-color-font:

> The font works in all operating systems, but will currently only show color emoji in Firefox, Thunderbird, Photoshop CC 2017, and Windows Edge V38.14393+. This is not a limitation of the font, but of the operating systems and applications. Regular B&W outline emoji are included for backwards/fallback compatibility.

**Comment by liZe** [comment]
> BTW: The colored glyphs in your screenshot from Mac look identical to the glyphs I see. And I have the impression that they don't look like the TwitterEmojis at all, but like the ones from Google Noto.

Of course, the emojis from the screenshot (and in my document) are Google Noto’s emojis, not Twitter ones. That’s because, on these computers (including mine), FontConfig’s configuration forces the use of a color emoji fallback font when available.

When dealing with fonts, it’s hard to know where to follow the system configuration and when to ignore it. Should WeasyPrint blindly follow the `@font-face` rule, or decide that a missing color emoji is a missing glyph and use a fallback font?

By the way, there are obvious cases where WeasyPrint is wrong (see #1028), but I think that we can safely ignore this problem here, as WeasyPrint just follows the fallback rules defined by the system.

@zopyx If you want to test color emojis, the easiest solution may be to use a font with bitmap fonts (like Noto) as it’s more widely supported. I can’t even find bug reports about Pango and Cairo supporting SVG in OpenType fonts.

**Comment by zopyx** [comment]
I think that an explicit `@font-face` declaration must always have a higher priority than the default configuration. As a user, I usually wonder why a rule based system is making decisions that I can not understand..at least some reasonable information about using a fallback font would be helpful. The very same problem but also affects many other tools.

**Comment by liZe** [comment]
> I think that an explicit `@font-face` declaration must always have a higher priority than the default configuration.

You’re probably right. From the specification:

> If the matched face is defined via `@font-face` rules, user agents must use the procedure below to select a single font:
> 1. If the font resource has not been loaded and the range of characters defined by the ‘unicode-range’ descriptor value includes the character in question, load the font.
> 2. After downloading, if the effective character map supports the character in question, select that font.
>
> […]
>
> A font is considered to support a given character if (1) the character is contained in the font's character map and (2) if required by the containing script, shaping information is available for that character.

So we should ignore Fontconfig rules in this case.

**Comment by liZe** [comment]
> So we should ignore Fontconfig rules in this case.

We’ll take care of this in #1028.

**Comment by Tontyna** [comment]
I don't get it, @liZe -- do you think B/W rendering TwitterEmojis would be the right way of doing it? And the browsers (mine and the one on @zopyx' Mac) are doing it wrong?

**Comment by liZe** [comment]
> I don't get it, @liZe -- do you think B/W rendering TwitterEmojis would be the right way of doing it? And the browsers (mine and the one on @zopyx' Mac) are doing it wrong?

Firefox is OK, because it knows how to render SVG in OTF fonts.

On my computer, Chrome renders black and white emojis from Twitter font, and that’s OK according to the specification.

Epiphany (WebKit) follows my Fontconfig configuration, including a rule replacing black and white emojis by color emojis when possible. That’s not OK according to the specification.

**Comment by zopyx** [comment]
> Epiphany (WebKit) follows my Fontconfig configuration, including a rule replacing black and white emojis by color emojis when possible. That’s not OK according to the specification.

Compliance with the standard or ignoring the standard is one thing...I agree here with @liZe .

The user expectation is a different concern. The rendering process of any PrintCSS is in most case a black box. If the processor decides to replace one font with another font then I want to be informed that this is happening and why.

**Comment by Tontyna** [comment]
> If the processor decides to replace one font with another font then I want to be informed that this is happening and why.

WeasyPrint has no info about the font substitutions performed. It's not WeasyPrint doing the replacements, it's Pango, obeying Fontconfig rules.

**Comment by liZe** [comment]
> WeasyPrint has no info about the font substitutions performed. It's not WeasyPrint doing the replacements, it's Pango, obeying Fontconfig rules.

It’s right, but even if Weasyprint has no info about the substitutions, it can probably avoid them by using a custom Fontconfig configuration instead of using the system’s one.

Unfortunately, always discarding the system configuration is not an option, you’re really happy to get fallback fonts when you have `font-family: Arial` on a Linux computer. But we can try to skip the system configuration only for `@font-face` rules.

**Comment by Tontyna** [comment]
Is this possible on **glyph** level as the spec demands?

**Comment by Tontyna** [comment]
Consider a text snippet like this one:

```html
<div class="emoji">
    🤗🙈🤐🐰😈🤩abc🙄🤑🤨🤭🦘
</div>
```

Emojis should be forced to not fall back to **Noto**, but nevertheless I'd like to see "abc".

**Comment by liZe** [comment]
> Is this possible on **glyph** level as the spec demands?

Yes, it is. Fontconfig configuration files have the "charset" test allowing to set properties only for given Unicode characters (should be used to solve #378 for example).

A naive solution would be:
- to keep the system configuration with system fonts (that’s what we do),
- ignore the system configuration with `@font-face` fonts (that’s not what we do), use a custom font configuration for the font (that’s what we do) and add a small configuration to get system fonts only as a fallback (that’s not what we do, see #1028, `@font-face` font names are just added to the system font names, and the system preferences are always applied).
