### ISSUE TITLE
Encountered HTTP 499 error when accessing image files stored on S3

### ISSUE THREAD

**Issue by kunxin-chor** [Kozea/WeasyPrint#1082]
Hi, we are using Amazon S3 to store our static files (on Django, using django-s3-storages, running Django 2.6). When we attempt to render a PDF, we got an error like below:

`
Failed to load image at "http://<s3 address>" (HTTP Error 499: UNKNOWN)
`

We are running the project from Amazon Cloud9 as our development platform.

**Comment by liZe** [comment]
Hello!

This error is a non-standard HTTP error returned by the server, so the problem is probably in the server configuration. You can try to reach this URL with another HTTP client (your browser or curl for example) and see if you get the same error.

**Comment by kunxin-chor** [comment]
Are there any settings that I need to set on a S3 instance for static files for the package to be able to access the files?

**Comment by kunxin-chor** [comment]
Hi! I have tried using the browser to access the image file, but it works ok via the browser, just not from within weaslyprint

**Comment by liZe** [comment]
> Hi! I have tried using the browser to access the image file, but it works ok via the browser, just not from within weaslyprint

Maybe your server is refusing WeasyPrint’s request for some reason. The easiest way to know is to look at nginx’ logs and check that you have exactly the same URL path for your request from the browser and from WeasyPrint. If that’s exactly the same request, then maybe nginx is refusing the connection because of the header. You can try to download the image with [WeasyPrint’s HTTP headers](https://github.com/Kozea/WeasyPrint/blob/ab47de3a273cf803a87b950fe26572c59e183874/weasyprint/urls.py#L37-L41) using curl or wget.

**Comment by liZe** [comment]
Did you try to get the resources with WeasyPrint’s headers?

**Comment by liZe** [comment]
Feel free to reopen if needed.
