### ISSUE TITLE
Why is weasyprint exec'ing gcc?

### ISSUE THREAD

**Issue by davidgfnet** [Kozea/WeasyPrint#1125]
If one does a simple html 2 pdf conversion running strace -f you can see:

[pid 18024] execve("/usr/bin/gcc", ["/usr/bin/gcc", "-Wl,-t", "-o", "/tmp/tmpay12194t", "-llibgdk_pixbuf-2.0-0"], 0x7fdab1b3b800 /* 48 vars */ <unfinished ...>
[pid 18030] execve("/usr/bin/gcc", ["/usr/bin/gcc", "-Wl,-t", "-o", "/tmp/tmpvvn39q4q", "-llibgobject-2.0-0"], 0x7fdab1b3b800 /* 48 vars */ <unfinished ...>
[pid 18036] execve("/usr/bin/gcc", ["/usr/bin/gcc", "-Wl,-t", "-o", "/tmp/tmpyzm7_z0d", "-llibglib-2.0-0"], 0x7fdab1b3bb20 /* 48 vars */ <unfinished ...>

I'm actually curious what that is. I imagine might be a weasyprint dependency not the program itself.

**Comment by liZe** [comment]
That’s a good question!

I suppose that gcc is used by `ffi.dlopen` to find where the shared libraries are. [An old Python issue](https://bugs.python.org/issue18502) somehow explains the relationship between `dlopen`, `find_library`, `gcc` and `ld`, it may have changed since but the overall idea is probably still accurate.
