### ISSUE TITLE
What PDF-Versions are supportet?

### ISSUE THREAD

**Issue by IngoSchopf** [Kozea/WeasyPrint#1131]
Hello,
this project is great, and we really love working with your Program. 
Amazing work and quality!

We are using Weasy Print successfully, but only PDF-Version 1.5 (Acrobat 6.x) is created.

What PDF-Versions are supported?

How can we change to a different PDF-Version?

Thank you a lot!

**Comment by runxel** [comment]
Not the dev, but wondering, what exactly you need. Is there something crucial in the newer PDF versions (1.6 and 1.7)?

**Comment by liZe** [comment]
> Not the dev, but wondering, what exactly you need. Is there something crucial in the newer PDF versions (1.6 and 1.7)?

That’s the good question. Cairo generates 1.5 because it uses features introduced in 1.5, but as PDF is retro-compatible, it’s also valid for 1.6 and 1.7.

If you really need to use a more recent version, you can safely change the first line of the PDF.

**Comment by IngoSchopf** [comment]
> 
> 
> Not the dev, but wondering, what exactly you need. Is there something crucial in the newer PDF versions (1.6 and 1.7)?

We want to create PDF in PDF/UA Format for Universal Accessibility, that is part of Version 1.7.
We will try to change the first line of the PDF. 
I will tell you the results. Thanks.

**Comment by IngoSchopf** [comment]
Changing the first line is no option for us. 
This must be built and can not be changed for every customer manual.
What is the Parameter to change the Version?

We can't find it in the API documentation:
https://weasyprint.readthedocs.io/en/stable/api.html

**Comment by liZe** [comment]
> Changing the first line is no option for us.
> This must be built and can not be changed for every customer manual.

I’m really sorry, but I don’t get it. If your goal is to generate PDF/UA documents, you definitely are able to edit the PDF, and thus are able to change its first line.

If you manually do this with some graphical software, then I understand that this option may not be available, or that it’s an extra step you would like to avoid.

> What is the Parameter to change the Version?
> 
> We can't find it in the API documentation:
> https://weasyprint.readthedocs.io/en/stable/api.html

There’s no option, because Cairo (the library we use to generate PDF documents) doesn’t provide one.

There are many, many reasons to edit the generated document. Changing the documents versions is one, but we won’t add an option each time someone wants to change something.

However, in the current master branch, [a `finisher` function can be provided](https://github.com/Kozea/WeasyPrint/pull/1096) that can change the generated PDF document. I think that it’s what you want.

**Comment by liZe** [comment]
@IngoSchopf Is there anything else we can do for you?
