### ISSUE TITLE
High values of colspan take too much time

### ISSUE THREAD

**Issue by chrisfrigo1** [Kozea/WeasyPrint#1155]
Hi, can't seem to work out why specifically this html string is causing weasyprint to hang during conversion. i'm using the latest version 51.  Any suggestions would be appreciated. 

[example-html.txt](https://github.com/Kozea/WeasyPrint/files/4888967/example-html.txt)

**Comment by Tontyna** [comment]
It's because of `colspan="65534" `

**Comment by liZe** [comment]
> It's because of `colspan="65534"`

Then I suppose it’s not struck, it’s just extremely slow :smile:. There’s an optimization waiting to be found.

**Comment by chrisfrigo1** [comment]
thanks guys. appreciated.

**Comment by liZe** [comment]
There are horrible nested loops here:
https://github.com/Kozea/WeasyPrint/blob/1b8ac910043dccf6f9d51981d555a000ff89f027/weasyprint/layout/preferred.py#L490-L495

Here’s a fix that makes `colspan=2000` take less than a second instead of 2 mins 30 on my computer. With the original 65534 value, it takes about 25 seconds. That’s not perfect, but I think it’s OK for such a dirty corner case :smile:.
