### ISSUE TITLE
Getting error when starting server after installing weasyprint gem

### ISSUE THREAD

**Issue by adityajain-cdn** [Kozea/WeasyPrint#1156]
Unable to load application: SyntaxError: /home/poweron/.rvm/gems/ruby-1.8.7-head/gems/weasyprint-0.1.0/lib/weasyprint/configuration.rb:10: odd number list for Hash

**Comment by liZe** [comment]
Hello!

The error you get is caused by [the Ruby gem called WeasyPrint](https://github.com/simplybusiness/weasyprint), not by WeasyPrint itself. I don’t think that this Ruby library is active anymore, so it’s probably broken now :unamused:.

If you want to use WeasyPrint, you can read [the documentation](https://weasyprint.readthedocs.io/en/latest/). Feel free to ask more questions if you can’t find a solution there.
