### ISSUE TITLE
Query: Full justify, hotlinked URL, word break and whitespace

### ISSUE THREAD

**Issue by drboone** [Kozea/WeasyPrint#1189]
Our "house style" (haha) uses two columns and full justification.  Occasionally the body of a document will contain a hotlinked URL.  Having two columns means that such a URL is commonly too long to fit on one line.

It appears that (1) the URL is split at one or more reasonable places (typically a slash) so that the parts will fit in the column, and then (2) the line is justified.  This can often result in a fair amount of whitespace between the previous text and the head of the URL.

I've tried the word-wrap and overflow-wrap properties, but they seem to be ignored (because a solution was found before getting that desperate?).

Is there a way to control the "badness" of whitespace in mid-line?

Thanks!

**Comment by liZe** [comment]
> Is there a way to control the "badness" of whitespace in mid-line?

Unfortunately, I don’t think so :unamused:. The best solution in this kind of situations is to use hyphenation, but it’s a bit strange for URLs… So, it’s not really a CSS problem, it’s actually a page layout problem with no real logical solution.

It’s a common problem for newspapers (often with a lot of small columns), and their solution is: fix problems by hand, force line-breaks earlier so that the long word is at the beginning of the line, manually adjust letter spacing on some words. And of course: only use justification when you **really have to** :wink:.
