### ISSUE TITLE
Inline-block ignores its padding/border/margin when calculating its max width

### ISSUE THREAD

**Issue by mtkennerly** [Kozea/WeasyPrint#1235]
This is a follow-up from #1234. Context:

* Using Pandoc to convert Markdown -> HTML -> PDF, with WeasyPrint as the `--pdf-engine`
* Markdown file: https://raw.githubusercontent.com/mtkennerly/playground/95ac6a3c30a5aa3300d337a2da807646462e20a1/docs/sample.md
* Pandoc invocations: https://github.com/mtkennerly/playground/blob/95ac6a3c30a5aa3300d337a2da807646462e20a1/.github/workflows/main.yaml#L18-L30

Using the latest WeasyPrint master code, the PDF does wrap long lines in code blocks, but each line is cut off prematurely, and there are some extra blank lines after the last wrapped line.

Documents produced by above Github workflow: [samples2.zip](https://github.com/Kozea/WeasyPrint/files/5374051/samples2.zip)

HTML:

> ![image](https://user-images.githubusercontent.com/4934192/95915559-4f6fe500-0d75-11eb-86c6-f1f7c5f4ff48.png)

PDF:

> ![image](https://user-images.githubusercontent.com/4934192/95915460-23ecfa80-0d75-11eb-9eef-ed5504271e41.png)

**Comment by mtkennerly** [comment]
As a workaround, I tried adding this to the Markdown:

```
<style type="text/css" scoped>
.sourceCode {
    white-space: pre-wrap !important;
}
</style>
```

In the HTML version, that gives me what I want:

> ![image](https://user-images.githubusercontent.com/4934192/95931491-47c13800-0d97-11eb-9a3b-db0f6b2f0718.png)

However, the PDF is unchanged. It seems like the `white-space` rule is ignored:

> ![image](https://user-images.githubusercontent.com/4934192/95931529-61fb1600-0d97-11eb-925d-f67c56ffe01d.png)

Documents: [samples3-inline-css.zip](https://github.com/Kozea/WeasyPrint/files/5374950/samples3-inline-css.zip)

**Comment by liZe** [comment]
Hello!

This problem is fun :smile:.

Lines are split, but it’s not a bug, it’s a feature. The stylesheet from your document has this rule, that only applies for print:
```css
  @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em }
  }
```

The `white-space: pre-wrap` rule makes lines break, and it’s actually quite clever for print, because you won’t be able to scroll.

The second rule, `text-indent: -5em; padding-left: 5em` is a little bit more cryptic, but it’s actually a nice workaround: it makes normal lines be displayed normally (-5em, +5em) and makes cut lines displayed with a 5em indentation (indent only applies to the first line of a block). The normal result is pretty nice (from a browser with print rules forced enabled):

![Capture d’écran de 2020-12-10 21-32-05](https://user-images.githubusercontent.com/952243/101826363-309c8d80-3b2f-11eb-822e-0ad6609e0d47.png)

We have a bug in WeasyPrint. The spans, displayed as inline blocks, have a content width of 100%, ignoring their left padding (that should set their size to 100% - 5em instead, to have a padding-box width of 100%). So, the text is 5em too wide, making it disappear on the right.

I’ll try to create a very small example showing the problem.

**Comment by liZe** [comment]
```html
<span style="background: red; display: inline-block; margin: 0 100px">a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h a b c d e f g h </span>
```

**Comment by liZe** [comment]
The result is really nice 😍! Very interesting way to display `pre` tags for print, thanks a lot for reporting this issue.

![Capture d’écran de 2020-12-14 07-16-15](https://user-images.githubusercontent.com/952243/102046773-500c1280-3ddc-11eb-8a6a-5a8d8f52b54e.png)
