### ISSUE TITLE
Remove columns support and update docs

### ISSUE THREAD

**Issue by LukasKlement** [Kozea/WeasyPrint#1245]
The WeasyPrint support for columns appears to be broken also with version 52. Since the CSS columns feature does not seem to be supported anymore by WeasyPrint, would it not make sense to remove it entirely? Endless loops are certainly worse than the CSS attribute being ignored?

We could also indicate in the docs to use WeasyPrint <= 47 if one wants to use the columns feature?

Referring to https://github.com/Kozea/WeasyPrint/issues/1020, the bug can be reproduced on the last 5 versions of WeasyPrint.

**Comment by liZe** [comment]
Hello!

> Since the CSS columns feature does not seem to be supported anymore by WeasyPrint, would it not make sense to remove it entirely?

The support for columns is far fro perfect, but it’s not totally broken. Actually, some companies use it daily and wouldn’t be happy to have it removed entirely :wink:.

> We could also indicate in the docs to use WeasyPrint <= 47 if one wants to use the columns feature?

Having a regression in one case (page breaks, according to #1020) doesn’t mean that support of columns is worse since 47. adb5216 (that introduced the bug) fixes 2 issues, with a test added to avoid future regressions.

The [documentation](https://weasyprint.readthedocs.io/en/stable/features.html?highlight=columns#css-multi-column-layout-module) already includes a paragraph telling that this feature only works for simple cases, and that pagination is not seriously tested:

> Simple multi-column layouts are supported in WeasyPrint. Features such as constrained height, spanning columns or column breaks are not supported. Pagination and overflow are not seriously tested.

In my opinion, the best solution is to fix #1020.
