### ISSUE TITLE
New pip resolver fails installation of WeasyPrint

### ISSUE THREAD

**Issue by kingsleyndiewo** [Kozea/WeasyPrint#1257]
Due to the new resolver on pip-20.3, pip install WeasyPrint fails on the dependency cairocffi:
ERROR: Requested cairocffi>=0.9.0 from file:///root/.cache/pip/wheels/37/f0/7e/f92a9b82bde542ad7e50f6f91b368f84fab2cf1176ba265aa5/cairocffi-file_.cairocffi_VERSION-py3-none-any.whl (from WeasyPrint==52.1) has different version in metadata: 'file-.cairocffi-VERSION'

**Comment by liZe** [comment]
Hello, thank you for this pull request!

It works for me, and I think that it’s not related to the new resolver. This error happens when you have an old version of setuptools, or when a wheel has already been generated in cache with an old version of setuptools.

Could you please try with a recent version of setuptools, and a clean cache (you can remove `~/.cache/pip/` for example)?

**Comment by kingsleyndiewo** [comment]
Clearing the cache resolved it. Thanks.
