### ISSUE TITLE
Better error message for the non-support of WOFF fonts

### ISSUE THREAD

**Issue by vpoulailleau** [Kozea/WeasyPrint#1259]
Thanks for WeasyPrint, I love it!

I lost 1 hour trying to use my `@font-face` and trying several options (local files, remote files, absolute and relative paths…). I finally discovered that WOFF and WOFF2 fonts are not supported (https://github.com/Kozea/WeasyPrint/commit/18010a152ee3f7327513d90be29096d29f5bc953) and this is totally OK, I know you're working on removal of cairo and better support.

In the meantime, I think that the following error message:

> WARNING: Font-face "Open Sans" cannot be loaded

may be replaced with

> WARNING: Font-face "Open Sans" cannot be loaded because WOFF and WOFF2 fonts are not currently supported

I saw an exception here: https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/fonts.py#L357

Maybe it's possible to catch it somewhere and provide a clearer message?

What do you think? (You may answer that I'll just have to wait for the support of WOFF and WOFF2 fonts :wink:)

**Comment by liZe** [comment]
Hello! Thank you for reporting this issue.

> You may answer that I'll just have to wait for the support of WOFF and WOFF2 fonts

Right, it’s even already supported in the `pydyf` branch :wink:.

> In the meantime, I think that the following error message:
> 
> > WARNING: Font-face "Open Sans" cannot be loaded
> 
> may be replaced with
> 
> > WARNING: Font-face "Open Sans" cannot be loaded because WOFF and WOFF2 fonts are not currently supported

It’s a bit more complicated than that: this warning is displayed when loading all the different fonts if one `@font-face` rule have failed. We may have different reasons why loading different fonts fail, we can’t have a specific message here.

But the message of the exception is displayed when you launch WeasyPrint with the `--debug` option. It’s not useful to display it as a warning, because font-face rules often contain fallback fonts, and one import failing doesn’t mean that the whole font-face rule is failing.

A clean way to do this would be to store the exceptions in a list and display them after the warning message (as warning messages) when they all fail.

Now that WOFF(2) fonts are supported, I’m not sure that it’s really useful to have this feature. Letting developers know that there’s a `--debug` option is probably a better idea :smile:.

**Comment by vpoulailleau** [comment]
OK, thanks for all this information. The `--debug` option is exactly what I needed (I read too fast the `--help` result…), I now get some messages that indicate the lack of support of WOFF fonts.

I'll try the `pydyf` branch.

@liZe Just to know, when is it planned to use this branch as the new `master` branch?

**Comment by grewn0uille** [comment]
Hi @vpoulailleau! Please have a look at https://github.com/Kozea/WeasyPrint/issues/1232#issuecomment-738087689 :)

**Comment by vpoulailleau** [comment]
Hi @grewn0uille! Thanks for the good news and for WeasyPrint/pydf!
