### ISSUE TITLE
Broken link on https://weasyprint.org/

### ISSUE THREAD

**Issue by Yanal-Yves** [Kozea/WeasyPrint#1270]
1) Link to changelog at https://weasyprint.org/news/ is broken there's no https://github.com/Kozea/WeasyPrint/blob/master/NEWS.rst.

2) At https://weasyprint.org/, the News section does not mention any new release after v51

**Comment by Smylers** [comment]
I came here to report this — either it's cropped up again or this issue was closed too hastily.

The header of all pages on [the WeasyPrint website](https://weasyprint.org/) says “WeasyPrint v52.4 (Latest version)”, which links to the non-existent [NEWS.rst](https://github.com/Kozea/WeasyPrint/blob/master/NEWS.rst) file.

Maybe it could link to either the [GitHub releases page](https://github.com/Kozea/WeasyPrint/releases) or the [docs' changelog](https://doc.courtbouillon.org/weasyprint/latest/changelog.html)?

**Comment by grewn0uille** [comment]
Thanks @Smylers!
I forgot this link last time ^^" It’s fixed now.
