### ISSUE TITLE
proxy support on comman line standalone program

### ISSUE THREAD

**Issue by KrullBorg** [Kozea/WeasyPrint#1276]
how can i use an http proxy with the standalone program on command line?

(i have a local html file with css/js from internet)

thanks in advance

**Comment by liZe** [comment]
Hello,

There’s no easy way to define a proxy on the command line. There’s probably a solution using a third-party tool…

**Comment by kajk** [comment]
Hello,

I thought that python usually respects the `http_proxy`/`https_proxy` environment variables for proxy settings.
And because WeasyPrint uses urllib this also seems to work here (at least for me on a Linux machine).

With a http proxy running on localhost:8080, I can start weasyprint like this, going through the proxy:
(Linux and MacOS):
```bash
export http_proxy="localhost:8080"
weasyprint http://weasyprint.org website.pdf
```
or in one-line: `http_proxy="localhost:8080" weasyprint http://weasyprint.org website.pdf`

For Windows it should be something like this:
```cmd
set http_proxy="localhost:8080"
weasyprint http://weasyprint.org website.pdf
```

Maybe this would be worth to add to the documentation?
But since it actually isn't a feature of weasyprint, maybe also not worth mentioning.

Cheers

**Comment by liZe** [comment]
> I thought that python usually respects the `http_proxy`/`https_proxy` environment variables for proxy settings.
> And because WeasyPrint uses urllib this also seems to work here (at least for me on a Linux machine).

Wow, thanks a lot!
