### ISSUE TITLE
Query: Is it possible to configure WeasyPrint linebreaks?

### ISSUE THREAD

**Issue by fabiobatalha** [Kozea/WeasyPrint#1281]
Sometimes WeasyPrint includes linebreaks in a undesired matter.

**In a sequence of characters without white spaces. (see: n°20/Millenium)**

problem : Breaking lines in / (slashs)

PDF left, HTML right.

![Screenshot from 2021-01-07 14-07-30](https://user-images.githubusercontent.com/504142/103934006-42ebf600-50f2-11eb-9c72-cdd63f865bdd.png)

**In a sequence of characters without white spaces, but containing html tags ex <i> (see: l'ethos)**

problem: Breaking line in html tag

PDF

![Screenshot from 2021-01-07 14-19-05](https://user-images.githubusercontent.com/504142/103934931-d2de6f80-50f3-11eb-8671-0fe32faac192.png)

HTML

![Screenshot from 2021-01-07 14-21-03](https://user-images.githubusercontent.com/504142/103934942-d83bba00-50f3-11eb-88e0-c6ad8e3a7507.png)

**Comment by liZe** [comment]
Hello!

> problem : Breaking lines in / (slashs)

Line breaking is defined by Unicode. Slashs [allow line breaks after](https://www.unicode.org/reports/tr14/tr14-45.html#SY), but a comment says that these lines breaks can be avoided by the layout engine in some cases. WeasyPrint doesn’t have any special case for that.

If you want to avoid line breaks between some characters, you can use the [word joiner character](https://www.unicode.org/reports/tr14/tr14-45.html#WJ), an invisible character that prevents line breaks.

> **In a sequence of characters without white spaces, but containing html tags ex (see: l'ethos)**

It’s fixed since version 52, see a0031a8.
