### ISSUE TITLE
Page creation takes too much time based on page size

### ISSUE THREAD

**Issue by ildarworld** [Kozea/WeasyPrint#1296]
Dear Weasyprint team, first of all I would like too say Thanks for your great work)

Now, my case, I'm generating through the Weasyprint almost similar documents but with different page sizes.
HTML almost the same - inside one tablewhich contains a lot of <td> elements.

- First story: I generating A4/Letter document, in each page 24 <td> elements. Generating a page takes less than a second in my case.
- Second story: Small page size 58x40. One <td> element in each page.
 
E.g. in first story we have 3 pages with 24 <td> elements in each page, the same data will be presented as 24x3 = 72 pages for second story for 58x40 page size.

My concerns is here: Second story takes twice much more time for page generation and it increases when number of pages increases.

Could you answer, how to optimise my code in order to avoid such overtime, and have a similar pdf creation time for all page sizes.

Thanks in advance )

**Comment by liZe** [comment]
Hello!

> Dear Weasyprint team, first of all I would like too say Thanks for your great work)

:heart:

> My concerns is here: Second story takes twice much more time for page generation and it increases when number of pages increases.
> 
> Could you answer, how to optimise my code in order to avoid such overtime, and have a similar pdf creation time for all page sizes.

For technical reasons (that are not really interesting), the time needed to render a table on multiple pages depends on the number of pages. The problem is not really technical, it’s logical, and there’s no easy solution to make a table render both "right" and "fast" (even if some code already tries to help).

The best solution, if it’s possible for you, is to avoid long tables. You’ll get a much faster rendering using common layouts instead of tables. Of course, if you rely on automatic column size based on the content, or on repeated headers and footers, then it’s hard to do… But if you don’t rely on that, you could try to remove this table.

If you’re stuck with this table, you can share your document here, we can try to find a solution to get a faster rendering.

**Comment by ildarworld** [comment]
T

> Hello!
> 
> > Dear Weasyprint team, first of all I would like too say Thanks for your great work)
> 
> ❤️
> 
> > My concerns is here: Second story takes twice much more time for page generation and it increases when number of pages increases.
> > Could you answer, how to optimise my code in order to avoid such overtime, and have a similar pdf creation time for all page sizes.
> 
> For technical reasons (that are not really interesting), the time needed to render a table on multiple pages depends on the number of pages. The problem is not really technical, it’s logical, and there’s no easy solution to make a table render both "right" and "fast" (even if some code already tries to help).
> 
> The best solution, if it’s possible for you, is to avoid long tables. You’ll get a much faster rendering using common layouts instead of tables. Of course, if you rely on automatic column size based on the content, or on repeated headers and footers, then it’s hard to do… But if you don’t rely on that, you could try to remove this table.
> 
> If you’re stuck with this table, you can share your document here, we can try to find a solution to get a faster rendering.

Thanks a lot,  will try, and I would share results here

**Comment by ildarworld** [comment]
Hello there, really,  I just excluded table from html and it increased performance)
