### ISSUE TITLE
Transparent 1px margins to the right and bottom in png output

### ISSUE THREAD

**Issue by au1985** [Kozea/WeasyPrint#1316]
I am using Weasyprint to create printable labels. My label printer does not like transparency in png, so I need to render completely white page. Unfortunately, I found that Weasyprint always adds 1px transparent borders to the right and bottom sides of the image. I created a minimalistic example to show:

css:

```
@page {{
            size: {medium['width']}mm {medium['height']}mm;
            margin: 0px;
            padding: 0px;
            background-color:white;
            border: none;
        }}
```

html:
`<html><body><div></div></body></html>`

I work with Python WeasyPrint==52.1 under CentOS.

**Comment by liZe** [comment]
Hi! Thanks for this bug report.

You have transparent pixels because 1mm = (96/25.4)px. The image size is rounded (we only have full pixels), but the page size (with the white background) is not. It’s more a logical problem than a technical problem, there’s no clean solution here :/. Changing the size of the page to use the size of the image is not a good idea, because you could easily find situations where it could break the rendering.

If you want to be sure that no transparent pixel is in your output, you can set a page size in pixels, not in millimeters.

I’m closing this issue because it’s already "fixed" in the current `master` branch (we only generate PDF files with arbitrary sizes, and Ghostscript or Poppler have the responsibility to handle the transformation correctly).

**Comment by au1985** [comment]
Hi liZe, thank you very much for your response - understood the point about rounding. Did not yet have a chance to look at the fresh version from master. I worked around the problem by blending my generated image with white background image of equal size to remove alpha channel.
