### ISSUE TITLE
Avoid some drawing artifacts when drawing lines

### ISSUE THREAD

**Issue by metapone** [Kozea/WeasyPrint#1324]
There is a white line appears between borders of the same cell and borders between adjacent cells:

![image](https://user-images.githubusercontent.com/52821877/112708973-289f0880-8ee8-11eb-843f-d7be6be2a597.png)

The top and left border are of the same cell here, the right one is of another cell to the right, and the bottom one if of yet another cell below that right cell. As you can see, they don't blend together like when viewing in a browser (Chrome in my case). The effect can be quite distracting if the border is set next to a cell with `background-color` of the same color, as in the case below. They should be blended, but isn't:
![image](https://user-images.githubusercontent.com/52821877/112709225-fdb5b400-8ee9-11eb-948f-ab84a40d9b6e.png)

----------------------------------------------------------------------------------

Another, probably related, issue is having colored lines between borders and background:

![image](https://user-images.githubusercontent.com/52821877/112709078-da3e3980-8ee8-11eb-86ae-b968e0740ed3.png)

The cell in the example have a blue background, and white borders with `border-radius: 10px`. You can see the background color "bleeding" into the outline of the borders, showing quite visibly where the top and left border are. Setting the `border-color` to `transparent` instead of `white` helps avoiding this issue of course, but it is an issue nevertheless.

**Comment by liZe** [comment]
Hello!

These artifacts can appear when two colored surfaces theoretically touch, but the PDF renderer separate them because of rounding errors. You’ll see these artifacts appear and disappear when zooming or when moving the viewable area. They will be different depending on the PDF renderer.

Unfortunately, it’s really hard (and in some cases impossible) to avoid these artifacts. We already avoid (some of) them in simple cases (borders with one color and no border radius), but it’s really complicated for other cases.

Moreover, "fixing" these artifacts would be more hacks than fixes. In the case of your border radius above, the blue background is bleeding outside of the border, but that’s actually a blue surface with a white surface drawn above. The coordinates are the same for the blue and the white surfaces (the numbers come from the same function), but rounding errors in the PDF renderer make the blue surface visible. If we want to avoid this, we have to use a slightly smaller size for the blue surface, but that would break other cases when you want the blue surfaces to be exactly the right size.

So… There’s no real solution. We could avoid some artifacts with a lot of work and some hacks, but we’ll never get a perfect rendering. It’s even more complicated for WeasyPrint because we rely on an intermediate vector format between HTML/CSS and the screen.

**Comment by metapone** [comment]
@liZe Would you mind explaining how browsers avoid this problem when viewing normally and when using their "Print to PDF" feature?

**Comment by liZe** [comment]
> @liZe Would you mind explaining how browsers avoid this problem when viewing normally and when using their "Print to PDF" feature?

They don’t really avoid this problem, they have it too when generating PDF. They probably have rendering strategies that are different from WeasyPrint’s ones, and thus have different problems.

Here is a simple example of PDF created by Firefox. You can clearly see artifacts on the border (and even guess how borders are drawn with Firefox :D). Even with a lot of work, it looks almost impossible to get a "correct" rendering.

![Capture d’écran de 2021-04-22 10-14-08](https://user-images.githubusercontent.com/952243/115680479-e2f12680-a353-11eb-9486-d9bbc5e0ba7e.png)

The problem doesn’t appear on browsers when they render web pages on a screen, because the screen is a table of pixels and they have full control on what is rendered on each pixel. But, when generating a PDF, if you define two squares with no space between them, there’s no guarantee that the PDF renderer will not render a small space between them (because of rounding errors, because of antialiasing, and a lot of other good reasons I don’t know yet). As far as I know, we don’t really have control on that.

**Comment by liZe** [comment]
Closing, as we won’t try to be better than browsers about that :wink:.
