### ISSUE TITLE
“size:60mm 40mm portrait; ” This setting conflicts！

### ISSUE THREAD

**Issue by 54huige** [Kozea/WeasyPrint#1387]
`size:60mm 40mm portrait;`
I want to set the page size and keep the specified orientation

What should I do?

**Comment by AlexanderNeilson** [comment]
To help us understand the issue here (as it seems to me the response from weasyprint is correct) do you want the page to be 40mm wide and 60mm tall? if so then you probably want "size:40mm 60mm;" or if you want it landscape then just drop the portrait part of the css size.

The size parameter is side:<width> <height>; While it is true that you can mix orientation with dimensions this appears to be only allowed for situations where a "standardised" page size is selected (for example A4) as that page size provides two dimensions that can be either oriented portrait or landscape. When you specify the dimensions exactly you do not need to specify the orientation separately as you already have done that in the size you have defined

I think you want to use "size:40mm 60mm;" in your CSS but please advise if you have further information about the scenario that may need other advice to resolve.

https://www.w3.org/TR/css-page-3/#page-size
https://www.w3.org/TR/css-page-3/#typedef-page-size-page-size
https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size
