### ISSUE TITLE
print-css.rocks renderings with latest beta

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1400]
Hi there,

I am currently preparing a new print-css.rocks release. A few renderings appear weird with WP 53.0b2

https://beta.print-css.rocks/lesson/lesson-fonts-emoji

https://beta.print-css.rocks/lesson/lesson-images

https://beta.print-css.rocks/lesson/lesson-pdf-links

https://beta.print-css.rocks/lesson/lesson-cross-references

**Comment by liZe** [comment]
Thanks for the bug report.

e30907c fixes pdf-links and cross-references.

Colored emojis are not supported yet with pydyf. Emojis work with common monochrome fonts, but they’re broken as soon as a font with colored emojis is installed.

The problem with SVG is unknown and has to be fixed.

**Comment by liZe** [comment]
lesson-images is now fixed.

Well… Honestly, it’s not fully supported (see the green gradient), because of our poor support of SVG in 53. It will be better in future versions. At least, the image is displayed and doesn’t look bad.

We have open an issue for emojis (#1406) and everything else is fixed or tracked, let’s close this issue.

Thanks again for your report. We’ll definitely spend some time on the failing examples (we’d love to display the deer correctly :heart:).
