### ISSUE TITLE
Error loading static CSS and images

### ISSUE THREAD

**Issue by aabanaag** [Kozea/WeasyPrint#1407]
I have been reading up on few issues related to images and this has something to do with the url_fetcher but first I don't have access to a request object because I'm generating the pdf via celery task. 

This are the logs I get, but if I try clicking the link everything is loading fine. Also I integrated django-weasyprint which works perfectly but generating multiple pdfs is taxing so I moved it to a celery task. Also my entire structure is running in docker but then again I'm testing it on postman using the localhost:8000 endpoint which works perfectly. Any ideas?

![Screen Shot 2021-07-30 at 2 22 36 AM](https://user-images.githubusercontent.com/2245822/127545532-249c658b-f592-41b8-89ce-1886f9f3c95c.png)

**Comment by liZe** [comment]
Hello!

Your problem is probably caused by a network configuration problem in Docker, I don’t see how it could be related to WeasyPrint itself :/.

Maybe reading [this article](https://medium.com/it-dead-inside/docker-containers-and-localhost-cannot-assign-requested-address-6ac7bc0d042b) can help!

**Comment by aabanaag** [comment]
> this article

Thank you, Will check this out.

**Comment by liZe** [comment]
> Hmm, but if I try accessing that links via the browser I can view them properly so it is not an issue with the docker network?

Your browser is probably installed on your workstation, not in your Docker, that’s why it works. The problem (I think) is that the Docker service can’t reach the web server running on your workstation. That’s more or less the case explained in the article.

The problem you have is that your container’s `localhost` is not the workstation where the website runs. In order to reach the workstation, you need to define a host in your Docker container, as explained in [this SO question](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach).

As I said earlier, that’s a Docker configuration problem, not a problem in WeasyPrint. You’ll probably get more useful help on a Docker forum than here, because we don’t know Docker that much :wink:.

**Comment by liZe** [comment]
@aabanaag Is there anything more we can do for you?

**Comment by aabanaag** [comment]
SLR, I got it working locally from what you suggested there was just a fluke on what I did from the last comment. Apologies I'll close this one now.
