### ISSUE TITLE
 make_bookmark_tree removed from API but still referenced by docs

### ISSUE THREAD

**Issue by stanim** [Kozea/WeasyPrint#1420]
In this documentation there is a reference to make_bookmark_tree:
https://github.com/Kozea/WeasyPrint/blob/d5a7ec1f4a32081e901b144ab4b6f79fb8e54151/docs/first_steps.rst#individual-pages--meta-data

However this method is no longer available in document.py How should I port my code which uses make_bookmark_tree?

**Comment by liZe** [comment]
Hello, and thank you for the report.

You’re totally right, we’ve removed `resolve_links`, `make_bookmark_tree` and `add_hyperlinks` from the API without any comments in the changelog. We didn’t even change the part of the documentation you mentioned.

The removed methods are now directly included in `write_pdf` and include the data directly in the PDF instead of splitting the gathering/writing steps. It’s actually hard to put them back. Did you rely on this function?

**Comment by adnathanail** [comment]
@liZe Hi thanks so much for this package it's very useful!
We were using `make_bookmark_tree` to ensure a series of concatenated documents all started on an odd-numbered page so that a document was never split in double-sided printing.

If there was any way it could be put back that would be incredibly helpful!
Or do you happen to know of another way to go about this?

This was my code:

```python
bookmarks = html.make_bookmark_tree()
pages_passed = 0  # Used to find the indexes for extra pages to add.
num_route_pages = 0  # Number of pages for the current route.
for b in bookmarks:
    if b.label == "page start":
        pages_passed += 1
        num_route_pages += 1
    elif b.label == "route end":
        if num_route_pages % 2 == 1:  # If odd number of route pages, a new page must be appended to allow for double-sided printing.
            new_document = HTML(string="<style>@page {size: A4 landscape;}</style>").render()
            new_page = new_document.pages[0]
            html.pages.insert(pages_passed, new_page)
            pages_passed += 1  # Extra page count added to take into account newly inserted page.
        num_route_pages = 0

pdf = html.write_pdf()
```

Many thanks,
Alex

**Comment by liZe** [comment]
I’m not sure to understand your exact workflow, but could [`break-before: recto`](https://www.w3.org/TR/2018/CR-css-break-3-20181204/#propdef-break-before) be useful for you?

**Comment by grewn0uille** [comment]
Original issue has been fixed (documentation has been updated).
@adnathanail Feel free to say if the proposed solution isn’t working.
