### ISSUE TITLE
Raster image rendering performance dropped

### ISSUE THREAD

**Issue by SvenBecker** [Kozea/WeasyPrint#1444]
The rendering speed of raster images dropped since WeasyPrint version 53, see benchmarks in #1439.

**Comment by liZe** [comment]
The problem is particularly important with images other than JPEGs, as we have to convert them into JPEG2000 to embed them in the PDF.

Maybe there’s a better solution. I’ve read that some PNG files can also be embedded with no conversion.

**Comment by aschmitz** [comment]
I'll also mention that Firefox's PDF.js is also very slow at decoding JPEG2000 images, so this affects both rendering and viewing speed in some cases.

I believe you're right that certain kinds of PNG can be embedded without significant image conversion (assuming a compatible filter, color choices, etc.), but if we're trying to load raster graphics (other than JPEG or JPEG2000), it might be fastest to convert to that subset of PNG that can be directly embedded, rather than JPEG2000 (which is a fairly complicated and slow format to encode).

**Comment by liZe** [comment]
> I'll also mention that Firefox's PDF.js is also very slow at decoding JPEG2000 images, so this affects both rendering and viewing speed in some cases.

That’s sad :cry:.

> it might be fastest to convert to that subset of PNG that can be directly embedded, rather than JPEG2000

That would be the best solution. I’ve spent some time playing with the PIL to get the information needed to include the PNG files, but I’m not sure that it’s the right tool for this job. Could a PNG-in-PDF guru help me for this issue :smile:?

**Comment by liZe** [comment]
#1481 should help a lot. Tests with the current `master` are welcome!

**Comment by mpth** [comment]
Just ran a test with a real-world document. It had ~31 images pointing to PNG files and also 515 PNG images embedded via data-uri (`src="data:image/png..."`)

Size before #1481 
`37.5 MB`

Size after #1481
`4.7 MB`

Looks like an improvement to me 🎉 

Thanks @liZe @aschmitz ❤️
