### ISSUE TITLE
fonttools[woff] version is not pinned

### ISSUE THREAD

**Issue by ypicard** [Kozea/WeasyPrint#1449]
Hi,

I use poetry in my CI/CD pipeline with the following command: `poetry export --dev -f requirements.txt | poetry run pip install -r /dev/stdin`

This produces this error:
```
Collecting fonttools[woff]>=4.0.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    fonttools[woff]>=4.0.0 from https://files.pythonhosted.org/packages/f0/0d/dcbe10481ff3bd374b38dfa33b1f841ee7b8f9b7e5d27f564ccf6b682699/fonttools-4.27.1-py3-none-any.whl#sha256=51ad7ee7ff878bcf75578d07f221bb90e6eaed1def53774249815377e89490e7 (from weasyprint==53.2->-r /dev/stdin (line 557))
```

After googling a little bit, ended up here: https://github.com/python-poetry/poetry/issues/3472.

I can fix the problem by adding the `--without-hashes` param to my command, but is there a reason why the `font tools[woff]` dependency version isn't pinned when all others are? Would it be possible to pin it in the next release?

Thanks!

**Comment by liZe** [comment]
Hello!

> I can fix the problem by adding the `--without-hashes` param to my command, but is there a reason why the `font tools[woff]` dependency version isn't pinned when all others are?

Actually, we [don’t pin anything](https://github.com/Kozea/WeasyPrint/blob/313fb3a7f0b67dd61f5c21c2039146c5559e95a3/pyproject.toml#L14-L23), we only set the lowest versions required. So… I don’t know why poetry complains only about `fontools[woff]`.

Pinning the versions of all our libraries doesn’t look like a good idea for a library like WeasyPrint 😄.

> I use poetry in my CI/CD pipeline with the following command: `poetry export --dev -f requirements.txt | poetry run pip install -r /dev/stdin`

I don’t understand what you’re trying to do. Poetry is able to install WeasyPrint without generating a `requirements.txt` file before, isn’t it?

**Comment by ypicard** [comment]
> Actually, we don’t pin anything

Indeed, this is weird.

> Pinning the versions of all our libraries doesn’t look like a good idea

Why not?

> I don’t understand what you’re trying to do. 

We use Poetry as a development environment on our local machines. In CI and production, we are not using `poetry` and using plain old `pip` because of `poetry` performance issues. So a mix of both actually. I am not sure _why_ `poetry` complains about this, I just know it does 😅

**Comment by liZe** [comment]
> Why not?

Let’s imagine that there’s a bug in a library used by WeasyPrint. If the version is pinned, we have to release a new version of WeasyPrint when the bug is fixed in this library, and we definitely don’t want to do this :wink:. That’s even worse if this bug is caused by a security issue.

Moreover, requiring an exact version of a library would be a nightmare for Linux distribution packagers, that can only install one version of a library, even if it’s required by multiple packages.

Pinning versions in libraries is definitely not a good idea :smile:.

> We use Poetry as a development environment on our local machines. In CI and production, we are not using `poetry` and using plain old `pip` because of `poetry` performance issues. So a mix of both actually. I am not sure _why_ `poetry` complains about this, I just know it does

So, why don’t you use `poetry install` instead of `poetry export` + `pip install`?

**Comment by ypicard** [comment]
> Let’s imagine that there’s a bug in a library used by WeasyPrint. If the version is pinned, we have to release a new version of WeasyPrint when the bug is fixed in this library...
But then,  what happens if one of those libraries _introdue_ a bug in their releases? Backwards scenario no?

> requiring an exact version of a library would be a nightmare for Linux distribution packagers

Do all linux packages do the same? Meaning, they do not pin their dependency versions? I would need to understand why `poetry` is so opinionated on this being a security issue then.

> So, why don’t you use poetry install instead of poetry export + pip install?
Because I wanted to avoid having to install `poetry` in production environments. But overall, it looks like `poetry` has brought more struggles then benefits, I think the solution is going to be to revert to basic `pip` usage... Python really needs to up its game on those topics. I hope it can inspire itself from its neighbors out there.

**Comment by liZe** [comment]
> But then, what happens if one of those libraries _introdue_ a bug in their releases? Backwards scenario no?

The bug will be reported to the library, and will be fixed. Until then, users can manually install a previous version of the library. After the bug is fixed, users can upgrade the library. Users don’t have to wait for WeasyPrint devs to do anything.

> Do all linux packages do the same?

Of course. Imagine that they update a largely used library like libc, they don’t want to release a new version of the packages depending on libc, and then a new version of the packages depending on the packages depending on libc, etc.

> I would need to understand why `poetry` is so opinionated on this being a security issue then.

Poetry does a lot of things, but one of its ideas is to have deterministic builds. That’s really, really useful for end-user projects, when multiple people develop this project and have to use the exact same version of the libraries. If the project is a web service for example, you can deploy it in a really safe way, as you know which version of each library is used.

Of course, if there’s a bug or a security problem, the project manager has the responsibility to update the pinned versions manually.

So, pinning versions is very useful for projects, because it’s reproducible, and pinned versions can be changed when the product owner wants. For libraries, pinning versions would mean than end users depend on the library developers to choose the versions of the libraries they want.

> Because I wanted to avoid having to install `poetry` in production environments.

Oh, OK.

By the way, if Poetry is not able to generate a `requirements.txt` file, it’s maybe a bug in Poetry. Poetry devs will probably be able to say why it doesn’t work.

> But overall, it looks like `poetry` has brought more struggles then benefits, I think the solution is going to be to revert to basic `pip` usage...

`pip freeze` does the job, doesn’t it?

> Python really needs to up its game on those topics. I hope it can inspire itself from its neighbors out there.

I agree. Actually, I’m currently writing [a series of articles about Python packaging](https://www.courtbouillon.org/blog/00011-the-python-packaging-hell-the-can-of-worms) :wink:.
