### ISSUE TITLE
UTF-8 issues with Montserrat

### ISSUE THREAD

**Issue by knyttl** [Kozea/WeasyPrint#1456]
Consider this html:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Test File</title>
    <style>
        @page{size:100mm 100mm;}
        body,html{font-family:'Montserrat'; font-size:13px;font-weight:600;line-height:19px;text-transform:uppercase;}
    </style>
</head>

<body>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:600,700" rel="stylesheet">
    <div class="text">
        EĚSŠCČRŘZŽYÝAÁIÍEÉ<BR>
        eěsšcčrřzžyýaáiíeé
    </div>
</body>
</html>
```

Which works correctly in browser:

<img width="665" alt="Screenshot 2021-09-30 at 11 36 19" src="https://user-images.githubusercontent.com/401107/135427833-0ae25ff7-29de-4a19-bcc4-67ceb8ebb3bc.png">

Is rendered incorrectly with current Weasyprint version:

[ticket.pdf](https://github.com/Kozea/WeasyPrint/files/7258450/ticket.pdf)

<img width="270" alt="Screenshot 2021-09-30 at 11 37 15" src="https://user-images.githubusercontent.com/401107/135427967-f1c58e89-ce58-49e6-8489-7fc31619bccc.png">

**Comment by liZe** [comment]
Hello!

Thanks for this bug report.

The problem comes from the way Google Fonts works. Google Fonts doesn’t return the same CSS depending on the browser. For "advanced" browsers (namely Chrome, Firefox…), it gives a long CSS file with various subsets of glyphs to include characters that are not in their "default" subset.

But for other browsers (that are not supposed to be able to check if these fonts are all needed, and thus would download many useless fonts), it only includes basic latin by default. There’s a manual option needed to include other subset.

That’s why you have a different rendering in Chrome (with the needed subset) and in WeasyPrint (without the subset, the glyphs are rendered with another local font).

Don’t worry, we have a solution for you.

Google Fonts now provides a new API by default. If you use their website, you’ll now get a different URL. Instead of

`https://fonts.googleapis.com/css?family=Montserrat:600,700`

you’ll now have

`https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700`

🎉 And with this new API, there’s no manual subset needed. 🎉

**Comment by knyttl** [comment]
Thanks! This was really helpful and unexpected!
