### ISSUE TITLE
Full width row equalises other columns.

### ISSUE THREAD

**Issue by SophieWeb** [Kozea/WeasyPrint#1479]
I have the following layout in a table

```
<table>
    <tbody> <!-- this one is optional -->
        <tr>
            <td colspan="5">Title and summary</td>
        </tr>
    </tbody>
    <tbody>
        <tr>
            <td>Description</td>
            <td class="col_number">1234.56</td>
            <td class="col_number">234.56</td>
            <td class="col_number">3456.78</td>
            <td class="col_number">45678.90</td>
        </tr>
    </tbody>
    <!-- more optional and mandatory <tbody> -->
</table>
```
With a fixed size of 3cm for `.col_number`, table-layout is fixed.

When the first `<tbody>` is absent, the number columns are 3cm wide (the first column takes all the remaining space). When the optional `<tbody>` is present, all columns have the same width (a fifth of the table width).

Any idea if I’m doing something wrong ? The only fix I could come up with was cutting the table each time I have a full-width row.

**Comment by liZe** [comment]
Hello!

I’m not sure to understand your problem. Here’s what I get, with and without the first `tbody`:

![Capture d’écran de 2021-10-30 13-08-40](https://user-images.githubusercontent.com/952243/139530571-e26a10de-8585-435d-8ef7-e008d082e941.png)
![Capture d’écran de 2021-10-30 13-08-59](https://user-images.githubusercontent.com/952243/139530576-30cd34c2-2d4e-4ec7-8326-96f45ce0fd13.png)

Do you get something different?

**Comment by aschmitz** [comment]
Is it possible you've set [`table-layout: fixed`](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout) on the `<table>`? That would make the first row responsible for determining the widths of various cells, and all spanned columns would be treated as equal-width.

Instead if your first row has defined widths for columns (because you're not beginning with the colspan'd cell), those will be used throughout the rest of the table instead.

If your table is very long, using `table-layout: fixed` could get you a speedup because the renderer doesn't have to consider all columns, so it's reasonable to want `table-layout: fixed`. I haven't tested it, but you could probably use [`<col>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/col) elements to define widths for columns instead, and keep the `table-layout: fixed` for a moderately-easy optimization.

**Comment by SophieWeb** [comment]
Thanks for your insight @aschmitz, that’s exactly what’s happening! I’ll test with `<col>` elements to see if I can solve it that way.

**Comment by liZe** [comment]
@SophieWeb Please reopen if needed!
