### ISSUE TITLE
weasyprint.HTML won't load CSS nor images when called with string parameter

### ISSUE THREAD

**Issue by ringeringeraja** [Kozea/WeasyPrint#1494]
weasyprint.HTML(filename='blabla.html') renders it nice, though. There's an explanation for this behavior?

**Comment by liZe** [comment]
Hello!

When you give a filename, WeasyPrint uses it to resolve relative URLs. When you give a string, there’s no base URL.

You have to give the `base_url` parameter to the [`HTML`](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#weasyprint.HTML) class, so that relative URLs can be resolved.
