### ISSUE TITLE
Unexpected behaviour re SSL Context in default_url_handler

### ISSUE THREAD

**Issue by pandamodium** [Kozea/WeasyPrint#1504]
Hey All,

Just wanted to highlight a small issue we've been coming across when using weasyprint. (Great project by the way - very impressive! :))

When creating a CSS or HTML object, as standard it seems to discard the default SSL context? I'm not sure if this is intentional - but it seems to break the environmental variables such as REQUESTS_CA_BUNDLES and suchlike.

More specifically - in urls.py -> default_url_fetcher, we are taking the ssl_context=None, when it should really be ssl_context = ssl.SSLContext()

eg line 174 in urls.py - [here](https://github.com/Kozea/WeasyPrint/blob/509ab9379f5b3430ed8a7dfe3b76e4d43bb00b2a/weasyprint/urls.py#L174):

def default_url_fetcher(url, timeout=10, ssl_context=None):

Should read:

def default_url_fetcher(url, timeout=10, ssl_context=ssl.SSLContext()):

Or similar (eg check if ssl_context is not provided as an argument then set it to ssl.SSLContext() as a default.

Unless the behaviour is intentional?

I can put in a patch if that's allowed - apologies am new to github!

Regards,
Amien

**Comment by liZe** [comment]
Hello!

Using `None` by default makes `urlopen` work with the default behavior (`None` is the default value of `urlopen`). That’s a good default configuration in my opinion, because it lets `urlopen` take care of the SSL context.

The goal of the `ssl_context` parameter is to give users the possibility to handle SSL contexts manually if needed. If you want to use a specific context, you can create a specific `url_fetcher` and use it with WeasyPrint instead of the default one:

```python
def my_url_fetcher(url):
    return default_url_fetcher(url, ssl_context=ssl.SSLContext())
```

You can change this function to use the same SSL context everywhere, or to define the protocols used by the context, that’s up to you!

**Comment by liZe** [comment]
Feel free to reopen if needed!
