### ISSUE TITLE
issue with UL or OL in rtl direction

### ISSUE THREAD

**Issue by engragy** [Kozea/WeasyPrint#1512]
i can convert an HTML to pdf with this awesome solution (Weasyprint) as easy with direction "LTR", yet i notice there is limited support for "RTL".
the style orientation of ul/ol list items is left even though the ul and its li has the dir="rtl".
so is there a way around this limitation or can you tell me which file/part of the python code that may need a fix, may be i can help.

**Comment by liZe** [comment]
Hello!

The position of the marker is set here:
https://github.com/Kozea/WeasyPrint/blob/8ae09175eb39d17a613d241b5a727eb40a11f2f7/weasyprint/formatting_structure/build.py#L317-L328

The code is supposed to handle rtl direction: the marker is translated to the right, by 100% of its own width, and that’s OK. The problem is that its original position is on the left of the parent, and it should be on the right instead.

To understand what’s wrong, you can render this code using a browser and WeasyPrint:

```html
<html dir="rtl">
  <div style="position: absolute; padding: 1em; background: green">abc</div>
</html>
```

Right-to-left layouts should put absolute boxes on the right. In WeasyPrint, it’s put on the left. As markers are absolute boxes, we have exactly the same problem.

The missing code to handle this is here (there’s even a TODO!):

https://github.com/Kozea/WeasyPrint/blob/8ae09175eb39d17a613d241b5a727eb40a11f2f7/weasyprint/layout/absolute.py#L53-L124

The direction is in the box style, you can see an example in another function:

https://github.com/Kozea/WeasyPrint/blob/8ae09175eb39d17a613d241b5a727eb40a11f2f7/weasyprint/layout/absolute.py#L307-L315

To fix the bug, we have to set `translate_box_width` and `translate_x` according to the direction. It requires some logic, but it should be possible in less than 10 lines of code. We’ll need tests too, but I can definitely write them later.

It’s actually a good issue to discover WeasyPrint’s code, don’t hesitate to ask if you have any questions!

**Comment by liZe** [comment]
And for ordered lists, there’s another problem to fix:
https://github.com/Kozea/WeasyPrint/blob/8ae09175eb39d17a613d241b5a727eb40a11f2f7/weasyprint/formatting_structure/build.py#L307-L309

(There’s no need to panic, it can be fixed later! 😁)
