### ISSUE TITLE
Django. OSError: cannot load library 'gobject-2.0-0'

### ISSUE THREAD

**Issue by Gatisvagulis** [Kozea/WeasyPrint#1526]
Hi, I am using Python 3.9.5, Django==3.2.7, weasyprint==54.0b1 (tried lower version 53.0 but no luck), and gtk3-runtime-3.24.29-2021-04-29-ts-win64.exe. I  (windows) puted gtk in the path above all others (for both user and system).. I restarted computer. Uninstall weasyprint and install from beginning. tired to set paths like this:
Importing in views.py
`
from weasyprint import HTML
`
I am not using `add_dll_directory` because for this version it is not needed anymore. but Have tried it anyway without luck.
And last thing I did in virtual environment:` set WEASYPRINT_DLL_DIRECTORIES=C:\Program Files\GTK3-Runtime Win64\bin` like path is on my computer. 
Error still the same `OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`
I am using Windows 10 Pro, 64-bit operating system, x64-based processor

I dont know what else I can triy...

**Comment by sanketwagh147** [comment]
iam facing the same issue with fastapi

**Comment by KateAilet** [comment]
The same issue... and I'm really getting desperate(((((

**Comment by liZe** [comment]
Please carefully follow the [Install](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows) section of the documentation. If it doesn’t work, you can follow the [Troubleshooting](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#missing-library) section dedicated to this problem.

If the problem is not solved, please open a new issue so that we can solve your specific problems.
