### ISSUE TITLE
Build a standalone executable for Windows

### ISSUE THREAD

**Issue by teknowledgist** [Kozea/WeasyPrint#1550]
I know this is a very ignorant statement, but I (as a Python-ignorant, Windows sysadmin) think it would be helpful to be able to just download a "WeasyPrint.exe" executable (probably zipped with license.txt) and run with it.  

I have very simple needs for converting HTML to PDF and have been successfully using wkhtmltopdf.  It was extremely easy to get started because it was a single download and a page of commandline options.  

In an effort to be more up-to-date, I'm looking at WeasyPrint.  The warnings about how installing WP in Windows "may not be easy" and the multiple dependencies and using pip in a "virtual environment" make it very daunting.  Can I do it?  Most likely, but it sure seems like a lot of "mess" and extra baggage to keep around for my simple use-case.  

My understanding is that Python scripts/apps can be compiled into a stand-alone executable with all dependent libraries and the interpreter included.  If that is true, wouldn't it make sense to offer that as an option for folks who are looking for something simple with which to get started?  

Thanks!

**Comment by teknowledgist** [comment]
Sooo...  a stand-alone, binary WeasyPrint conversion tool is

* not possible?
* too problematic?
* not expected to have enough demand?
* worth considering?
* being investigated?
* a great idea, but low on the priorities list?
* being added to milestone X?
* something only an python-ignorant fool would ask for?  😉

**Comment by grewn0uille** [comment]
Hello!

> I know this is a very ignorant statement, but I (as a Python-ignorant, Windows sysadmin) think it would be helpful to be able to just download a "WeasyPrint.exe" executable (probably zipped with license.txt) and run with it.
> The warnings about how installing WP in Windows "may not be easy" and the multiple dependencies and using pip in a "virtual environment" make it very daunting.

Indeed having a "WeasyPrint.exe" would be the easiest solution for the users on Windows and would be less scary.

> My understanding is that Python scripts/apps can be compiled into a stand-alone executable with all dependent libraries and the interpreter included. If that is true, wouldn't it make sense to offer that as an option for folks who are looking for something simple with which to get started?

That’s the idea. Of course it would make sense to have that and we’ve got it in mind since quite a time, but it’s kind of complicated and requires a lot of work.

> * not possible?

Possible

> * too problematic?

Complicated to put in place, and may be problematic to maintain (with the different versions of Windows, etc.)

> * not expected to have enough demand?

It would definitely help a lot of users

> * worth considering?

We totally consider it

> * being investigated?

We’re investigating it when we have time … but there are many bugs we have to investigate!

> * a great idea, but low on the priorities list?

It’s a good idea, and would be worthy. There is a lot of demands for new features, bug fixes… which put it quite at the bottom of things to do.
Working to get a working Windows executable requires a lot of time, and maintaining it requires even more time. That would be possible if we had dedicated sponsoring for this task. Currently, we don’t even have a Windows licence to test it!

> * being added to milestone X?

Actually there is no milestone planned with it.

> * something only an python-ignorant fool would ask for?

I guess all Windows users would be happy to have an executable, python-ignorant or not, it would be more simple :smile:.

**Comment by teknowledgist** [comment]
Excellent answer(s)!

> Working to get a working Windows executable requires a lot of time, and maintaining it requires even more time. That would be possible if we had dedicated sponsoring for this task. Currently, we don’t even have a Windows licence to test it!

I understand!  I'm not trying to push for more than is possible; I just wanted to raise the question and get a response as to the interest and possibility.

As for a Windows license... 

1. Windows 10/11 will actually continue to work after the "trial" period without a license.  There are just some limitations to customization for the UI and it has an annoying reminder.
2. In a pinch, you can download a very current, [short-term, development VM from here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines), and then uninstall everything.  I have a script to do most of the "cleanup" in an automated way.  I'll try to get it into one of my repos and post the link here.

Thanks!

**Comment by liZe** [comment]
> I understand! I'm not trying to push for more than is possible; I just wanted to raise the question and get a response as to the interest and possibility.

No problem!

> As for a Windows license...

We know that we can use temporary licenses, but that’s not a solution to automatically generate and test a WeasyPrint executable 😀. We also already use GitHub Actions to test WeasyPrint on Windows.

The real problem is to get the time to build a reliable workflow to automatically generate a `.exe` file that would bundle everything and would work everywhere. Any other half-working proof of concept would only create other problems, and add issues to the long list of Windows-specific bugs reported here.

**Comment by grewn0uille** [comment]
Hello!

As it’s soon our 2-year anniversary as CourtBouillon, we opened a [short survey](https://thym.courtbouillon.org/1) to know more about your expectations.
Don’t hesitate to support this feature and give it a boost 🚀!

The survey will be opened until October 10th.

**Comment by liZe** [comment]
The executable is now [available](https://github.com/Kozea/WeasyPrint/releases).
