### ISSUE TITLE
default_url_fetcher is silent on TLS errors

### ISSUE THREAD

**Issue by arthru** [Kozea/WeasyPrint#1589]
I got a PDF export that suddenly came out whithout the CSS.

It turned out that the certificate from the server where the CSS was served changed a few hours earlier, and there was a mistake in the configuration, the certificate chain was not fully set in the file.

There has been some TLS errors during fetching this CSS file, but these errors were silently ignored and it turns out that the CSS file is just ignored.

I expect weasyprint to raise an exception on such TLS errors, or to print a warning.

**Comment by liZe** [comment]
That’s strange. Here’s what I get when I try to reach a stylesheet with a bad certificate (hostname mismatch in my case):

`ERROR: Failed to load stylesheet at https://bad.yabz.fr/style.css: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'bad.yabz.fr'. (_ssl.c:1145)>`

This message is displayed in the logs. If you use the CLI, it’s written by default on the standard input. If you use the library, you have to [configure the logger](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging) to define where you want to display/store the messages.

**Comment by liZe** [comment]
> Currently I'm experiencing sort of the same issue but due to another reason (network time-outs or DNS lookup failures).
> Even with a custom URL fetcher I'm unable to catch the exception when writing the PDF.

That’s not the same issue.

The original issue is about WeasyPrint being silent when a TLS error happens. I don’ think that it’s the case, but maybe @arthru has other arguments 😀.

Your issue is about the URL fetcher not raising an error and stopping the rendering. That’s not a bug, that’s a feature 😁: when an image or a stylesheet cannot be retrieved, it doesn’t crash the rendering, just as the browsers render a page when loading an image fails. You only have an error in the logs, just as the browsers display an error in the inspector.

There’s no simple way to stop the rendering when a secondary request doesn’t work. There’s a ticket about this that’s been open for years: #351.

**Comment by StrawberryJuice** [comment]
Thanks for the fast reply! Indeed something like a "strict" flag described in #351 would help for my case!

**Comment by liZe** [comment]
@arthru Ping?

**Comment by liZe** [comment]
Don’t hesitate to add another comment if you think that there’s something wrong in WeasyPrint.
