### ISSUE TITLE
Problems with Footnotes when using Columns

### ISSUE THREAD

**Issue by dlpgit22407** [Kozea/WeasyPrint#1598]
I was recently asked to look at weasyprint to replace out current tool to create pdfs. Most everything seems to work but I am seeing some problems with footnotes and cannot find documentation on exactly what you support.

The test-case.log file includes data, css style, and the instructions to recreate the problem that I am seeing. The footnotes seem to work fine until I start using columns.

The example_page image shows one of our documents and how we current handle footnotes for this service.

I am new to css but I tried a number of ways to get this to work and this was the simplest way to demo the problem.

Please let me know if this is a bug or if I am doing something wrong. Also let me know if your tool can match what we are currently doing or what is the best you can offer now or in the near future.

Thank You

[test-case.log](https://github.com/Kozea/WeasyPrint/files/8286374/test-case.log)
![example_page](https://user-images.githubusercontent.com/93775787/158818858-5425a063-a74e-4995-bc93-002370de33de.PNG)

**Comment by liZe** [comment]
Hello!

First of all, thanks for your report.

There are two different problems in your document:

1. Adding columns to the content displays the footnotes on the first page (even if there’s only one column). That’s a bug. But here’s the fun part: the PR #1597, proposed and merged earlier this morning, fixes this bug. (Yes, @aschmitz fixes the bugs before they’re reported). So… this will be fixed in version 55.

2. Displaying footnotes per column are not supported. We could also imagine that we could have 2 columns in the footnote area, but that’s not what you want (and it makes WeasyPrint crash, to be honest…). This problem is more complicated to solve, because that’s actually [an open question in the specification](https://www.w3.org/TR/css-gcpm-3/#footnote-area-position). And even if it was was specified, it would be hard/long to support in WeasyPrint.

**Comment by dlpgit22407** [comment]
1. When will version 55 be released?
2. So we can have 2 or more columns of data but the footnote area would be one column and all the fonts should be on the correct pages.

**Comment by liZe** [comment]
> 1. When will version 55 be released?

When it’s ready 😀. You can expect something like a couple of months. It won’t be included in the next minor version because it’s not a regression (and it may introduce some new bugs). But you can install the `master` branch if you want ([pip is able to do this](https://pip.pypa.io/en/stable/topics/vcs-support/#git).

> 2\. So we can have 2 or more columns of data but the footnote area would be one column

Yes.

> and all the fonts should be on the correct pages.

Yes (I assume that you meant "footnotes", not "fonts").

**Comment by dlpgit22407** [comment]
Thank you very much for your answers. And you assumed correctly.
