### ISSUE TITLE
Support CSS color module level 4

### ISSUE THREAD

**Issue by sander-deryckere** [Kozea/WeasyPrint#1630]
When using a color value without commas (like `style="color: hsl(180 100% 50%);"`), the resulting color is black. While color values with a comma (like `style="color: hsl(180, 100%, 50%);"`) work as expected.

Both should give the same results: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl

**Comment by liZe** [comment]
Hi!

That’s a feature introduced in [CSS color module 4](https://drafts.csswg.org/css-color/#changes-from-3).

**Comment by Thomasb81** [comment]
Hello

Apparently to fix this issue following function need to be fix:
https://github.com/Kozea/tinycss2/blob/291c1429e7de23d839c8bc187908b967013db477/tinycss2/color3.py#L126
in order to support `180, 100%, 50%` or `180 100% 50%`

But I understand also that `hsl(180 100% 50%)` is new syntax introduce by [https://www.w3.org/TR/css-color-4/](css-color-4) which is not yet approved W3C standard.
So if this fix is implemented is there other feature of this draft that need to be anticipate ?

**Comment by liZe** [comment]
> So if this fix is implemented is there other feature of this draft that need to be anticipate ?

Actually, we should keep the `color3` module and write another `color4` module in tinycss2, in order to let users choose the version they want to support. We’ll then be able to use `color4` instead of `color3` in WeasyPrint.

It’s safe to implement almost everything from this specification. Even if it’s only a working draft, some of its features are already implemented in other browsers, it shouldn’t change much in the future. Libraries using tinycss2 will be free to use the version they want.

**Comment by Thomasb81** [comment]
color4 seems far more complex than color3. 

In particular there is support for [Device-independent colors ](https://www.w3.org/TR/css-color-4/#lab-colors) and [Predefined Color Space](https://www.w3.org/TR/css-color-4/#predefined)

Where the purpose if I understand it well is to better the rending device : monitor in case you read you document on a calibrated screen or on paper-ink-printer to preserve author intent.

Can such application be supported by PDF and WeasyPrint ? I may be wrong but I guess today only RGBA is supported and everything is converted to RGBA. With Color4 I understand that the specified color space should end-up in the pdf document.  
Implementing everything on this topic required sharp knowledge and very few user may use them ...

**Comment by liZe** [comment]
> color4 seems far more complex than color3.

Yes, it is.

> I may be wrong but I guess today only RGBA is supported and everything is converted to RGBA.

Unfortunately, you’re wrong. CMYK support, for example, would be very useful for WeasyPrint.

> In particular there is support for [Device-independent colors ](https://www.w3.org/TR/css-color-4/#lab-colors) and [Predefined Color Space](https://www.w3.org/TR/css-color-4/#predefined) […] Can such application be supported by PDF and WeasyPrint?

There are three different steps.

The first step is to handle the syntax in `tinycss2.color4`. This part is necessary before handling what we can/want to handle in WeasyPrint. For this step, there’s no need to assume whether device-independent colors or predefined color spaces can/will be supported by PDF and WeasyPrint.

The second part is to use `tinycss2.color4` instead of `tinycss2.color3` in WeasyPrint. It’s the first step giving the possibility to handle new syntaxes (ie. fixing this bug).

The third part is to include new features, in the future. We’ll answer these questions then.(Spoiler alert: they are useful, for example for PDF/A support that can require default ICC profiles to be embedded. That’s just an example, CMYK being another obvious one.)

> Implementing everything on this topic required sharp knowledge

Do you imply that implementing countless CSS specifications, HTML, PDF generation or SVG rendering doesn’t require sharp knowledge 😁? We can learn, as we always do.

More seriously, we don’t want to handle everything in WeasyPrint right now. We only need the two first steps, and they are the easiest ones.

> and very few user may use them

I wouldn’t assume that CMYK is only used by "very few users" in the print industry 😁. And among the 7 million downloads of tinycss2 last month, it’s probably possible to find a few users that would benefit from a clean support of the level 4 syntax.
