### ISSUE TITLE
Images whitin multicolumn paragraph

### ISSUE THREAD

**Issue by jjsarton** [Kozea/WeasyPrint#1632]
The code:
```
<!DOCTYPE html>
<html>
    <head>
        <style>
			body {
				font-family: Sans;
				margin:0;
			}
			.col2 p {
				column-count: 2;
				column-gap: 3em;
			}
			.col2 p:first-child {
				margin-top: 0;
			}
			.col2 p img {
				max-width: 100%;
			}
			@media print {
				p  { font-size: 10pt; }
				h1 { font-size: 16pt;}
				img { page-break-inside: avoid; }
				@page {
					size: A4 portrait;
					margin: 20mm;
				}
			}
		</style>
	</head>
	<body>
		<div class="col2">
			<h1>Example</h1>
			<p>
				<img src="DSC00476.JPG">
				<img src="DSC00487.JPG">
			</p>
		</div>
	</body>
</html>
```
With a browser all is okay. Within the PDF file the images are vertically aligned.
If I don't have the h1 element weasyprint output is okay.
The images used has a width of 800px and an height of 533px;

**Comment by liZe** [comment]
I’ve finally found what’s going on here, and there’s no bug. The images are in the same column because they’re inline, and so they follow the `orphans` and `widows` properties that avoid lines to be alone at the beginning or the end of a block.

To "fix" this, you can either:
- set `img {display: block}`, or
- set `.col2 {orphans: 1; widows: 1}`.
