### ISSUE TITLE
Keep spaces as-is in code blocs

### ISSUE THREAD

**Issue by N-X-N** [Kozea/WeasyPrint#1635]
When there are several consecutive blank characters in the document, the generator usually removes them, but places the next characters at the right place.
I assume this behavior reduces the PDF size.

But in HTML `pre` and `code` blocks, blank characters usually are intentional.
Keeping them in place helps copying the program text from the PDF into another editor.
Without them, you need to re-indent the whole copied text, which can be error-prone if the language relies on indentation.

The attached HTML was generated from Markdown via Pandoc, I attached the relevant styles too.

[removed_spaces.zip](https://github.com/Kozea/WeasyPrint/files/8599393/removed_spaces.zip)

**Comment by liZe** [comment]
Hi!

Thanks for this bug report.

> I assume this behavior reduces the PDF size.

We’re not that smart 😁. The generated PDF actually includes all the spaces you want, we don’t do anything about that. The culprit here is the PDF viewer, that tries to be smart and removes "useless" spaces in order to provide a "clean" copy-paste feature. I’ve seen this behavior on Poppler- (Evince…) and pdfjs- (Firefox, Chrome…) based viewers, and I’ve read that it’s also the case for Adobe Acrobat.

I can’t find anything about this in the PDF specification, there’s probably no way to force the PDF viewer to keep the spaces. If you find anything online about this "feature" and how to avoid it, don’t hesitate to add a comment. But I’m afraid that this bug report should actually be a feature request for PDF viewers 😢.

The `pdftotext` program, provided with Poppler (it should be already installed if you’re on Linux) has a `-layout` option. Here’s what we get with `pdftotext acode.pdf`:

```
Some code:
class A {
int a; // Comment with

several spaces

int b;
}

Some method:
int getMax() {
int max = (this.a > this.b) ? this.a : this.b;
}
```

With `pdftotext -layout acode.pdf`:
```
Some code:

 class A {
     int a; // Comment with       several spaces
     int b;
 }

Some method:

     int getMax() {
         int max = (this.a > this.b) ? this.a : this.b;
     }
```

So… The spaces are definitely in the PDF, but the viewer prevents you from selecting and copying them.

**Comment by N-X-N** [comment]
Hi liZe,

Thanks for the explanations.
Yes, I saw the same behavior in 3 different PDF readers (Evince, Adobe, Sumatra), so I assumed the spaces were somehow removed at document creation time.
I will research this further, why they do it and if one can prevent it.

Best regards

**Comment by liZe** [comment]
> We’re not that smart .

Actually, we now are: https://github.com/Kozea/WeasyPrint/commit/669ad1a976e862535d46068ebe14ad39a43122ef

(It’s not released yet, so it’s not related to this problem)

> Would it help to use some special character instead of a plain space, e.g. equivalent to `&nbsp;`?

It doesn’t, at least for Evince.

Understanding the text layout is so complex in a PDF that I think that that PDF viewers don’t rely at all on actual space characters, but use the distance between text items. I’m not sure that there’s a solution to get these spaces back.
