### ISSUE TITLE
Really slow rendering of a 3 column layout

### ISSUE THREAD

**Issue by justquick** [Kozea/WeasyPrint#1642]
I am a developer. I do a lot of Python. That being said I should never be writing CSS because this is what happens when I do.

Ive found some sort of black hole for weasyprint where the rendering of a particular HTML/CSS 3 column layout w/ page breaks takes forever to run. I am trying to do a 3 column layout over several pages. This particular combination of break CSS directives seems to slow weasyprint considerably. Just wanted to report that this particular config is super slow and see if theres a way to fix it. It might be related to the fix for #36 which I knew was beastly.

Python 3.9
Weasyprint 54.3

The following gist articulates the problem. It's not a very long document (4 pages) but ive had to go through some hoops to get the formatting right. Again I really suck at CSS but it's for my [justquick/pdf12step](https://github.com/justquick/pdf12step) project 

https://gist.github.com/justquick/c6908fc5a2592307ea69d820e33f530b

**Comment by liZe** [comment]
Hi!

I’ve got good news for you: the bug is already fixed by #1597 and the fix will be included in the future major version (55) that will be probably released before the end of the week. You can try the current master branch to be sure that 55 will works for you, or wait a few days crossing fingers 😁.

(The rendering takes 2.6s on my laptop: [weasyprint.broken.pdf](https://github.com/Kozea/WeasyPrint/files/8667252/weasyprint.broken.pdf).)

Have fun with WeasyPrint!

**Comment by justquick** [comment]
Yup way faster and way better results on master. I will continue writing abominable CSS. Thanks.
