### ISSUE TITLE
Soft hyphens are rendered in bookmarks

### ISSUE THREAD

**Issue by brakhane** [Kozea/WeasyPrint#1654]
WeasyPrint 55.0

The following short program
```py
from weasyprint import HTML

HTML(string="""
<html>
<body>
<h1>Test&shy;ing 123</h1>
</body>
</html>
""").write_pdf("bug.pdf")
```

results in [bug.pdf](https://github.com/Kozea/WeasyPrint/files/8816085/bug.pdf).

**Actual behaviour:**

The PDF headline shows "Testing 123", but the bookmark shows "Test-ing 123"

**Expected behaviour:**

The text "Testing 123" should appear both in the PDF headline as well as in the bookmark.

**Comment by brakhane** [comment]
I just noticed the hyphen is not shown when displayed by Firefox. But SumatraPDF 3.3.3 shows a hyphen.

I'm not sure if it's a bug in SumatraPDF or in Weasyprint that Firefox PDF Viewer just works around.

**Comment by brakhane** [comment]
OK, I think this is indeed a bug in SumatraPDF. I've created a bug report on their repo.

**Comment by GitHubRulesOK** [comment]
Must be a bug in Acrobat and other conforming Editors too ? I have Illustrated how bookmarks are used as browser fragments in above link.

**Comment by brakhane** [comment]
@liZe i'll reopen it, as Acrobat has the same behaviour as SumatraPDF, so soft hyphens are probably not supposed to be in bookmarks

**Comment by GitHubRulesOK** [comment]
I have not looked at the standard and many such conflicts exist where there is convention rather than rule.

The point I was illustrating is that SumatraPDF traditionally tried to match as much as reasonable of Acrobat 9 as a minimal yardstick. SumatraPDF did/does not use much of URL fragments (but similar -switches).

Named Destinations are a wooly mammoth difference across ALL pdf viewers, so I am not saying what's right or wrong, just it older convention for URL or -switch navigation of the PDF outline.

**Comment by liZe** [comment]
Hi!

> I have not looked at the standard and many such conflicts exist where there is convention rather than rule.

There in nothing special in the specification about bookmarks: "Title − text string − (Required) The text that shall be displayed on the screen for this item."

The PDF renderers are then on their own to display the outline, and decide how they handle things like double spaces, line breaks, etc. But about soft hyphens, there’s no discussion about how they should be rendered: when they’re at the end of the line they should be displayed, when they’re not at the end they’re not displayed. That’s for sure a "strange" character that requires specific rules for the library rendering text, but it’s far from being the only one in Unicode 🤣.

> @liZe i'll reopen it, as Acrobat has the same behaviour as SumatraPDF, so soft hyphens are probably not supposed to be in bookmarks

The choice in WeasyPrint has always been to follow the specification rather than the implementation details. Having a bug in Acrobat’s bookmarks is not enough to add a dedicated workaround. The bug should be reported to Adobe, not to us 😀.
