### ISSUE TITLE
WeasyPrint adds some padding when scaling images

### ISSUE THREAD

**Issue by meollab** [Kozea/WeasyPrint#1683]
Hi!

I've found this odd behaviour in WeasyPrint. 

When trying to convert this html to pdf (minimal example)

```
<html>

<head>
 
    <style>
        div {
            background: aliceblue;
            border: 1px black solid;
            width: 2em;
            height: 2em;
        }

        div img{
            max-width: 80%;
            max-height: 80%;

        }
    </style>

</head>

<body>
                            <div>
                                <img src="https://duckduckgo.com/i/e8be2f83.png">
                            </div>

                            <div>
                                <img src="https://duckduckgo.com/i/b2e38b1b.png">
                            </div>


                            <div>
                                <img src="https://duckduckgo.com/i/e8be2f83.png">
                            </div>
</body>

</html>
```

which Chrome or Firefox render like this 

![image](https://user-images.githubusercontent.com/91116554/178775533-b9d1a543-6ad8-4472-85d1-8aea079c84eb.png)

WeasyPrint creates a pdf which looks like this

![image](https://user-images.githubusercontent.com/91116554/178775880-59a49255-6238-4ce8-aefc-5699dcd3e61c.png)

As you can see there's some weird space in the between the first and the third logos and the top of their respective boxes. 

As far as I can see there's nothing wrong with the html, which should be rendered as Chrome and Firefox do it, that is, the logos should be at the top of the box. I've looked into this issue https://github.com/Kozea/WeasyPrint/issues/776 but doesn't look related to my problem.

I'm using the latest WeasyPrint version (0.56), installed using pip.

Thanks for advance and keep up the good work!

**Comment by liZe** [comment]
Hi!

This strange space is there because the image is inline. The bottom of the image lays on the baseline, and the baseline’s position is lower than the image’s height, just as a "a" wouldn’t touch the top border.

As far as I can tell, it’s not a bug in WeasyPrint. The baseline position is given by the [strut](https://www.w3.org/TR/CSS21/visudet.html#strut) and CSS doesn’t define the position of the strut. Of course, some user agents are smart and define a "smart" position only based on the image height (ie. Firefox and Chrome), but others are stupid and define a "stupid" position based on the image height *and* the font metrics (ie. WeasyPrint).

So, unless someone’s able to give me a link to the specification defining the position of the strut in this case, there’s nothing to fix. Let’s keep WeasyPrint stupid 😁.

Of course, there are easy solutions for you: you can set `line-height: 0` on you `div`s, or set `vertical-align: top` on your `img`s, or set `display: block` on your `img`s. Would it solve your problem?

**Comment by meollab** [comment]
Thanks for your prompt response liZe!

You're right, setting `display: block` fixes the "problem" (or rather "discrepancy"). I agree with you, it's better to keep things simple instead of trying to mimic those browsers' behaviour.

I'll close the issue, thanks again!
