### ISSUE TITLE
@font-face not working with base64 data url

### ISSUE THREAD

**Issue by alastair-todd** [Kozea/WeasyPrint#1692]
e.g.

```CSS
      /* latin */
      @font-face {
        font-family: 'Open Sans';
        font-style: italic;
        font-weight: 400;
        font-stretch: 100%;
        src: url(data:font/woff2;base64,d09GMgABAAAAAEWY....
```
        
  FWIW this is the tool I used to generate the CSS
  
  https://amio.github.io/embedded-google-fonts/

**Comment by liZe** [comment]
Hi!

It works for me, even with a woff2 font, even with a data URL.

The problem probably comes from the fact that some of the libraries you use (probably Freetype, maybe another one) are not up to date. Woff2 is for example supported by Freetype since 2.10.2.

Please note that using this tool may cause problems in the future. The URLs provided by Google Fonts serve different contents depending on the browser you use, so you should really use them instead of using this tool. For example, your tool doesn’t give the same data URL on Chrome (where a woff2 font is served) or on Epiphany (based on WebKit, where a ttf font is served).

**Comment by alastair-todd** [comment]
Yeah thanks. Due to an archaic version of weasyprint in some cobwebbed docker...
