### ISSUE TITLE
Emojis are not printed in the pdf

### ISSUE THREAD

**Issue by Rickrk4** [Kozea/WeasyPrint#1716]
Hello, I'm trying to convert an HTML file containing some emojis into a pdf, but the emojis are not written in pdf.
This is some python code to replicate the bug.
`HTML(string="<html><head /><body>🦄👍🐶</body></html>").write_pdf('report.pdf')`

Weasyprint version is 56.1, python is 3.8.

Thanks!

**Comment by liZe** [comment]
Hi!

It works for me. Do you have a font including emojis on your system, such as Noto-color-emoji?

[report.pdf](https://github.com/Kozea/WeasyPrint/files/9535643/report.pdf)

**Comment by Rickrk4** [comment]
Hi, thanks for your reply.
Probably not since the code runs on a server.
However, I tried to add the font with emoji inside the CSS, but still not working. Is there any way to add the font to the file without installing it in the system?
Now, this is the code I'm running.
`
css = CSS(string = '''
    @font-face {
      font-family: 'Noto Color Emoji';
      src: url(https://raw.githack.com/googlefonts/noto-emoji/main/fonts/NotoColorEmoji.ttf);
    }
    body {
        font-family: 'Noto Color Emoji'
    }
''')

HTML(string="<html><head /><body>🦄👍🐶</body></html>").write_pdf('report.pdf', stylesheets=[css])
`
Thank you for your kind.

**Comment by liZe** [comment]
Emojis are generally handled with dedicated rules in Fontconfig, that’s why it’s often complicated to add a font including emojis using `@font-face` rules.

The (very) hard way would be to edit the Fontconfig rules so that you can use these distant fonts, but you’ll probably spend hours before getting interesting results. So, if you can install an emoji font on the system (and they’re often already packaged on Linux systems), it would save you a lot of time.

If you can’t install a font on the system because you’re not administrator, it’s always possible to install fonts for a dedicated user in its own home folder (it’s `~/.local/share/fonts/` on Linux).

**Comment by Rickrk4** [comment]
Ok, I've managed to install the font on the system and now the emoji are printed.

Thanks a lot for your help.

**Comment by btsunjin** [comment]
This is a good case. But I found another problem, which reads as follows:
>css = CSS(string = '''
    @font-face {
      font-family: 'Noto Color Emoji';
      src: url(https://raw.githack.com/googlefonts/noto-emoji/main/fonts/NotoColorEmoji.ttf);
    }
    body {
        font-family: 'Noto Color Emoji'
    }
''')

HTML(string="<html><head /><body>✅❎</body></html>").write_pdf('report.pdf', stylesheets=[css])
Using this string will trigger OOM.

**Comment by btsunjin** [comment]
My server's memory is 4GB

**Comment by btsunjin** [comment]
Thank you very much for your reply.
My weasyprint version is 59.0 and I am running on a debian server.
The text I edited is in mac

**Comment by liZe** [comment]
Could you please check what you get in [logs](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging)?

**Comment by btsunjin** [comment]
The problem is solved, but through other means: For the Noto Color Emoji font, it is supported for ✅ after offline installation.
Another surprising thing is that when the emoji font is not installed, it will also be oom, but now it will not, and the emoji font is also not installed.
The reason I need to investigate again.

**Comment by btsunjin** [comment]
I know the cause of the problem, it's a font problem
1. I use the font from https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf to render emoji. Actually its size is 10.4MB
2. I use the font downloaded from https://fonts.gstatic.com/s/notocoloremoji/v25/Yq6P-KqIXTD0t4D9z1ESnKM3-HpFab5s79iz64w.ttf or https://fonts.google.com/noto/specimen/Noto+Color+Emoji , rendering could not be completed. Its size is 23.7MB.
Although the problem is solved, but I still don't know why?

**Comment by liZe** [comment]
I can’t reproduce, even with https://fonts.gstatic.com/s/notocoloremoji/v25/Yq6P-KqIXTD0t4D9z1ESnKM3-HpFab5s79iz64w.ttf.

Maybe you’ll get interesting information in logs.

**Comment by btsunjin** [comment]
I print running logs, like this:

**Comment by btsunjin** [comment]
I print running logs, like this
<img width="550" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/112474570/f9e60e14-ae7e-4a74-809d-884552a30e74">
With this font  https://fonts.gstatic.com/s/notocoloremoji/v25/Yq6P-KqIXTD0t4D9z1ESnKM3-HpFab5s79iz64w.ttf., it will stop here, but with this font https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf , it will continue to render, logs:
<img width="1486" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/112474570/918ab310-dec1-498a-833e-fe1d8af002d2">

**Comment by liZe** [comment]
Then the problem may come from fonttools. Do you use the latest version of this library?

**Comment by btsunjin** [comment]
thank you for your reply
I upgraded fonttools from 4.39.4 to 4.40.0, which may be the latest version, but the problem still exists. I will continue to compare the differences in lib versions and update you with new progress.
Thanks again
