### ISSUE TITLE
WeasyPrint on Windows 10

### ISSUE THREAD

**Issue by leducvin** [Kozea/WeasyPrint#1725]
Hi! Thanks for the great library.

Happy user under linux, but starting to wonder if I can use it on my Windows 10 machines.
Looking at the documentation, it explicitly says: 

> Only Windows 11 64-bit is supported.

So, I suppose there is a good reason for that. Can you elaborate and add a little explanation in the documentation? Or I can PR a change in the docs once I have your answer ;) I wasn't able to find the answer in the existing issues.

In the installation instructions I didn't see anything at first glance that would be impossible to do on Windows 10. It is worth it for me to try on Windows 10 or is it just not going to work?

**Comment by grewn0uille** [comment]
Hi!

You can try it on Windows 10, I think it should work the same way as Windows 11.

As written in the documentation, we only support Windows 11 because it’s the last version of Windows, and being sure everything works on several Windows isn’t very practical for us (we’re linux users, so we have to test on vm everytime).
