### ISSUE TITLE
Race condition when loading Cairo

### ISSUE THREAD

**Issue by stacey-gammon** [Kozea/WeasyPrint#1731]
I am not entirely sure this is an issue with this library, however I am posting in case anyone has ideas.

I suspect a race condition because all it takes is adding a log message and the error goes away.

The error is:

```
        try:
>           with subprocess.Popen(['/sbin/ldconfig', '-p'],
                                  stdin=subprocess.DEVNULL,
                                  stderr=subprocess.DEVNULL,
                                  stdout=subprocess.PIPE,
                                  env={'LC_ALL': 'C', 'LANG': 'C'}) as p:
E                                 AttributeError: __enter__
/home/root/.pyenv/versions/3.9.11/lib/python3.9/ctypes/util.py:289: AttributeError
```

Which is coming from this call from WeasyPrint:

```
>   cairo = dlopen(
        ffi, ('cairo-2', 'cairo', 'libcairo-2'),
        ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
```

The error is coming simply from importing the WeasyPrint module:

```
from weasyprint import CSS, HTML
```

If anyone has any idea how just importing from weasyprint could throw an `__enter__` error, please let me know!

**Comment by liZe** [comment]
Hello!

WeasyPrint doesn’t use Cairo since version 53. Do you have a similar problem with a more recent version of WeasyPrint?

> If anyone has any idea how just importing from weasyprint could throw an `__enter__` error, please let me know!

The problem happens when a library is opened using `dlopen`. `ctypes` tries to launch `/sbin/ldconfig` using `Popen`, that should return an object that can be used as a context manager (ie. with the `with` keyword). The `with` automatically calls the `__enter__` method of an object at the beginning of the block. But for some reason, your `Popen` object doesn’t have an `__enter__` method.

I don’t know how it’s possible to get this error, other than having some code in your project monkey-patching the `subprocess.Popen` class. Maybe you have some strange Python module installed, such as `subprocess32`.

> I am not entirely sure this is an issue with this library, however I am posting in case anyone has ideas.

That’s not related to WeasyPrint, but we can try to help!

**Comment by stacey-gammon** [comment]
That was exactly the case, we mocked out `Popen` and didn't have the `__enter__` or `__exit__` fns. THANK YOU SO MUCH! !You saved me so much investigation time! 🎉
