### ISSUE TITLE
On weasyprint >=56.0 doesn't work 'Courier New' font

### ISSUE THREAD

**Issue by kykint** [Kozea/WeasyPrint#1736]
I have just upgraded from 55 to 56.1 and found out a strange bug. If there is in source html some text with Courier New font (Normal), then it wouldn't be rendered. Courier New Italic and Bold are ok.
Tested on Ubuntu 20.04 with ttf-mscorefonts-installer and on Windows 11.
55.0 - without bug
56.0, 56.1, 57.0b1 - with bug

**Comment by liZe** [comment]
Thanks for this bug report.

The problem comes from the bitmap fonts included in Courier New Regular (and not in the other ones). The generated PDF is invalid, causing various problems (not displaying characters with pdf.js or Ghostscript, creating an endless loop with Poppler…).

When a font includes both the vector and bitmap variants, we should probably use the vector one.

**Comment by liZe** [comment]
We now use the vector glyphes when available. Thanks for the report!
