### ISSUE TITLE
SVG rendered with non-zero stroke-width when stroke-width="0"

### ISSUE THREAD

**Issue by castedo** [Kozea/WeasyPrint#1738]
WeasyPrint 56.1 renders this SVG incorrectly.

STEPS:
With [svg-stroke-color-zero-width.html.txt](https://github.com/Kozea/WeasyPrint/files/9765865/svg-stroke-color-zero-width.html.txt):
```
weasyprint svg-stroke-color-zero-width.html out.pdf
```
EXPECTED: The middle X should look like the first X, which has zero stroke width.
GOT: The middle X looks like the last X, which has non-zero stroke width.

This SVG is a simplified version of some SVG that tex2svg created from input TeX. This causes math in a pdf to look pretty bad when viewing an entire PDF page with math. The more zoomed out, the more this issue looks bad.

It seems like somehow setting `stroke="currentColor"` on the middle `<g>` element caused the `stroke-width="0"` to get over-ridden.

My environment is Fedora 36 with WeasyPrint installed via pip.

**Comment by liZe** [comment]
Hi!

I think that your expectation is wrong. Here is what my different browsers give me (I’ve just changed 1 into 100 to clearly see the difference):
![Capture d’écran du 2022-10-12 17-36-10](https://user-images.githubusercontent.com/952243/195386782-0e3688e5-7489-4392-b52c-559eec11debd.png)

Rendering
```svg
<defs>
  <path stroke-width="1" id="E1-MJMATHI-58" d="…"></path>
</defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0">
 <use xlink:href="#E1-MJMATHI-58" x="1000" y="0"></use>
</g>
```
is like rendering
```svg
<g stroke="currentColor" fill="currentColor" stroke-width="0">
  <g x="1000" y="0">
    <path stroke-width="1" id="E1-MJMATHI-58" d="…"></path>
  </g>
</g>
```

As `stroke-width` is set to 1 on `path`, setting it to 0 on the `use` tag (or its parent) is useless. The path will always be rendered with `stroke-width="1"`. There’s no visible stroke on the first X because the default value of `stroke` is none. As soon as you set a stroke color, the stroke is visible.

**Comment by liZe** [comment]
> The more zoomed out, the more this issue looks bad.

This problem is related to the way PDF readers handle [spatial anti-aliasing](https://en.wikipedia.org/wiki/Spatial_anti-aliasing). As the stroke width is really small, it would be less than one pixel when your document is zoomed out. PDF readers generally choose to always display 1px lines, even when they should be smaller than that, to avoid to display nothing instead. This is why your strokes are too wide when displayed on a zoomed-out document.

**Comment by castedo** [comment]
Ah, thank you for the explanation. I think I'm understanding this better now.

Why does Firefox and Chromium render all three X the same but the PDF shows the last two Xs differently than the first X?

**Comment by castedo** [comment]
As an interesting data point: I just converted the attached html file to pdf using Chromium --headless --print-to-pdf ... and it show the same PDF effect as Weasyprint even though Chromium shows no different between the Xs when viewing inside the browser.

**Comment by castedo** [comment]
OK, so I think I understand this now. Most PDF readers do NOT perform anti-aliasing, or at least not as aggressively as a browser, when rendering the border of an SVG path. So a browser will let the parts of the path disappear as one zooms out but a PDF reader will try to preserve all (or maybe just much more) of the path border with darker pixels. The filling doesn't seem to affected like this maybe because PDF readers to anti-aliasing more like a browser with the filling of path.

I imagine I have a few details wrong in my mind, but I think or more or less understand how PDF readers and browsers are handling SVG when zoomed out.

What I'm going to try and do now is to modify the output of `tex2svg` to not use path border at all. If you have any advice how how to get math displayed via WeasyPrint let me know! I am currently exploring the approach of https://github.com/Kozea/WeasyPrint/issues/59#issuecomment-761623047 but it's not yet working for me ... still trying.

**Comment by liZe** [comment]
> OK, so I think I understand this now. Most PDF readers do NOT perform anti-aliasing, or at least not as aggressively as a browser, when rendering the border of an SVG path. So a browser will let the parts of the path disappear as one zooms out but a PDF reader will try to preserve all (or maybe just much more) of the path border with darker pixels.

You get the idea!

> I imagine I have a few details wrong in my mind, but I think or more or less understand how PDF readers and browsers are handling SVG when zoomed out.

Learning how browsers work is an endless trip 😁️.

> If you have any advice on how to get math displayed via WeasyPrint let me know! I am currently exploring the approach of [#59 (comment)](https://github.com/Kozea/WeasyPrint/issues/59#issuecomment-761623047) but it's not yet working for me ... still trying.

KaTeX seems to work, there’s another example of code in #1215.
