### ISSUE TITLE
OSError: cannot load library

### ISSUE THREAD

**Issue by AtharvaThipse** [Kozea/WeasyPrint#1803]
OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

**Comment by liZe** [comment]
Hi,

This error shouldn’t happen if you follow the [install steps](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html). If you did follow these instructions, please share more information about your system.

**Comment by shacker** [comment]
My team is seeing the same error when installing on M1-based Mac, using this documented method:

```
python3 -m venv venv
venv\Scripts\activate.bat
python3 -m pip install weasyprint
python3 -m weasyprint --info
```

Except for the second line, which should be 
`source venv/bin/activate`
(there is no Scripts dir and no .bat files on Mac vents).

**Comment by liZe** [comment]
> My team is seeing the same error when installing on M1-based Mac, using this documented method:

The documented way to use WeasyPrint on Mac is `brew install weasyprint`. You don’t even need a virtual environment.

**Comment by shacker** [comment]
@liZe To be sure I understand, are you saying that even though a pip installable version of weasyprint is available, it's not expected to be complete, and that it still needs some non-python supporting libs? 

It's never just about one Mac - it's a whole build stack, which should work on Mac and Linux equally. This is one dependency among hundreds that we use, and all of them are installed automatically on every server and dev workstation. 

Or do you mean that it will `pip install` and work fine on linux servers, but if you want to run it on Mac, you have to run `brew install` first to get the non-python dependencies installed, and then add the python module via pip?

**Comment by liZe** [comment]
> To be sure I understand, are you saying that even though a pip installable version of weasyprint is available, it's not expected to be complete, and that it still needs some non-python supporting libs?

Yes. WeasyPrint uses Pango (and some of its dependencies/related libraries like Harfbuzz, GObject, Fontconfig…)

> It's never just about one Mac - it's a whole build stack, which should work on Mac and Linux equally. This is one dependency among hundreds that we use, and all of them are installed automatically on every server and dev workstation.

Then you’ll have to install these dependencies.

> Or do you mean that it will `pip install` and work fine on linux servers

You have to install these dependencies, on all OSes. On Linux, it’s easy because they can be installed using the distribution’s package manager, when they’re not already part of the original installation (and WeasyPrint itself is already packaged for many distributions). On Mac, Homebrew is the easy way to install these libraries, even if other (not officially supported) solutions exist, such as Macports and Conda. On Windows, the preferred way is to install the bundled GTK library that comes with all the required dependencies.

Building a WeasyPrint executable (including all the dependencies) for Mac could also be possible, but it’s currently not our priority because 1. [it’s not the priority of the users who answered the last survey](https://www.courtbouillon.org/blog/00033-two-years-of-courtbouillon), and 2. we don’t have Apple hardware to test.

**Comment by shacker** [comment]
Thanks much for the excellent response. I think we had come from the perspective of all of our project dependencies being simple `pip installs` and not having to alter the deployment stack. But I understand. Thank you.

**Comment by stephanreitz** [comment]
Hi, @liZe 

I'm with Win11 - 64bits and believe I followed the install steps correctly.

Even so, I'm stuck on the same error: 
"OSError: cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'".

Are there something else tha I can do?
Thanks.

**Comment by liZe** [comment]
Hi @stephanreitz,

Did you install GTK3 in the default `C:\Program Files\GTK3-Runtime Win64` folder? If you didn’t, you can [set the `WEASYPRINT_DLL_DIRECTORIES` environment variable](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#missing-library) to the folder where you installed it.

**Comment by lmcamoes** [comment]
I have the same problem but I am using windows 10, is that ok?

**Comment by liZe** [comment]
> I have the same problem but I am using windows 10, is that ok?

You can now try the Windows executable at the bottom of the [latest release](https://github.com/Kozea/WeasyPrint/releases) (it’s called weasyprint-windows.zip).

For other use cases, please **carefully follow** the [installation steps for Windows](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#windows) and read the [missing library chapter](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#missing-library).

If it doesn’t work, please open a new issue!
