### ISSUE TITLE
Apply margin-top to table if split across page

### ISSUE THREAD

**Issue by Paddy-Farmeye** [Kozea/WeasyPrint#1846]
Hi there,

Thanks for WeasyPrint, it's fab.

If a table is split across two pages, is there a known way to apply a margin-top to the split portion on the second page?

Thanks

**Comment by liZe** [comment]
Hi!

There’s a property called [`box-decoration-break`](https://www.w3.org/TR/css-break-3/#valdef-box-decoration-break-clone) that could help. In your case, it won’t repeat margins because [margins are truncated at page breaks](https://www.w3.org/TR/css-break-3/#break-margins), but a padding might do the trick.
