### ISSUE TITLE
break-inside: avoid not respected within table cells 

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#1868]
Weasyprint 58.1

We have a larger table running over multiple pages. The `<td>` element has `break-inside: avoid` configured which is not respected.
  
<img width="1132" alt="Bildschirmfoto 2023-04-25 um 12 06 14" src="https://user-images.githubusercontent.com/594239/234244909-4e9142e0-32a4-4e8a-a898-3b8862e913a2.png">

**Comment by liZe** [comment]
Hi!

We didn’t find anything really specific to page breaks in table cells, and currently `break-inside: avoid` in tds avoids to split the content of `td` between pages (even if the table borders can be split, as in your example).

We chose to do this because the rendering you’re expecting can already be achieved by setting `break-inside: avoid` on the `tr` tag instead.
