### ISSUE TITLE
The HTML `fieldset` element does not render correctly

### ISSUE THREAD

**Issue by michielderoos** [Kozea/WeasyPrint#1892]
With this HTML  
```
<!doctype html>
<html>
<body>
    <fieldset>
        <legend>Sample Text</legend>
        <p>Text Text Text</p>
    </fieldset>
</body>
</html>
```  
  
This is expected (from Chrome 113):   
<img width="575" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/2199643/e43a6b7e-f522-440c-afc5-74c73bf51b37">
However, this is the result (using Weasyprint 59):  

<img width="592" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/2199643/5d3e5cdb-6a60-453d-b858-9d43e7341fe0">

**Comment by liZe** [comment]
Hi!

As far as I can tell, there’s no hard rule about how fieldset legends have to be rendered in the specification. But we can try to provide a default rendering that’s close to other browsers.

The solution to do this is to find a default CSS that would work, and put it into [the user-agent stylesheet](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/css/html5_ua.css). Anyone intersted?

**Comment by oshmoun** [comment]
added this to the stylesheet:
```
fieldset legend {display: inline-block; position: relative; top: -1.1em; background: white}
```

getting this result:
![image](https://github.com/Kozea/WeasyPrint/assets/2135622/1108aabf-99d4-443f-af53-1db9114b42ac)

Upon checking how chromium does it, it seems that `display: block` is utilized, not `block-inline`, but weasyprint seems to always give `block` elements the full width, so could not use that here.
Also not sure about hardcoding the background color, since chromium also doesn't do that, but without it the result would like this in weasyprint:
![image](https://github.com/Kozea/WeasyPrint/assets/2135622/3e628fc9-edd8-4b93-9f55-9ca16b99dc16)

**Comment by liZe** [comment]
Well, it seems complex to get a standard stylesheet that will work for everybody. The current rendering is not perfect but it’s OK, and nothing is done wrong according to the specifications. Browsers seem to use specific rendering for these elements, just as they do for form fields for example. Let’s keep the current rendering and let users write their own CSS, it’s actually better than setting default rules that will have to be overridden by users.
