### ISSUE TITLE
Dynamic page height, fit to content

### ISSUE THREAD

**Issue by kujiu** [Kozea/WeasyPrint#193]
Add an option on page size (for example for height) to adapt the size of the page to fit to its content. The document will have a dynamic size and not fixed-size pages.

**Comment by dmalan** [comment]
@SimonSapin, for a grading tool, we're actually hoping to do something similar so that each page in a PDF is only as tall as it needs to be to contain the page's content. Inspired by your comments and @sebasmagri's comments at https://github.com/Kozea/WeasyPrint/issues/274, we've figured out how to get the actual height of the content in the `body` of a page, as via `document.pages[0]._page_box.children[0].children[0].height`. But to keep everything on one page, is there perhaps a more elegant solution than

1. initially specifying a very large height and then cutting it down as needed (for which we'd need to guess a max possible height), or
1. letting the content span multiple pages initially, sum the pages' heights, and create a brand-new document whose `@page` height equals that sum (which feels a bit inefficient)?

Many thanks!

**Comment by josesanch** [comment]
Hi, 

I've been working on this because I need to have dynamic height documents and I've found a workaround that works well for me.

Generating a 1cm height pages and then counting the result.

I hope this could help anybody.

Best Regards.

```

css_1cm = [CSS(string="@page {height: 1cm; page-break-inside: always;}}}")]
render = html.render(stylesheets=css + css_1cm)
css += [ CSS(string="@page {height: " + str(len(render.pages)) + "cm}}}")
html.write_pdf(stylesheets=css)



```

**Comment by AndydeCleyre** [comment]
I'll add here my use case for which I think I want the same feature: I'm generating images of syntax-colored code, for viewing on screens. 

- I don't want the lines to wrap, though it's not so bad that they do.
- The generated image has a transparent border I don't want, but I trim that post-creation with graphicsmagick.
- The generated image is extra long when the code is short, but I trim a second time with the same graphicsmagick invocation.
- When the code more than 50 lines, I get a [transparent gap](https://user-images.githubusercontent.com/1787385/123166935-f009bf00-d443-11eb-9dae-56e7896c7a1d.png) between what I guess are pages, but I'm confused by the notion of "pages" in an image file altogether.

My current usage looks like this:

```python
from plumbum import local
from weasyprint import HTML
try:
    convert = local['gm']['convert']
except CommandNotFound:
    convert = local['convert']


def mk_png(html: str, folder=None) -> str:
    """Return generated PNG file path"""
    folder = (local.path(folder) if folder else local.path('/tmp/ccb_png')) / uuid4()
    folder.mkdir()
    png = folder / 'code.png'
    (
        convert['-trim', '-trim', '-', png]
        <<HTML(
            string=html,
            media_type='screen'
        ).write_png(resolution=384)
    )()
    return png
```

**Comment by liZe** [comment]
Closing, as there’s nothing in the CSS specification for that. The workarounds here can be useful, but the best solution is probably to use a browser if you want to export the content as an image.

**Comment by iandoesallthethings** [comment]
Old thread, but since it's at the top of the google results, I figured I'd drop my workaround here. `Page` objects give you a list of anchors, so you can tag the end of your document with an id, render once at an absurd length, grab the height, and render again.

```python
html_string = """
<html>
<body>
    <h1>Hallo</h1>
    <p>content content content...</p>
    
    <div id="document-end" />
</body>
</html>
"""

base_css = open("style.css").read()

def page_rule(y_position: float):
    return f"""
        @page {{
            height: {y_position}px;
        }}
    """

async def render_with_dynamic_length(html_string: str, filename: str) -> bytes:
    html = HTML(string=html_string)

    test_css = CSS(string=base_css + page_rule(20_000)) # Or some absurd overkill length. Maybe try/catch this if the content could be longer
    test_document = html.render(stylesheets=[test_css])
    target_height = test_document.pages[0].anchors["document-end"][1] # it's a tuple from top-right to bottom left like (x1, y1, x2, y2)

    final_css = CSS(string=base_css + page_rule(target_height))

    html.write_pdf(target=filename, stylesheets=[final_css])
```

Probably not the most memory efficient since the document kinda gets created twice, but hey, we're writing python here lol.
