### ISSUE TITLE
named pages force page break

### ISSUE THREAD

**Issue by pmjdebruijn** [Kozea/WeasyPrint#1944]
When using named pages a page break seems to be forced, even when it's not appropriate.

For example when the first div in the code associated with a named page, you end up with an empty first page, and a second named page. Where you would expect to get a named first page.

See example attached in #1943 for a concrete demonstration.

**Comment by liZe** [comment]
That’s a bug … in your HTML file 😄: the [doctype](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype) should be `<!DOCTYPE html>`.

**Comment by pmjdebruijn** [comment]
Oh, I'm a bit rusty on HTML/CSS, however when I change that, I still get that first empty page...

**Comment by liZe** [comment]
There are 2 problems with your doctype: the missing exclamation point (that’s important for this use case) and `html5` instead of `html`. When I use your original file I get the empty page (because the HTML parser thinks that it’s a normal tag), but when I change this single line it works.

[background-image-bleed-bug.zip](https://github.com/Kozea/WeasyPrint/files/12446662/background-image-bleed-bug.zip)

**Comment by pmjdebruijn** [comment]
Doh! Apologies... Indeed NOTABUG...
