### ISSUE TITLE
Logo at top of every page

### ISSUE THREAD

**Issue by kgish** [Kozea/WeasyPrint#1948]
How does one include a logo image on the top-left of every page?

I've tried the following css, but it does not work:

```
@page {
    @top-left {
        content: url(logo.ext);
    }
}
```
nor
```
@page {
    @top-left {
        background: url(logo.ext);
        background-repeat: no-repeat;
        background-size: 300px 100px;
    }
}
```
where ext is jpg, png or svg.

The following works fine and prints the expected text:
```
@page {
    @top-left {
        content: "Logo goes here";
    }
}
```

**Comment by liZe** [comment]
It should work, images are probably not in the folder WeasyPrint expects them. What do you have in [logs](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#logging)?

**Comment by kgish** [comment]
I looked in the logs and I see the following error:

```
Failed to load image at 'file:///app/reports/templates/logo.svg': ValidationError: ['“/app/reports/templates/logo.svg” is not a valid UUID.']
```

which is strange because the image can be found there:

```
$ ls backend/reports/templates/logo.*
backend/reports/templates/logo.jpg  backend/reports/templates/logo.png  backend/reports/templates/logo.svg

```

**Comment by liZe** [comment]
> ValidationError: ['“/app/reports/templates/logo.svg” is not a valid UUID.']

This is not an error from WeasyPrint. Do you use WeasyPrint with another library?

**Comment by kgish** [comment]
It's a django backend, could that be the reason?

**Comment by liZe** [comment]
> It's a django backend, could that be the reason?

Yes, it looks like a Django error.

If you want to use Django with WeasyPrint, you really should use [django-weasyprint](https://github.com/fdemmer/django-weasyprint), it’ll handle the URLs correctly for you!

**Comment by kgish** [comment]
You claim that this is not a weasyprint error, however when I look in the `weasyprint.log` file I definitely see the following line there:
```
Failed to load image at 'file:///app/reports/templates/kpn-logo.svg': ValidationError: ['“/app/reports/templates/kpn-logo.svg” is not a valid UUID.']
```

**Comment by liZe** [comment]
> You claim that this is not a weasyprint error, however when I look in the `weasyprint.log` file I definitely see the following line there:

To be clear: `Failed to load image at 'file:///app/reports/templates/kpn-logo.svg'` is an error raised by WeasyPrint, caused by the original error `ValidationError: ['“/app/reports/templates/kpn-logo.svg” is not a valid UUID.']` caused by Django. It’s just like an HTTP 500 error displayed in a browser: the error is displayed in the browser, but it’s actually caused by the server.

Handling base URLs used by WeasyPrint in web applications is a complex problem, that’s why plugins like django-weasyprint and flask-weasyprint have been invented. They propose smart ways to handle relative URLs, bypass cookies and authentication, avoid useless HTTP requests for static files, etc.
