### ISSUE TITLE
simple HTML renders perplexing bad text involving font

### ISSUE THREAD

**Issue by castedo** [Kozea/WeasyPrint#1951]
**ALERT:** reproducing this bug might depend on the current fonts served by fonts.googleapis.com (see link in
[input.html.txt](https://github.com/Kozea/WeasyPrint/files/12478072/input.html.txt)).

**REPO STEPS:**
Place [input.html.txt](https://github.com/Kozea/WeasyPrint/files/12478072/input.html.txt) in a current directory, then
```
podman run -v .:/test docker.io/castedo/font-mono-bug weasyprint /test/input.html.txt /test/dockout.pdf
```
One can probably do the above using `docker` too, but `podman` is better.

**GOT**
[dockout.pdf](https://github.com/Kozea/WeasyPrint/files/12478094/dockout.pdf)
The second line is crap text that does not match the first line.

**EXPECTED**
The second line to be valid letters (visually) that are the same letters as the first line.

**NOTES**

[Here is the Dockerfile](https://github.com/Kozea/WeasyPrint/files/12478110/Dockerfile.txt) that built the `docker.io/castedo/font-mono-bug` and [here is the output from building the image](https://github.com/Kozea/WeasyPrint/files/12478120/buildah.out.txt).

Making _any one_ of the following changes removes the bug:
* removing link to fonts.googleapis.com
* uninstalling the Fedora package `mozilla-fira-mono-fonts`
* removing the CSS rule `font-stretch: condensed;` affecting the _first_ line
* remove the CSS rule `font-family: 'Fira Mono';`

**VERSIONS**
* weasyprint 59.0 (installed via pip)
* Fedora 38

**Comment by castedo** [comment]
I should mention some background ...

**IMPACT**
In my most immediate use cases with gitlab.com/perm.pub/epijats I think I have plenty of easy work arounds. Namely, I can use other fonts or always use epijats in 'offline' mode (which does not link to google fonts) whenever  epijats is installed with the corresponding distro font package. But this issue appeared very unexpectedly late this summer. I'm not sure whether it appeared because the online Google font binary data changed or the distro font package changed or something else. In the long-run this bug, in other variations, will probably be annoying.

**Comment by liZe** [comment]
Hi!

After some tests, I can reproduce the problem! I’ll try to find where it comes from.

**Comment by liZe** [comment]
I’ve found what’s going on.

When Pango tries to find the normal "Fira Mono", it takes the one from Google. But when Pango tries to find the condensed "Fira Mono", it can’t take Google’s font, as it’s defined in `@font-face` to be used for normal stretch. Pango then tries to find another matching font on the system, and uses the "Fira Mono" installed on the system.

The two fonts have the exact same metadata, but they don’t use the same IDs for glyphs.

Pango uses two different fonts. When WeasyPrint embeds fonts, it tries to deduplicate Pango fonts, so that it doesn’t include the same font twice for two different font sizes for example. To deduplicate, it relies on the font description, that are by design different for different fonts. That’s supposed to be a good idea: Pango even provides a built-in stable identifier for font descriptions, so that they can be used as keys.

Unfortunately, these two fonts have exactly the same description. WeasyPrint thus only includes the first one, but the glyphs IDs used for the second line correspond to the second font.

A fix would be to use the font file content instead of the font description as key. The problem is that hashing the file content is much slower than using Pango’s built-in function that has been designed for this exact use case.

This problem only happens when:
- two fonts with the exact same metadata but different glyph IDs are available, **and**
- these two fonts are configured by Fontconfig to match different CSS font rules (ie. one is in `@font-face` and the other is not), **and**,
- these different font rules are used for this font in the document.

This case … shouldn’t happen very often :smile:. And the workaround is quite simple: don’t use `@font-face` for fonts that are already installed on the system, or don’t install fonts that are in `@font-face` rules on the system, or use `local()` in `src`’s `@font-face` rules (so sad Google Fonts doesn’t include an option for this.)

If this workaround is OK for you, then I think that we can safely close this issue. 😄

**Comment by castedo** [comment]
Wow! Impressive detective work! Thanks!

Yes, those workarounds are OK. It does sounds like the fix is not worth it.

I will keep this interference between web fonts and system fonts and @font-face in mind.
