### ISSUE TITLE
Justify negatively affects li marker spacing

### ISSUE THREAD

**Issue by pmjdebruijn** [Kozea/WeasyPrint#1953]
Currently, with `text-align: justify;` enabled, the `li::marker` is included in the application of the justification algorithm, which leads to an uneven left margin:

**Example:** [li-justify-bug.zip](https://github.com/Kozea/WeasyPrint/files/12485511/li-justify-bug.zip)

It's most noticeable in the "Quisque" and "Aliquam dictum" lines.

**Comment by liZe** [comment]
Looks like Firefox and Chrome do the same, so it may not be a bug. I’ll try to find something in the specification about that, but I don’t see why the space after the marker shouldn’t be included in the justification algorithm when using `list-style: inside`.

**Comment by liZe** [comment]
`list-style: inside` means that:

> The [::marker](https://www.w3.org/TR/css-pseudo-4/#selectordef-marker) is an inline element at the start of the [list item’s](https://www.w3.org/TR/2020/WD-css-lists-3-20201117/#list-item) contents.

So the space is just a normal space and its width is changed by the justification, just as in Chrome and Firefox. [Automatic justification is not really well specified in CSS](https://www.w3.org/TR/2023/CRD-css-text-3-20230213/#valdef-text-justify-auto), so other browsers could behave differently (WebKitGTK, maybe Safari?) but there’s nothing to change in WeasyPrint in my opinion.

**Comment by pmjdebruijn** [comment]
Aside from it looking quite horrid...? This is very wrong from a typography perspective. Essentially it makes justification unusable for documents that use this list style.

Keep in mind, that using list-style: inside doesn't conceptually change the beginning of the sentence, and therefore justification shouldn't affect anything before the start of the sentence.

Also, this wouldn't be the first bug in Firefox or Chrome of course :)

**Comment by liZe** [comment]
> Aside from it looking quite horrid...?

I can understand your frustration, but the goal of WeasyPrint is to blindly follow the specifications, not to try to be smarter than them. Each time we tried to be smarter than the specification, it just brought A LOT OF PAIN. 😢

Implementing W3C specifications is hard. We just don’t have the time (and even the will?) to define our own separate specifications.

>This is very wrong from a typography perspective.

I can for example use "Chapter XX — " instead of bullets for my list. Which spaces would then be justified?

>Also, this wouldn't be the first bug in Firefox or Chrome of course :)

Of course, there are bugs in browsers. But this time, it’s not a bug. You may find this horrible, terrible, a typography crime, but you may not call it a bug in browsers that follow rules defined by specifications. If there’s a bug, it’s in the specification.

>Essentially it makes justification unusable for documents that use this list style.

If justification is unusable for documents using this style, then don’t use this style! You can use a `::before` inline block where you can add padding, margin, whatever you want. There are many solutions that both give the result you want and follow the specification.

If you don’t like the specification, then it’s possible to change the specification! You can open an issue on the [W3C’s GitHub](https://github.com/w3c/csswg-drafts/) and discuss this topic with people who want to define the rules 😄.
