### ISSUE TITLE
Python 3.10 AWS Lambda incompatibility - Amazon Linux 2

### ISSUE THREAD

**Issue by christian-repos** [Kozea/WeasyPrint#1964]
Hello everyone!

I tried to build and package the latest version of the WeasyPrint library (59.0) and its native dependencies into an AWS Lambda layer for the Python 3.10 runtime. I am using the image "public.ecr.aws/sam/build-python3.10", which offers Pango 1.42.3 via the yum package manager. As the library requires Pango ≥ 1.44.0, it doesn't work.

I tried to follow the instructions to build from source for Pango-1.50.14 and all the dependencies from https://www.linuxfromscratch.org/blfs/view/svn/x/pango.html, but I am not able to get Pango working.
 
Following #1003, I managed to get WeasyPrint 52.5 to work with python 3.10. However, I would really need the latest version.

Can somebody provide a solution for this, please?

**Comment by liZe** [comment]
Hi!

> Can somebody provide a solution for this, please?

It should be possible to compile Pango and its dependencies, but that’s probably not easy, and I don’t know AWS enough to help you for that 😢.

But… Amazon Linux 2023 has been released, and it includes [Pango 1.48](https://amazonlinux.pkgs.org/2023/amazonlinux-x86_64/pango-1.48.10-1.amzn2023.0.3.x86_64.rpm.html). Is it possible for you to use Amazon Linux 2023 instead of Amazon Linux 2?

**Comment by liZe** [comment]
Otherwise, Kotify updated their [layer](https://github.com/kotify/cloud-print-utils) to use Docker with more recent packages.
