### ISSUE TITLE
language-specific rendering for Kyrgyz and Wolof not working

### ISSUE THREAD

**Issue by bobh0303** [Kozea/WeasyPrint#1995]
# Summary

When converting HTML to PDF, lang attributes using subtags `ky` and `wo` do not trigger language-specific rendering within the PDF, although the source HTML renders correctly in modern browsers.

WeasyPrint version: 60.1

Font for demonstration: [Scheherazade New](https://software.sil.org/scheherazade/) contains language-specific OpenType rendering for Kurdish (`ku`), Kyrgyz (`ky`, Rohingya (`rhg`), Sindhi (`sd`), Urdu (`ur`) and Wolof (`wo`)

## Correct rendering (HTML in Chrome 118.0.5993.90)

All 4 languages included here are rendered as expected:
![Chrome html rendering (all correct)](https://github.com/Kozea/WeasyPrint/assets/6842108/17987337-aeb7-406f-a2cb-f79c745f763d)

## Incorrect rendering from that same HTML converted to PDF using WeasyPrint
Kyrgyz and Wolof are incorrect:
![WeasyPrint PDF output (Kyrgyz and Wolof incorrect)](https://github.com/Kozea/WeasyPrint/assets/6842108/12ea7e9a-47ea-4d40-b6ea-42f3b26918f7)

# Further information:
According to the [IANA Language Subtag Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry), the correct language tags for use in HTML and XML for Kirghiz and Wolof languages are the two-letter tags `ky` and `wo`, respectively, based on ISO 639-1.  These languages also have ISO 639-2 three-letter codes, but IANA has settled on the two-letter codes for these languages in HTML and XML. 

In the case of Kyrgyz, the three-letter ISO 639-2 code `kir` **_does_** trigger Kyrgyz rendering behavior, but the IANA code `ky` does not.

In the case of Wolof, neither the IANA code `wo` nor the ISO 639-2 code `wol` trigger Wolof language-specific behavior.

**Comment by grewn0uille** [comment]
Hello,

Can you please share the related HTML/CSS?

**Comment by bobh0303** [comment]
Sorry it took me a bit to extricate minimum code, but please see 
https://github.com/bobh0303/langtagbug

**Comment by liZe** [comment]
Thanks for sharing the document.

WeasyPrint uses the Pango library, based on Harfbuzz, to render text.

It looks like it’s a bug in Pango. Here are the commands I’ve tested on my computer (I’ve transformed the font into OTF to install it, I can share it if needed.)

Harfbuzz gives the correct rendering:
`hb-view ScheherazadeNew-Regular.otf "ئ ئئئ" --language ky`
`hb-view ScheherazadeNew-Regular.otf "د بد بِّ بُ بٗ" --language=wo`

But Pango fails:
`pango-view --font "Scheherazade New 200px" --text "ئ ئئئ" --language=ky`
`pango-view --font "Scheherazade New 200px" --text "د بد بِّ بُ بٗ" --language=wo`

Note that you have the same behaviour as WeasyPrint, with `kir` working:
`pango-view --font "Scheherazade New 200px" --text "ئ ئئئ" --language=kir`

So… There’s not much we can do for you here 😢.

You can check that you get the same problems with the commands listed above. Then, you can report a bug on [Pango’s issue tracker](https://gitlab.gnome.org/GNOME/pango/-/issues) (and add Pango’s issue link here, so that other users can follow if they have the same problem), and the bug will fixed in WeasyPrint as soon as it is in Pango!

**Comment by khaledhosny** [comment]
This looks like https://gitlab.gnome.org/GNOME/pango/-/issues/723

**Comment by liZe** [comment]
> This looks like https://gitlab.gnome.org/GNOME/pango/-/issues/723

Thanks a lot for sharing this!

@bobh0303 After reading the issue (and the Wikipedia pages of Wolof and Kyrgyz 😁), it seems to be the bug you’re having.

Reading the [original PR in Harfbuzz](https://github.com/harfbuzz/harfbuzz/pull/4001) was interesting, and the problem in Pango seems to be complex. Adding the Arabic script to [`pango-script-lang-table.h`](https://gitlab.gnome.org/GNOME/pango/-/blob/main/pango/pango-script-lang-table.h) should be a workaround, but that’s not a clean fix.

Let’s continue the discussion on Pango’s issue if you have an idea about how to solve this!
