### ISSUE TITLE
unexpected line breaks at dots

### ISSUE THREAD

**Issue by sta-ho** [Kozea/WeasyPrint#2015]
WeasyPrint breaks line (if needed) at a dot joining letters and numbers (like "abc.123"), just as if there was a space after the dot ("abc. 123"). No line break is inserted in "a.b.c" nor "1.2.3". This odd behaviour is problematic if you have e.g. chapter numbers like "I.1.2.3", which are rendered as:
_see the chapter I.
1.2.3_ 

I'm not sure if this is a bug or intended behaviour; maybe there is such a typographic rule somewhere? In any case, the rule is not  universal. 
Adding _white-space: nowrap_ as a work-around is not always practical.

**Comment by liZe** [comment]
Hi!

I can confirm that `aaa.bbb` doesn’t break, `111.222` doesn’t break, `111.aaa` doesn’t break, but `aaa.111` **does** break.

We’re use [Pango](https://pango.gnome.org/) to break lines, and I get the same "problem" with `pango-view` for example. So, the best way to find an answer to this question and possibly fix the bug (if it’s a bug) is on [Pango’s bug tracker](https://gitlab.gnome.org/GNOME/pango/-/issues), we’re we’ll find people who know how this pure magic works :smile:. You can open an issue over there and add the link here so that other people with the same problem can follow your tracks.

**Comment by liZe** [comment]
Closing, as there’s nothing we can do here to fix this. Don’t hesitate to add the link to Pango’s bug if you open it.
