### ISSUE TITLE
@page {margins} relation images with 'position: absolute'

### ISSUE THREAD

**Issue by SystemError7** [Kozea/WeasyPrint#2020]
Hi, ``````

I have images with absolute position in a div in order to have free move with them, also I have the following style in ```@ page```:
```
    <style>
      @page {
        margin-top: 2.5cm;
        margin-left: 0cm;
        margin-right: 0cm;
        margin-bottom: 1cm;
        size: A4 landscape;
      }
    </style>
```
I've expected that the images with ```position: absolute | fixed``` won't be affected by the ```@page``` margins.

I try with
```
    @top-left {
        content: element(header)
    }
```
and it fixed in a certain way, because using that method, it doesn't apply the margin, but the images appear in all the pages.

There's a way to have the images with 'position: absolute' without affection of the ```@page``` margin?

What I expect:

![image](https://github.com/Kozea/WeasyPrint/assets/146701483/8e67a581-a64e-4f2d-9ca2-9fa9ca8b2a99)

The result:

![image](https://github.com/Kozea/WeasyPrint/assets/146701483/3bb0e14f-d6c3-4d2c-84ce-93421737be4f)

**Comment by liZe** [comment]
Hi!

> I've expected that the images with `position: absolute | fixed` won't be affected by the `@page` margins.

According to the specification, absolute and fixed elements are positioned relatively to the page area, which doesn’t include page margins.

If you want to put absolutely positioned images in the margins, you can use negative values for top/bottom/left/right. You can also set them as background of page margin boxes, or as background of the page (#1993 may be interesting to read, the fix is not included yet in a released version.)
