### ISSUE TITLE
Amazon KDP file processing issue

### ISSUE THREAD

**Issue by claell** [Kozea/WeasyPrint#2033]
I created a PDF with WeasyPrint. In Amazon Kindle Direct Publishing (KDP), this file causes issues.

After a long time of processing, finally some error message is displayed (similarly as described here: https://forum.softmaker.com/viewtopic.php?f=389&t=20441).

It seems that Amazon has problems with layers (that is a bit speculative, though). Opening the PDF and printing as PDF (for example in Firefox) fixes the problem. Possibly, this is also helpful for others with this problem.

The question is how to deal with this problem. Overall, the PDF seems to be fine, at least other viewers can deal with it. For an automated process, might it be sensible to add some option to WeasyPrint (or maybe there already is?) to "flatten" the PDF that is created?

**Comment by liZe** [comment]
Hi!

Could you please share the PDF (by mail if it can’t be public), so that we can check it?

**Comment by claell** [comment]
Sure! I just sent it to your email that is mentioned in your profile.

Thanks for your quick reply.

Amazon also replied to me, mentioning that flattening might indeed be required here (although I am not certain how reliable their support is in this case).

**Comment by liZe** [comment]
All the PDF readers and checkers we’ve tried are happy with this PDF, so the bug is likely on Amazon’s side. With WeasyPrint, you can try to generate PDF 1.4 documents instead of 1.7, or try to generate uncompressed PDFs, to see if it helps.

If it doesn’t work, then the best solution is maybe to try PDF to PDF converters (Ghostscript and Poppler at least should do this).

With no more official explanation from Amazon about why these documents don’t work, it’s hard to fix the "problem" reliably. Amazon has more manpower to fix their own bugs than we have to find workarounds in the dark. 😄

**Comment by claell** [comment]
Thanks for your feedback! According to Amazon, this has to do with layers. I'll try the suggested workarounds and also comment on here in case I find a working method.

I kind of agree that Amazon should be able to fix this. According to support, I think it was framed more like a "feature".

**Comment by liZe** [comment]
Closing, as there’s probably nothing we can (or want to?) do for Amazon.

@claell Don’t hesitate to add a comment if you have more information about this!

**Comment by claell** [comment]
Finally found the root of this issue! I used a background pattern as background image. However, I didn't specify a background color, leaving the empty space between the pattern transparent.

After explicitly setting a background color, Amazon no longer gives the processing error. Probably, Amazon has problems with transparent backgrounds or the combination of pattern and transparent background.

Just putting this here for reference (for me and in case others run into this issue).
