### ISSUE TITLE
cannot load library 'gobject-2.0-0'  - windows 10

### ISSUE THREAD

**Issue by lmcamoes** [Kozea/WeasyPrint#2071]
first of all, Thank you for your hard work and support.

I would like to use WeasyPrint on my Flask project but I am having some issues that I can't solve.
I follow instructions from https://doc.courtbouillon.org/weasyprint/stable/first_steps.html but with no success.
My system:
windows 10 Pro x64
Visual studio code 1.86.1
Python 3.12.1

I Installed GTK3 on C:\Program Files\GTK3-Runtime Win64

when running my code I have the error:
Exception has occurred: OSError
cannot load library 'gobject-2.0-0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'

Please help.

(.venv) PS E:\Finances\Flask example> python -m weasyprint --info     
System: Windows
Machine: AMD64
Version: 10.0.19045
Release: 10

WeasyPrint version: 61.0
Python version: 3.9.7
Pydyf version: 0.8.0
Pango version: 15003

**Comment by liZe** [comment]
Hi!

If you’re sure that:
- your OS is 64 bit,
- your Python version is 64 bit,
- your GTK libraries are actually installed in "C:\Program Files\GTK3-Runtime Win64" with DLLs in the "bin" folder,
- `WEASYPRINT_DLL_DIRECTORIES` is not set,
- your version of WeasyPrint is up to date,

then there’s nothing I can do for you. You’ll have to ask Windows gurus how it’s possible not to find a library when [`os.add_dll_directory` has been called with the correct folder](https://github.com/Kozea/WeasyPrint/blob/812e1946ec308eedf6866877186adc392785caf7/weasyprint/text/ffi.py#L420-L426).

Other solutions for you are:
- debug the `_dlopen` function to find what’s actually wrong,
- use WSL,
- use Conda,
- use another OS,
- manually copy the DLL files to the folder where your Flask app is launched (that’s a bad idea),
- try the new [Windows executable](https://github.com/Kozea/WeasyPrint/releases) (it’s in `weasyprint-windows.zip`).

**Comment by lmcamoes** [comment]
Thank you!
Just uninstalled everything and re-installed and with the following:
(.venv) PS E:\Finances\Flask example> python -m weasyprint --info
System: Windows
Machine: AMD64
Version: 10.0.19045
Release: 10

WeasyPrint version: 61.0
Python version: 3.9.7
Pydyf version: 0.8.0
Pango version: 15003

Is not giving errors anymore!!!
thanks

**Comment by liZe** [comment]
> PS E:\Finances\Flask example> python -m weasyprint --info

I didn’t see this. If `--info` includes the Pango version, then it has definitely found the GObject DLL.

**Comment by ilovefreesw** [comment]
I fixed this error by installing GTK Windows Runtime: https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases

Just installed weasyprint using uv: uv add weasyprint

and then installed the runtime from above link, it automatically sets path and after that it worked.

**Comment by liZe** [comment]
Adding DLLs to `PATH` leads to [DLL hell](https://en.wikipedia.org/wiki/DLL_hell) problems, and may break other programs that rely on that (see #2480 among others). There’s a [dedicated part](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation) in the documentation about how to set a specific environment variable instead of setting `PATH`.

🙏 Please follow the [installation steps](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#installation) if you want to get WeasyPrint working. And please open a new issue if you followed the documentation and have a problem. 🙏

(@ilovefreesw thanks for sharing your solution, but even if it works for you, this is not the best way to install WeasyPrint. Adding DLLs to `PATH` can break other programs. GTK for Windows is not maintained anymore, it brings outdated libraries with unfixed bugs. We prefer to give a single clean and tested way to install WeasyPrint in our documentation, as it avoids a brunch of problems that may not be obvious at first.)
