### ISSUE TITLE
getting images to load

### ISSUE THREAD

**Issue by developer992** [Kozea/WeasyPrint#2122]
Hello

this works:

`<img src="https://creapro.com/wp-content/uploads/2023/08/creapro_logo_color.pdf-300x69.png.webp">`

but not this:

```
{% for image in widget.charts() %}
<img src="{{ image[3] }}" />
{% endfor %}
```

widget.charts() returns a list of tuples where 3rd item is full url, it looks like this:

`http://localhost:8000/static/charts/dd08ff11-a654-4891-94b3-7848a96c81ba/1000_418089.png`

if i open this url in browser, it shows the image

but not weasyprint

it also works if i use absolute local path to the file and not url like so:
`<img src="file:///app/{{ image[2] }}" />`

but this kind of defeats the purpose since i need to load them from CDN

Thanks!

what am i doing wrong?

Example of a tuple:
```
[
'56', 
'1000/418089',
'static/charts/dd08ff11-a654-4891-94b3-7848a96c81ba/1000_418089.png',
'http://localhost:8000/static/charts/dd08ff11-a654-4891-94b3-7848a96c81ba/1000_418089.png'
],
```

Python code:
```
        font_config = FontConfiguration()
        css = CSS('...default.css", font_config=font_config) # -> css path is sample
        _html = render_report_to_html(report_uid=report_uid)
        html = HTML(string=_html, base_url='http://localhost:8000') # -> tried many variations of this to no avail
        buffer = io.BytesIO(
            html.write_pdf(stylesheets=[css], font_config=font_config),
        )
        headers = {"Content-Disposition": 'inline; filename="out.pdf"'}
        return Response(buffer.getvalue(), headers=headers, media_type="application/pdf")
```

**Comment by developer992** [comment]
i don't understand, this should work

**Comment by liZe** [comment]
Hi!

This problem often happens if you use a simple, mono-threaded development server. Your web app is already responding to the HTTP request that generates the PDF, it can’t respond to the parallel HTTP request to get the image.

There are many ways to avoid this. If you use Flask or Django, you should try Flask-WeasyPrint or Django WeasyPrint. Otherwise, you can launch your server so that it can handle multiple requests in parallel. Another solution is to write your own `url_fetcher` function that can read static files from disk instead of a useless HTTP request.

**Comment by developer992** [comment]
Thank you very much, this was it.

yes for development purposes i could just fetch local file and i will, but in production images will be hosted elsewhere.

i am using fastapi but all the same

thanks again
