### ISSUE TITLE
SVG text with text-anchor="middle" is clipped from version 60.2

### ISSUE THREAD

**Issue by paramaciej** [Kozea/WeasyPrint#2136]
Hi!

I've found out that there is a regression of SVG text rendering in version 60.2. When I set `text-anchor="middle"`, the bottom part of the text gets clipped. In the release notes for 60.2 there is a text-anchor related commit mentioned (https://github.com/Kozea/WeasyPrint/commit/1460522596d6b14d8bd959f8d89651839da3168c) , so maybe it's linked.

In the current version (61.2) it's not working properly.

Below HTML fragment and screenshots from versions 60.1 and 60.2.

```html
<!DOCTYPE html>
<html lang="en">
<body>

<h1>text-anchor="start"</h1>
<svg width="18cm" height="10cm">
  <text x="50%" y="50%" text-anchor="start" font-size="48pt" fill="black">
    abcdefg
  </text>
</svg>
<hr>
<h1>text-anchor="middle"</h1>

<svg width="18cm" height="10cm">
  <text x="50%" y="50%" text-anchor="middle" font-size="48pt" fill="black">
    abcdefg
  </text>
</svg>

</body>
</html>
```

### Version 60.1
<img width="450" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/2010828/fe34650e-c0b4-48e9-9188-e80c8cb8ef39">

### Version 60.2
<img width="451" alt="image" src="https://github.com/Kozea/WeasyPrint/assets/2010828/b4ed77f2-7a98-4668-91e1-50f1bb929d19">

**Comment by liZe** [comment]
Thanks for the bug report.

The problem comes from the fact that the text-anchor code now has to clip the text, because of a translation. For that, it uses the text bounding box. But this bounding box is the logical bounding box, not the ink bounding box (see [Pango documentation](https://docs.gtk.org/Pango/method.Font.get_glyph_extents.html) to learn more about this).

The code to change is here:
https://github.com/Kozea/WeasyPrint/blob/5a74e3b785d96a974dd6ec7c76e172dbaba6f1de/weasyprint/svg/__init__.py#L492-L496

A dirty workaround would be to add some extra width/height.

**Comment by liZe** [comment]
> A dirty workaround would be to add some extra width/height.

I added this dirty workaround that should work in most common cases. Text support is in quite a bad shape for SVG, a real fix would require a lot of work…
