### ISSUE TITLE
Migrate to resvg?

### ISSUE THREAD

**Issue by baseplate-admin** [Kozea/WeasyPrint#2141]
Hi,

it seems that [resvg](https://github.com/RazrFalcon/resvg) has better svg support than cariosvg.

Would you guys be willing to shift to `resvg` if i write a wrapper over it?

**Comment by liZe** [comment]
Hi!

Thanks for your proposal, but I don’t think that we’re interested, for many different reasons.

1) First of all, we don’t use CairoSVG anymore, because WeasyPrint dropped Cairo a few years ago. We replaced it by an internal library inspired by CairoSVG, but that uses pydyf instead of Cairo for the output.

2) The current solution used in WeasyPrint is able to generate vector shapes directly in a PDF through pydyf. As far as I can tell (I can’t find the documentation), resvg generates raster images.

3) We try to depend on less non-Python dependencies (see #841).

4) The current SVG implementation is limited (and some of its code is pretty awful), but it’s not ridiculous. If you miss some features or have blocking bugs, you can report them, and we’ll see if it’s possible to fix that.

5) We believe in [web diversity](https://www.courtbouillon.org/blog/00025-goodbye-web-diversity/), that’s why we’ve had the stupid idea to write our own HTML/CSS rendering engine 🙃. Let’s improve this implementation of SVG instead of killing it!

So… Long live resvg, and long live WeasyPrint’s implementation of SVG.

**Comment by baseplate-admin** [comment]
Alright thanks for insight
