### ISSUE TITLE
Duplicate Sequence Diagram Board Lines

### ISSUE THREAD

**Issue by lixueyi83** [Kozea/WeasyPrint#2181]
### Here is the original plantuml source code:

```ascii
```plantuml
@startuml
loop ["forever loop"]
A -> B: Request
alt #lightblue [yes]
B -> C : Request
C -> B : Reponse:yes
else #pink [no]
B -> C : Request
C -> B : Reponse:no
end
end
@enduml
```
```

### This is the generated PDF file,

[a.pdf](https://github.com/user-attachments/files/15813098/a.pdf)

By the way, I have no problem with other plantuml diagrams, such as flowchart and state diagrams. This issue is only seen with the sequence diagram. Thanks.

**Comment by lixueyi83** [comment]
[a.pdf](https://github.com/user-attachments/files/15813096/a.pdf)
Attached the generated PDF file.

**Comment by lixueyi83** [comment]
[a.pdf](https://github.com/user-attachments/files/15813104/a.pdf)

**Comment by liZe** [comment]
Hi!

I suppose that it’s the same problem as https://github.com/Kozea/CairoSVG/issues/266: the duplicated lines are supposed to be shadows, that are not supported in WeasyPrint because they are not supported by PDF (other than with raster images).

Could you try to use `skinparam shadowing false` and see if it fixes the problem?

**Comment by lixueyi83** [comment]
Thanks very much, that fixed the problem instantly! Have a great day! 🍻
