### ISSUE TITLE
weasyprint module not found by python

### ISSUE THREAD

**Issue by pbale** [Kozea/WeasyPrint#2186]
Hello,

I am trying to use weasyprint with python to convert html to pdf. I have set up a venv on vscode on MAC and installed weasyprint using home brew. 
I am using the snippets showed in the documentation https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#instantiating-html-and-css-objects to create pdf's. 

When I run the script, it complains that the weasyprint module is not found. I tried installing weasyprint both pip3 install and brew install still no use. Can someone help me in this regard.

I have 
python 3.12.1
weasyprint 62.2
MAC sonoma 14.5

Thanks,
pbale

**Comment by liZe** [comment]
> When I run the script, it complains that the weasyprint module is not found. I tried installing weasyprint both pip3 install and brew install still no use. Can someone help me in this regard.

Hi!

The easiest way to use WeasyPrint on macOS is to use Homebrew. Installing WeasyPrint with Homebrew also installs Python from Homebrew, that’s this version of Python you have to use.

```zsh
user@host ~ % brew install weasyprint
user@host ~ % which python3  # should print a Homebrew path
user@host ~ % python3
```

Then, in Python:
```python
>>> import weasyprint  # should work
```

**Comment by pbale** [comment]
I followed these steps and see the below error. 
<img width="756" alt="Screenshot 2024-06-18 at 1 46 00 PM" src="https://github.com/Kozea/WeasyPrint/assets/1521151/7c709557-1ebf-4f68-a9e0-87c6ccc17cc6">

**Comment by pbale** [comment]
Thank you for being prompt. I have tried the steps in a new mac terminal and attached the screenshot of this.

<img width="967" alt="Screenshot 2024-06-18 at 3 42 43 PM" src="https://github.com/Kozea/WeasyPrint/assets/1521151/49ea0a70-b685-456b-ba77-e6c2f78f7ed8">

**Comment by liZe** [comment]
`which python3` returns a path to another version of Python, not Homebrew’s Python. That’s why it doesn’t work.

You can either:
- uninstall the other version of Python installed in `/usr/local/` if you don’t need it for other projects, or
- launch Homebrew’s Python using its full path instead of just `python3`: `$(brew --prefix python)/libexec/bin/python3`.

My advice is to install and use a single version of Python for all your projects, if possible. Otherwise, you’ll easily be lost between the different versions.

If you want to learn more about Python with Homebrew, there’s a [very useful documentation](https://docs.brew.sh/Homebrew-and-Python).

**Comment by pbale** [comment]
I have uninstalled the python and installed home brew python and still see the same issue. 

<img width="841" alt="Screenshot 2024-06-18 at 4 22 33 PM" src="https://github.com/Kozea/WeasyPrint/assets/1521151/b6afd331-59f0-44d5-82ba-053e63106254">

**Comment by liZe** [comment]
`which python3` gives the right folder, that’s good news!

Let’s reinstall weasyprint, to be sure:
```
brew uninstall weasyprint
brew install weasyprint
```

And then
```
python3
>>> import weasyprint
```

If it doesn’t work, you definitely have something wrong in your Homebrew installation, and your problem is not related to WeasyPrint. As we don’t even have a Mac computer to test, we’re probably not the best people to help you with that.

**Comment by pbale** [comment]
Yep, did install/unistall weasyprint as well. That didn't change the results. 
I will see whats going on. thank you for the support.

**Comment by pbale** [comment]
Ok, Finally! It worked... I have uninstalled everything and installed python3 through homebrew, create venv on vscode, activated it and then installed weasyprint with pip3 and boom. Everything works don't know what went wrong earlier and what I did right this time.

**Comment by liZe** [comment]
Good to know. Have fun with WeasyPrint!

**Comment by leviouwendijk** [comment]
I wanted to install some scripts (that relied on Weasyprint) on another machine, but I kept running into dependency sourcing issues when it came to Weasyprint. I ran into this so many times now, that it prompted me to dig into it deeper.

Unbeknownst to me the issue was caused, in my case, by having installed Weasyprint twice in two different places, managed by two different package managers.

I had installed Weasyprint as a Python module with pip. This installed the Weasyprint dependency within the scope of my Python3.11 install, or the binary:

`/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11`

Later, I installed Python through Homebrew (I know), changing my default Python path into:

`/opt/homebrew/bin/python3`

Whenever invoking Python scripts that used Weasyprint, in order for the Weasyprint package to work, it required me to specify the 3.11 binary, because that version of Python was the only one with access to a Python module of Weasyprint.

After running into issues with invoking that binary, I (of course) at some point thought it wise to check my install of Weasyprint, and this led me to install Weasyprint again using Homebrew. But, naturally, all this did was place a new binary of Weasyprint somewhere else, namely:

`/opt/homebrew/bin/weasyprint`

And Homebrew, now managing the install of Weasyprint, did not allow me to install Weasyprint using pip, unless specifically forcing it to do so--at the risk of breaking packages. I did not really feel like doing that, expecting more headaches in the future.

Since I somehow, at some point, found out that my Python3.11 _was_ able to execute Weasyprint properly, it made me dig into _why that version could_, but any other version couldn't, and why the Homebrew install of Weasyprint did not affect it whatsoever. I retraced the binary of Weasyprint, then, to two locations: one in the Python3.11 framework, and one in Homebrew.

I rewrote my Python pdf script into a Swift one, that uses the Homebrew's Weasyprint CLI binary. That is what suited my intended use case better after all. But Python seems to require the Python-tailored pip package for Weasyprint, not that of Homebrew (although I do not know this with certainty)--it at least cannot reach brew's Weasyprint binary by default. Perhaps an uninstall of Homebrew's weasyprint (and--for me--some reconfiguring of my default Python path) would allow pip to install it without restriction.

If I were to use Python with Weasyprint now, I'd likely do it either through a virtual environment or a docker image. Or just install Weasyprint into a specific Python binary, and intentionally invoke that Python version for the script's execution. For now, I am glad to be able just using the CLI version. Perhaps I'd even prefer invoking that in my Python scripts with subprocess, if it ever comes to it.

This sure taught me a lesson on dependency management..
