### ISSUE TITLE
Support Pango GDI/DirectWrite on Windows

### ISSUE THREAD

**Issue by danyeaw** [Kozea/WeasyPrint#2227]
Gvsbuild allows for building Pango on Windows (and the rest of the GTK stack) with MSVC. Someone posted an issue requesting FontConfig to be re-enabled on Windows: https://github.com/wingtk/gvsbuild/issues/1411

It looks like FontConfig is being used cross-platform for WeazyPrint and PangoFT2 is being using to create a font map. However, I am used to seeing GTK related Windows apps using the GDI/DirectWrite backend for Pango since it is what is native.

Would it be possible to switch to using PangoCairo for this? It abstracts multiple pango backends. So WeasyPrint could use FontConfig (discovery) & FreeType (rendering) on Linux, GDI/DirectWrite on Windows and CoreText on macOS. This would help limit some external dependencies and improve cross-platform compatibility.

**Comment by liZe** [comment]
Hi!

> Would it be possible to switch to using PangoCairo for this? It abstracts multiple pango backends. So WeasyPrint could use FontConfig (discovery) & FreeType (rendering) on Linux, GDI/DirectWrite on Windows and CoreText on macOS. This would help limit some external dependencies and improve cross-platform compatibility.

Using PangoCairo would require Cairo, that we actually [got rid of in the past](https://www.courtbouillon.org/blog/00004-weasyprint-without-cairo-what-s-different/). So that’s pretty sure that we won’t use it again, that would actually add dependencies, and that’s not what we want 😄.

But without PangoCairo, with just Pango, using the native font manager on each platform could theoretically possible. The problem is that we the would have to duplicate the whole font management system code for 3 different platforms, and that would be a maintenance hell.

> It looks like FontConfig is being used cross-platform for WeazyPrint and PangoFT2 is being using to create a font map. However, I am used to seeing GTK related Windows apps using the GDI/DirectWrite backend for Pango since it is what is native.

As long a you only want to access system fonts, which is most GTK apps do, using Pango with the OS’s native font management platform is great, that’s the default behavior.

But WeasyPrint has to do more, particularly to handle `@font-face` rules that require to finely detect if local fonts installed match a pattern, or to temporarily add fonts with overridden matching rules to the list of available fonts. The "simple" path we followed is explained in [this blog entry](https://mces.blogspot.com/2015/05/how-to-use-custom-application-fonts.html), it’s now more complex to handle the subtleties of CSS.

> Gvsbuild allows for building Pango on Windows

Is there something preventing you from using MSYS2 to install the dependencies? You also have the possibility to use the WeasyPrint executable on Windows, if you don’t want to spend time installing dependencies.

**Comment by manuvarkey** [comment]
> Is there something preventing you from using MSYS2 to install the dependencies? You also have the possibility to use the WeasyPrint executable on Windows, if you don’t want to spend time installing dependencies.

MSYS generated python wheels seems to be not compatible with those available in PyPI (see https://www.msys2.org/docs/python/). So difficulties arise when python packages from PyPI are to be used along with MSYS2 libraries.

Using the executable seems to be the only option for windows for the time being. However this will require the HTML & CSS to be written to disk against the python API case where these can be loaded from memory.

**Comment by liZe** [comment]
> Using the executable seems to be the only option for windows for the time being. However this will require the HTML & CSS to be written to disk against the python API case where these can be loaded from memory.

The executable can read from the standard input and can write to the standard output, you don’t even need to create files on disk.

> MSYS generated python wheels seems to be not compatible with those available in PyPI

In WeasyPrint’s documentation, MSYS is only used to install Pango and its dependencies, but Python comes from the Windows store, so it shouldn’t be a problem. The CI for tests installs standard Windows wheels coming from PyPI, for [cffi](https://github.com/Kozea/WeasyPrint/actions/runs/10339644391/job/28619277038#step:8:22) or [brotli](https://github.com/Kozea/WeasyPrint/actions/runs/10339644391/job/28619277038#step:8:48) for example.

**Comment by danyeaw** [comment]
I understand why FontConfig is being used now, thanks for that!

MSYS2 is a great project, but its version of Python is unofficial and highly patched. As you point out though, maybe for this project you can use Pango from MSYS2 and official Python.

We'll work on reenabling FontConfig for Gvsbuild, and I'll close this issue. Thanks again!
