### ISSUE TITLE
Mac M1 OSError: cannot load library 'gobject-2.0-0'

### ISSUE THREAD

**Issue by robtaylor** [Kozea/WeasyPrint#2272]
#1448  was closed, but is still happenning, even after following instructions on that bug.

The fix I found was to:
`export DYLD_LIBRARY_PATH=$HOMEBREW_PREFIX/lib`

Three options for completely fixing this issue:
1) build the binary dependencies as dependencies using [cibuildwheel](https://github.com/pypa/cibuildwheel) - Nice fix for supporting a broad range of linuxes/windows/mac, but a fair bit of effort;
2) Fix documentation to tell the user set the DYLD_LIBRARY_PATH (may have side effects); or
3) add a check for $HOMEBREW_PATH set, and if so that weasyprint is installed, and then set  DYLD_LIBRARY_PATH in the environment before calling import (or do this as an exception handling path)

**Comment by liZe** [comment]
Hi!

Does `brew install weasyprint` work for you?

**Comment by robtaylor** [comment]
No, it is insufficient.

**Comment by liZe** [comment]
Then report a bug to Homebrew.

**Comment by robtaylor** [comment]
That's not the issue. You seem to have ignored my original message..

**Comment by robtaylor** [comment]
But to be absolutely clear, just installing weasyprint in homebrew is a
fragile solution *at best*, especially if combined with venv or an
environment manager like PDM.

**Comment by robtaylor** [comment]
I'd be happy to produce a patch for you, btw.

Yes, the installed brew works fine. What doesn't work is that we use PDM to
manage our build & deployment environments, and it fails there - and I'd
expect that to be the case as it may or may not be producing a python
environment using an installed homebrew python, depending on the locked
python version and the specifics of the developer's machine.

Hence the suggestion above - just installing the binaries in homebrew isn't
in general sufficient, and I've given potential ways to solve the issue. I
would personally go for the most robust way to reduce support load.

**Comment by liZe** [comment]
> Yes, the installed brew works fine.

Cool!

> What doesn't work is that we use PDM to manage our build & deployment environments, and it fails there - and I'd expect that to be the case as it may or may not be producing a python environment using an installed homebrew python, depending on the locked python version and the specifics of the developer's machine.

Homebrew libraries and Homebrew Python are built to work together. If a user uses Homebrew’s Python, we can quite safely guarantee that it will work. And if it doesn’t, the problem is probably in Homebrew’s packages.

If users want to use Homebrew libraries with another version of Python, it’s a bit more complicated. For example, your version of Python has to be built for the same architecture as your Hombrew packages. Depending on what the user do, using `uv` or `pdm` may install a version of Python that won’t work with Homebrew libraries, leading to a mess we don’t want to debug.

We don’t want to say that it’s impossible to use WeasyPrint using another version of Python that Homebrew’s, we just want to be clear that it’s not supported, and that users are on their owns if they want to use another way. We don’t even have a Mac, we can’t help everybody.

That being said, if there are ways to help people use WeasyPrint and reduce our free support time, by improving documentation, it’s always welcome.

> 2\. Fix documentation to tell the user set the DYLD_LIBRARY_PATH (may have side effects); or

It seems to be the best idea in my opinion. It’s actually already in [the documentation](https://doc.courtbouillon.org/weasyprint/stable/first_steps.html#troubleshooting).

**Comment by liZe** [comment]
Don’t hesitate to add a comment if there’s anything more we can do.
