### ISSUE TITLE
Passing python variables safely to stylesheet

### ISSUE THREAD

**Issue by AjobK** [Kozea/WeasyPrint#2295]
Hi again,

I was wondering if there is any way to set css vars from python, and if not, if this feature could be introduced.

**Context**

I am trying to set a `@top-left` content string inside a <style> tag of my Jinja HTML. If the python string contains HTML in it, it gets escaped improperly (HTML character entity such as `&lt;`). When I escape it myself in python, it works until I have quotes in the string that match the quotes used in CSS. I assume there would be more cases where this fails. Here's a snippet that simulates the behavior:

```jinja
        {% set hello = '"<h1>This is a program!</h1>' %}

        :root {
            --hello: "{{ (hello|safe) }}";
        }

        @page program {
            @top-left {
                font-size: 0.8em;
                color: grey;
                content: var(--hello);
            }
        }
``` 

If I remove the `|safe` pipe it simply shows HTML character entities again.

**Desired behavior**

I would like to be able to pass strings safely to a stylesheet, regardless of the content, and get a properly escaped string back. Using data-attributes is not an option, as I am not styling an HTML element, only `@top-left`.

Thank you in advance!

**Comment by ThiefMaster** [comment]
Setting CSS vars from Python would also be great for other cases, such as passing colors or similar from Python w/to having to make the CSS file a (Jinja or whatever else) template at all.

**Comment by ThiefMaster** [comment]
The problem is that when I interpolate data (that is coming from a user, and in my case it's actually a custom string to be used in `content` so not just something simple like a number) - in the stylesheet like this, I always need to deal with escaping...

And I think we all know (e.g. from SQL) that parametrizing is better than escaping! :)

**Comment by liZe** [comment]
> The problem is that when I interpolate data (that is coming from a user, and in my case it's actually a custom string to be used in `content` so not just something simple like a number) - in the stylesheet like this, I always need to deal with escaping...
> 
> And I think we all know (e.g. from SQL) that parametrizing is better than escaping! :)

CSS variables are defined in CSS and follow CSS rules, including cascade. If we really want to avoid CSS generation to avoid escaping, the only way would be to build CSS tokens manually out of given Python values. That’s for sure a potential source of horrible bugs, I really don’t want to do this in WeasyPrint. :smile:

Do you think there’s another possibility?

**Comment by ThiefMaster** [comment]
> CSS variables are defined in CSS and follow CSS rules

In a normal browser you can set CSS variables from JavaScript, so there's kind of precedence for what we'd like to have (e.g. `document.body.style.setProperty('--something', whatever);`).

I think it would be perfectly reasonable if CSS vars provided from Python were always be applied to the `:root` element.

**Comment by liZe** [comment]
> In a normal browser you can set CSS variables from JavaScript, so there's kind of precedence for what we'd like to have. For example, One can do `document.body.style.setProperty('--something', whatever);` to set the variable without having to put the value of `whatever` in a CSS string.

Unfortunately, we don’t have a DOM in WeasyPrint. I don’t see how we could inject CSS variables easily without generating CSS strings or building CSS tokens manually (and it doesn’t mean that we would like to do this if we could).

**Comment by ThiefMaster** [comment]
I guess there's some place that looks up CSS variables (climbing up the CSS tree up to `:root` as needed), isn't there, since you need that anyway for normal usage.

Being able to override that functionality to provide a fallback if no value has been found would already be enough (to provide a custom value instead of whatever default there is for undefined variables).

**Comment by liZe** [comment]
> I guess there's some place that looks up CSS variables (climbing up the CSS tree up to `:root` as needed), isn't there, since you need that anyway for normal usage.

You can take a look at this function:

https://github.com/Kozea/WeasyPrint/blob/ca74c8e81ce48b0f7b838492cab8634b9f1d33b7/weasyprint/css/__init__.py#L566-L589

If you want to inject CSS properties out of given Python values without escaping, I think that you’ll have to build tokens manually, because CSS variables are just CSS properties. We don’t want to do this in WeasyPrint for this use case.

If you think that it’s possible quite easily without creating tokens, you can open a pull request we can discuss about.

> Being able to override that functionality to provide a fallback if no value has been found would already be enough (to provide a custom value instead of whatever default there is for undefined variables).

Even if it was easily possible (I don’t think so), I’m really not convinced that we should add an API to inject CSS variables. For me, it’s an interesting corner case, but just a very limited corner case that users will always want to extend (I want to define other properties, with other selectors, etc).

You can already pass stylesheets to WeasyPrint, and that’s much more powerful. If you don’t want to deal with escaping, you’ll have to create tokens, and you can already do this yourself for your specific use case. Here’s a stupid example that doesn’t require an extra API, you can adapt it to your needs:

```py
from tinycss2 import ast
from weasyprint import CSS, HTML

variables = {
    "red": "faa",
    "blue": "12f",
    "green": "1f2",
}

prelude = [ast.LiteralToken(0, 0, ":"), ast.IdentToken(0, 0, "root")]
contents = []
for key, value in variables.items():
    contents.extend([
        ast.IdentToken(0, 0, f"--{key}"),
        ast.LiteralToken(0, 0, ":"),
        ast.HashToken(0, 0, value, is_identifier=False),
        ast.LiteralToken(0, 0, ";"),
    ])
rules = ast.QualifiedRule(0, 0, prelude, contents)
html = HTML("index.html")
html.write_pdf("output.pdf", stylesheets=[CSS(string=rules.serialize())])
```

But in my opinion, even if this code is simpler than overriding the CSS variables resolution, is too specific to be in WeasyPrint. We can let users adapt it for their needs without changing the API.

(And if you also want to avoid tinycss2’s serializer that escapes values for you, you can add a class that mimics `CSS` and avoid the whole serialize/reparse extra work.)
