### ISSUE TITLE
WeasyPrint 63.0 blocks upgrade of Pyphen to version 0.17

### ISSUE THREAD

**Issue by gmseb** [Kozea/WeasyPrint#2297]
Hello WeasyPrint team,

thanks for WeasyPrint! 🙏 

It came to my attention today that line…

https://github.com/Kozea/WeasyPrint/blob/ca74c8e81ce48b0f7b838492cab8634b9f1d33b7/pyproject.toml#L20

…currently blocks upgrading Pyphen to [0.17](https://github.com/Kozea/Pyphen/releases/tag/0.17.0) in the environment. It would be nice if that could be unblocked and this combination be supported. Thank you!

Best, Sebastian

**Comment by liZe** [comment]
We have a problem here, see #2294.

Before version 63, upper versions were not fixed, leading to problems like #2207. Now that they are fixed, we got two issues opened in less than a week.

We could enable dependabot to automatically get PRs for new versions, but we don’t want to release new WeasyPrint versions each time a dependency is updated. So that’s probably useless.

Many other libraries (Flask, Scikit-Learn, Pillow…) don’t define upper versions, maybe it was a bad idea to add them in WeasyPrint.

@gmseb @paulocoutinhox @nijel @violuke Feedback is welcome, don’t hesitate to share your needs and explain what would be best for you.

**Comment by liZe** [comment]
> With my Gentoo packager hat on, I have a clear vote for "no upper boundaries please"

Thanks a lot for your feedback (with my Gentoo user hat on)!

**Comment by paulocoutinhox** [comment]
Hi @liZe,

In my opinion is important keep dependencies updated and a new version compatible need be released.

You can adopt semver (https://semver.org/), and update the last number, example: 63.0.1.

It won't make any practical difference for you whether you release it or not, but for me as a user of the library it will. In these cases, I have to point directly to the master branch repository to bypass this.

Thanks.

**Comment by nijel** [comment]
I think Pillow API  is pretty stable and unlikely to introduce a breaking change, so removing the upper bound is certainly an option. The other option is to release a point release fast as soon as new version is tested (what should be automated via renovate or dependabot). We use that for Weblate.

**Comment by nijel** [comment]
Another thing to consider is that Pillow as track of fixing security issues in major releases (AFAIR it happened in 9.0.0 and 10.0.0), so users might be pushed to upgrade this particular dependency fast.

**Comment by paulocoutinhox** [comment]
Thanks. Im only wait for the new version to update my project to that.
