### ISSUE TITLE
Implement `target-counter` to create table of contents

### ISSUE THREAD

**Issue by sander76** [Kozea/WeasyPrint#23]
I'd like to automatically create a table of contents in my document.
I am thinking of using a small piece of Javascript.... 
But I have a feeling WeasyPrint doesn't process javascript.. ?
Or are there other ways of doing this ?

Sander.

**Comment by mzu** [comment]
Hi. Are there any news on implementing support for `target-counter()`? Are there any alternative ways to get a ToC with page numbers working with WeasyPrint?

**Comment by SimonSapin** [comment]
@mzu, please refer to https://github.com/Kozea/WeasyPrint/issues/23#issuecomment-46614037.

**Comment by ingcake** [comment]
Did anything happen related to the proof of concept @bitdivine posted last year? The docs don't seem to suggest so, this question is still open, the relevant source doesn't *look* like it supports it, and @bitdivine doesn't seem to have gone any farther with it.

If not, I might hack on it a bit and report back with some toy examples.

**Comment by SimonSapin** [comment]
@ingcake The last paragraph of https://github.com/Kozea/WeasyPrint/issues/23#issuecomment-62674356 is still relevant.

**Comment by ingcake** [comment]
Thanks. I'll have a look at it sometime in the next week.

**Comment by bitdivine** [comment]
I'm afraid I haven't followed up, and I'm unlikely to have time to do so in the near future.  I can but wish you bonne chance!

**Comment by ingcake** [comment]
I think I see a strategy for tackling the ToC issue as well as front matter in general. My concern is that this might fall into the aforementioned "very dirty hack" territory, and it requires fixing named pages.

The user could label specific content with `id=titlepage`, `class=frontmatter`, `class=content`. The document itself would also follow this order - the user would *not* place the table of contents at the end of the document. Then, we'd do something along these lines:
- Prior to rendering, append a copy of the front matter to the end of the document. Leave the original in place to serve as a dummy of sorts.
- The front matter receives page numbers via `counter(frontmatter, lower-roman)`. This counter needs to be reset so that the copy at the back of the document has the right page numbering.
- Call `render()`. The original (dummy) front matter will provide page numbers for the table of contents that lives in the copied front matter at the end of the document.
- Remove the dummy front matter using `page.anchors`, and replace it with the copied front matter at the end of the document.

If the above doesn't sound too hackish, I'd be interested in working on [named pages (#57)](https://github.com/Kozea/WeasyPrint/issues/57). With that worked out, the above should be far easier to implement. It seems like it would have a nontrivial impact on the WeasyPrint spec, though.

**Comment by mpicard** [comment]
bump? I really need a TOC

**Comment by liZe** [comment]
@mpicard bump? I really need a patch ;)

**Comment by mpicard** [comment]
@liZe bring me up to speed? From what I saw named pages is required as well?

**Comment by liZe** [comment]
AFAIK, creating table of contents in pure CSS is currently impossible.

Using named pages would be useful when using a strategy like @eenblam proposes. It would be useful, but it's not sufficient at all. And actually, it would be just a hack, not a real solution.

A quick and dirty way to get tables of content is @SimonSapin's first comment. But getting titles and page numbers would need `target-counter` and `target-text` (now defined in [CSS Generated Content Module Level 3](https://drafts.csswg.org/css-content-3/#target-counter)). Leaders (#247) would be a good point too.

So, if anyone is interested in closing this ticket:
1. `target-counter` and `target-text` are needed.
2. named pages (#57) would probably be useful.
3. `leader()` (#247) would be nice.

With (1.) and Python scripts, we can hack a table of contents with page texts and numbers. (2.) would probably be useful to put the table in the document in a quite clean way. (3.) adds cosmetics.

**Comment by eenblam** [comment]
@liZe I gave a similar disclaimer for my approach, so I'm not arguing that my proposed solution is at all ideal. That said ...

> "The CSS layout engine is written in Python, designed for pagination, and meant to be easy to hack on."

**Comment by liZe** [comment]
> @liZe I gave a similar disclaimer for my approach, so I'm not arguing that my proposed solution is at all ideal.

Yes, no offense!

> EDIT: The related CSS development doesn't seem like a priority for W3 at the moment. Perhaps a hack solution would be helpful in the meantime. It's possible that I can allocate time for this soon, since it's relevant to an upcoming project, but I can't make any promises today. I'm also not opposed to assisting with your (more sustainable) solution as time allows.

Cool! Adding a table of contents (tables and pages) at the end of the document is easy with only Python and lxml.

> I really recommend not to, but if you want to go with the dirty hack look at the Document.make_bookmark_tree() method. The problem is that by the time you can use it, the whole layout is done so it’s very contrived to add content at this point.

@SimonSapin is too shy to admit that his ideas are generally damn good. I really recommend not to follow his "I really recommend not to", just try to play with his awful dirty hack: it's a good way to understand how it currently works, what can be done (adding the ToC at the end) and what's impossible without big changes (getting page numbers before rendering the whole document, getting the titles without lxml, etc.)

**Comment by mpicard** [comment]
@eenblam send me a message if you decide to dig into this, I need a fix for this as well so I would be willing to help out and discuss with you what I find.

**Comment by cliuser** [comment]
Too bad you can't handle JS.  Phil Schatz's css-polyfills.js shim handles a slew of CSS3 generated content.  I have a demo HTML doc with autogenerated  TOC, LOF, LOT, and Acronym sections (MIL-STD style).  All it needs is leader() for the front matter.

**Comment by doronhorwitz** [comment]
I do realise that this issue had its name changed to handle the implementation of 'target-counter',  however, whenever you search for information about generating a table of contents using WeasyPrint, you land up here, and the contents of this issue thread make it seem as if generating the table of contents isn't straightforward. But I'd just like to emphasize that it _**is**_ straightforward, making WeasyPrint even more appealing. The [3rd comment](https://github.com/Kozea/WeasyPrint/issues/23#issuecomment-11372310) by @SimonSapin at the beginning of the thread basically explains how to do it, but I'd just like to outline what I did so that anyone coming back here doesn't leave as disappointed as I originally left, because as I said, it is possible and straightforward (and does not use "very dirty hacks" nor is it ""contrived", as @SimonSapin put it):

1) generate the `document` object of the content you're making into a PDF using `<h1>...<h6>` tags to generate bookmarks, something like:
```
html = """
<h1>A Title</h1>
<p>Some content</p>
<h2>A subtitle</h2>
<p>Some more content</p>
"""
document = HTML(string=html).render()
```
2) To generate the table of contents string, use the code slightly modified from [this link](http://weasyprint.readthedocs.io/en/stable/tutorial.html) (from the WeasyPrint website!) - search for _"Print the outline of the document."_:

```
def generate_outline_str(bookmarks, indent=0):
    outline_str = ""
    for i, (label, (page, _, _), children) in enumerate(bookmarks, 1):
        outline_str += ('%s%d. %s (page %d)' % (
            ' ' * indent, i, label.lstrip('0123456789. '), page))
        outline_str += generate_outline_str(children, indent + 2)
    return outline_str
table_of_contents_string = generate_outline_str(document.make_bookmark_tree())
```
Note: you'll definitely have to modify this code to format the table of contents in HTML nicely

3) generate a table of contents page in a new document
```
table_of_contents_document = HTML(string=table_of_contents_string).render()
table_of_contents_page = table_of_contents_document.pages[0]
```

4) insert the table of contents page into the original document
```
document.pages.insert(0, table_of_contents_page)
```

5) write your PDF
```
document.write_pdf(target='myfile.pdf')
```

**Comment by LegoStormtroopr** [comment]
@doronhorwitz You are a genius - that little recipe needs to be included in the WeasyPrint documentation, being unable to have tables of contents was one of the reasons I wasn't using this library

**Comment by benjaoming** [comment]
@doronhorwitz how does this approach handle page numbers, say when the table of content is 1, 2, 3 pages long? Can it break the table into several pages?

**Comment by LegoStormtroopr** [comment]
From what I can tell from the code its pretty boiler plate, leaving the actual construction of the "Table of Contents" up to who ever is using it. In this case, if it is HTML there are no breaks so its a big run on blob of text.

Changing the `outline_str` like this:

        outline_str += ('<div>%s%d. %s <span style="float:right">(page %d)</span></div>' % (
            ' ' * indent, i, label.lstrip('0123456789. '), page))

The above gets page numbers floated on the right (like most tables of contents), the rest of the styling is left as an exercise for the reader, but it would likely be done in a template rather than in code and is indicative of how it would work.

But, the approach I am taking is this:
```
title_pages = HTML(string=table_of_contents_string).render()
table_of_contents_document = HTML(string=table_of_contents_string).render()

# Number the pages of the main document (eg. using CSS counters)
document = HTML(string=MAIN_DOCUMENTtable_of_contents_string).render()

document.pages.insert(0, title_pages)
document.pages.insert(1, table_of_contents_page)

document.write_pdf(target='myfile.pdf')
```

Its important to note the "main part of the document" will have the pages number normally, with the title pages and table of contents outside that main flow (much like a regular document anyway), so regardless of how big the table of contents gets its flow doesn't mess the page count of the "actual document".

**Comment by mb21** [comment]
From what I gather in this issue, the problem is that you'd have to make a second pass to insert the page numbers in the TOC after the rest of the document is laid out. Could we then make the simplified assumption that the page numbers are absolutely positioned (or similar) and thus don't affect the position of the following boxes so we wouldn't have to trigger a reflow? It's not perfect, but it would be very useful... so we wouldn't have to make another layout pass, but simply write some code to insert the (absolutely-positioned) page numbers after all the other layouting is done.

btw, here is some HTML/CSS to demonstrate how `target-counter(attr(href), page)` [would work to create a TOC](https://alistapart.com/article/boom#section8).

**Comment by Tontyna** [comment]
After diving into WeasyPrint's code for several days I finally brought `target-counter()` into life. It resolves targets within the limits of current WeasyPrint:

 1. No counters in @page-context except the fix coded `page`and `pages`, see also #289.
   
 2. `page` and `pages` aren't available in document context:

    ```css
    p::before(
       content: "this paragraph is on page " counter(page);
    }
    ```
        
    always yields `0` like any other undefined counter. 
  
 3. Exchange of counter values only via `string-set` in document elements and `string()` in @page-content css.
   
**Conclusion:**
The `target-counter()` doesn't solve the TOC-with-page-numbers problem.
Unless somebody redesigns Weasyprint to make at leas N°2 of the above list possible.

At the moment my implementaion of `target-counter` is still too debuggy to make a pull-request -- lots of comments and debug-statements that helped me understand how WeasyPrint works, oh my! Python is not my favourite language! But in the next days I'll clean up my code...

**Comment by liZe** [comment]
@Tontyna Fixing #652 also fixes this issue too, doesn't it?

Of course, the original problem is not really solved, as we can't create a TOC in pure CSS. As there's nothing in the spec allowing such a feature, we may just close this issue and add @doronhorwitz's reciepe to the documentation.

**Comment by Tontyna** [comment]
You're right. A TOC requires a script, @doronhorwitz 's is a good starting point. Although the page numbers wont be the right ones when `counter-increment/-reset` functions are used in the document. And it doesn't require neither `target-*` nor #652 at all. 

With #652 available I'd automate my TOCs with a script that extracts the headings / bookmark-labels and injects a html-snippet like the `<ol class="toc">` in the [comment](https://github.com/Kozea/WeasyPrint/pull/652#issuecomment-403276559).

**Comment by liZe** [comment]
> With #652 available I'd automate my TOCs with a script that extracts the headings / bookmark-labels and injects a html-snippet like the <ol class="toc"> in the comment.

Indeed.

**Comment by liZe** [comment]
I'm closing this issue, as there's nothing more we can do here according to the current CSS specifications. The HTML template engine has to add empty links, see the [report sample](https://github.com/Kozea/WeasyPrint/tree/gh-pages/samples/report) for an example.

**Comment by sudarshang** [comment]
@liZe could you please link to the code that generates the pdf in the `report sample`. From #652 it is not clear if @doronhorwitz 's script is no longer required.

**Comment by liZe** [comment]
> @liZe could you please link to the code that generates the pdf in the `report sample`.

I just called the `weasyprint report.html report.css` from the [report folder](https://github.com/Kozea/WeasyPrint/tree/gh-pages/samples/report).
