### ISSUE TITLE
Table overflow issue

### ISSUE THREAD

**Issue by kesara** [Kozea/WeasyPrint#2325]
This was tested in `WeasyPrint version 62.3` and `WeasyPrint version 63.0`.
This happens when `overflow-wrap` is set to `break-word` or `normal`. `anywhere` seems to work fine.

Input:
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width initial-scale=1.0">
  <title>Table with Links</title>
  <style>
    table {
      width: 100%;
      max-width: 10px;
      border: 1px solid black;
      overflow-wrap: break-word; /* or normal */
    }

    th td {
      border: 1px solid black;
      padding: 8px;
      text-align: left;
    }

    a {
      margin-right: 8px;
      text-decoration: none;
      color: blue;
    }
  </style>
</head>
<body>
  <h1>Example 1</h1>
  <table>
    <thead>
      <tr>
        <th>Header 1</th>
        <th>Header 2</th>
        <th>Header 3</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>
          <a href="https://example.org">123.456.78</a>,
          <a href="https://example.org">234.567.89</a>,
          <a href="https://example.org">345.678.90</a>
        </td>
      </tr>
    </tbody>
  </table>
  <h1>Example 2</h1>
  <table>
    <thead>
      <tr>
        <th>Header 1</th>
        <th>Header 2</th>
        <th>Header 3</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>
          <a href="https://example.org">foooooobar</a>,
          <a href="https://example.org">foooooobar</a>,
          <a href="https://example.org">foooooobar</a>
        </td>
      </tr>
    </tbody>
  </table>
  <h1>Example 3</h1>
  <table>
    <thead>
      <tr>
        <th>Header 1</th>
        <th>Header 2</th>
        <th>Header 3</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>
          <a href="https://example.org">S 123.456.78</a>,
          <a href="https://example.org">S 234.567.89</a>,
          <a href="https://example.org">S 345.678.90</a>
        </td>
      </tr>
    </tbody>
  </table>
  <h1>Example 3</h1>
  <table>
    <thead>
      <tr>
        <th>Header 1</th>
        <th>Header 2</th>
        <th>Header 3</th>
        <th>Links</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>Data foooooooooobar</td>
        <td>
          <a href="https://example.org">S foooooobar</a>,
          <a href="https://example.org">S foooooobar</a>,
          <a href="https://example.org">S foooooobar</a>
        </td>
      </tr>
    </tbody>
  </table>
</body>
</html>


```

Weasyprint PDF rendering:
![Image](https://github.com/user-attachments/assets/f41b826d-e3d5-496d-a370-5bbf977bc1a8)

Firefox rendering:
![Image](https://github.com/user-attachments/assets/c0a20b66-adc1-4887-bff3-d79675475049)

**Comment by liZe** [comment]
This bug is caused by a dirty workaround that has been hidden since… 2013.

https://github.com/Kozea/WeasyPrint/blob/3c6f9a5a55b79563e32c766a1b5409e1d20b3601/weasyprint/layout/preferred.py#L317

Here, during minimum size calculation, we break the line if we only have a space, because, well, spaces are a very common way to break lines. So:
- if we have only a space between tags, minimum size works thanks to this hack,
- if we have text with a space inside between tags, it works because the line can be split by `split_first_line`,
- if we have text with a space only at the beginning/end of the text between tags, it fails.

For example, your sample works without the comma between `a` tags, or with "a a" instead of the comma. With `, `, it fails.

It only fails with layouts where the minimum size is required (tables and floats for example), but it works for other full-width layouts thanks to the "real" algorithm:

https://github.com/Kozea/WeasyPrint/blob/3c6f9a5a55b79563e32c766a1b5409e1d20b3601/weasyprint/layout/inline.py#L744-L758

Just as for this code, we should get track of the letters at tags boundaries to detect possible line breaks correctly, or even reuse the real algorithm, but that would much more complicated, and probably much slower.

Or we can just replace the current hack that worked until now by another one that will hopefully work for the next 11 years.
