### ISSUE TITLE
Paragraph content is truncated on different environments

### ISSUE THREAD

**Issue by commx** [Kozea/WeasyPrint#233]
A few weeks ago I noticed that my Web application is generating invalid PDF files; While most PDF viewers can open the files, Adobe's Acrobat can't. Another side effect is that some parts of the contents is truncated for some reason.

I have a sample HTML file located at [here](http://www.commx.ws/devel/weasyprint_test1.html). It renders correctly on my Mac, but it doesn't on the Linux server that runs my web application. html5lib/tinycss/weasyprint/cairosvg/pango are the very same versions on both machines. For me, it looks like a fontconfig issue, but I was not able to solve it yet. Did anyone else had this issues as well?

I have attached two generated PDF files: The first one generated on the Mac (looks correct) and the second one generated on the Linux server (with truncated content).

Any hints that help me solving this issue is greatly appreciated. I absolutely like WeasyPrint and like to keep it as the PDF generator backend for my apps.

Thanks.

Attachments:
- [http://www.commx.ws/devel/out_mac.pdf](http://www.commx.ws/devel/out_mac.pdf)
- [http://www.commx.ws/devel/out_linux.pdf](http://www.commx.ws/devel/out_linux.pdf)

**Comment by liZe** [comment]
Tried on ArchLinux, same strange bug reproduced. I'm trying to fix it.

**Comment by liZe** [comment]
I can reproduce this bug only on Arch. Gentoo with 1.14.0 works for me. Looking if there's anything reported anywhere about this.

**Comment by arthru** [comment]
I juste checked with Debian Jessie and cairo 1.14.0 and I encountered the same problem. So I guess it is not Arch Linux specific...

**Comment by liZe** [comment]
I don't know why it was working for me on Gentoo, and why it was working on OSX. I've checked twice, the PDF attached to the bug report have been generated on OSX by Cairo 1.14.0, and it works, so that's not only related to Cairo 1.14.0.

I've installed Cairo 1.14.0 once again on Gentoo, and I now have the bug. Sigh.

The good news is that this bug has been fixed.
https://bugs.freedesktop.org/show_bug.cgi?id=85662
http://cgit.freedesktop.org/cairo/commit/?id=e4b78424ac82588bcb9b855d5b6d5872050d33f9
Installing this commit works for me, installing the parent commit doesn't, and the commit message seems to be highly related to the bug we have.

The bad news is that we have to wait for a release of Cairo. 14 months were needed to release the last version (it was a major one). Patches can probably be easily added to Cairo packages in some distros when the bug is reported (Arch, Gentoo for example), but it will be pretty hard for other ones relying on vanilla releases (binary packages distributed for OSX for example).

Please try the patch or install the git version of Cairo, and please tell me that it works for you :)!

**Comment by liZe** [comment]
I finally know why this bug cannot be reproduced everywhere: it depends on the default font used by Cairo to produce the PDF. So the bug in Cairo is the only cause of the bug in WeasyPrint, but from same HTML, WeasyPrint can produce broken or valid PDF files depending on the font used to render the text.

**Comment by liZe** [comment]
Cairo 1.14.2 has been released, does it fix the bug for you?

**Comment by arthru** [comment]
Seems ok for me...

**Comment by commx** [comment]
I can confirm this to be fixed with cairo 1.14.2. Thanks a lot for your effort.

**Comment by loscil06** [comment]
I can attest the issue persist in Cairo 1.16.0-4 using the latest weasyprint, using Ubuntu 19.04

**Comment by liZe** [comment]
> I can attest the issue persist in Cairo 1.16.0-4 using the latest weasyprint, using Ubuntu 19.04

It's probably another bug, please open a new issue.
