### ISSUE TITLE
Border spacing is not working

### ISSUE THREAD

**Issue by ddeath** [Kozea/WeasyPrint#245]
between 2 td is gap even when I add border-spacing: 0px; to my css

**CSS Example**

    @page {
        margin: 0;
    }
    
    /*--------- Graphs ---------*/ 
    
    .graphs table {
        height: 2.7em;
        border-spacing: 0px;
    }
    
    .graph-real, .graph-ideal {
        width: 0.2cm;
        display: inline-block
    }
    
    .energy .graph-real {
        background-color: #3ba03b;
    }
    
    .energy .graph-ideal {
        background-color: #8fd48f;
    }

**HTML example**

    <html>
    	<body>
    		<div class="graphs energy">
    			<table>
    				<tbody>
    					<tr>
    						<td class="graph-real" style="height:2.6708571428571em"></td>
    						<td class="graph-ideal" style="height:2.7em"></td>
    					</tr>
    				</tbody>
    			</table>
    		</div>
    	</body>
    </html>

**wrong PDF output:**
![wrong output](https://cloud.githubusercontent.com/assets/2537379/6546265/b5ab3a56-c5ad-11e4-931e-2dc5d87d7531.png)

**desired PDF output:**
![desired](https://cloud.githubusercontent.com/assets/2537379/6546266/ba51cbce-c5ad-11e4-8f5a-7ff37a333ace.png)
**css hack which solve the problem:**

    .graphs table td:first-child {
        position: relative;
        left: 5px;
    }

**Comment by liZe** [comment]
There's no bug, the rendering is actually OK. From the CSS2 spec:
> If a child C of a 'table-row' box is not a 'table-cell', then generate an anonymous 'table-cell' box around C and all consecutive siblings of C that are not 'table-cell' boxes.

As your tds are inline-blocks, one anonymous cell is created around the two tds. The space you see is actually the newline and space characters between the two tds transformed into one single space according to the standard HTML and CSS rules.

Firefox gives the same rendering as WeasyPrint. Chrome gives your desired output. I think that both can be defended, because "around C and all consecutive siblings of C" is not really clear: do we need to:
- keep space-like characters between these siblings (add an anonymous starting tag before C and a closing tag after the last sibling, like Firefox or WeasyPrint), or
- just keep the real siblings (add an anonymous tag with only the real siblings inside, like Chrome)?

I don't want to answer this question. It makes me sad and I prefer to be happy.

**Comment by SimonSapin** [comment]
I’m not sure if it helps, but https://drafts.csswg.org/css2/tables.html#x21 defines “consecutive” as:

>     Two sibling boxes are consecutive if they have no intervening siblings other than, optionally, an anonymous inline containing only white spaces. A sequence of sibling boxes is consecutive if each box in the sequence is consecutive to the one before it in the sequence.

**Comment by liZe** [comment]
That's a good point, because we're now sure that these tds are consecutive and that they are in the same anonymous cell. But it doesn't help to define if the anonymous inline box must be included with the siblings or not.

**Comment by SimonSapin** [comment]
I don’t see anything in the spec that says it should be removed, but meh.

Regardless, @ddeath, you may be able to work around this by removing `display: inline-block` and letting the `<td>`s have they default `display: table-cell`.
