### ISSUE TITLE
How to get page content of HTML.render() method

### ISSUE THREAD

**Issue by Jim25** [Kozea/WeasyPrint#265]
In the API documentation I see this description:
"Lay out and paginate the document, but do not (yet) export it to PDF or another format.
This returns a Document object which provides access to individual pages and various meta-data"

I can iterate over the the page list in the document, but how can I extract content of each page?

For example I want to know the first content of each page. some method like page.get_content...

**Comment by SimonSapin** [comment]
Define "content". What do you need from the page? Plain text, geometrical information, something else? And why? What are you trying to do?

Each `Page` object has a `page._page_box` attributes that represents the output of CSS "layout" (determining the size and position of everything on the page) and the input of "painting" (writing the output file). It is the root of a tree of "boxes", objects whose classes are defined in `weasyprint/formatting_structure/boxes.py`. It is not intended to be used by anything outside of WeasyPrint itself. In is **an implementation detail** that is deliberately not documented, and has zero promise of stability between any WeasyPrint versions. (Although there is is not much risk there since development is effectively inactive.) In another language this would be a private attribute, but this is Python so you can totally go and mess with it. But do you really want to?

**Comment by Jim25** [comment]
@SimonSapin 

Thanks for your answer. Well, my purpose begins from another story. 
My mission is:
I have a long .HTML/.XHTML file, and I want to simulate the function [print preview] of browser when display these files on a browser.

Then I become to find a way to break the HTML file to separate pages, This is such a pain. I researched a lot but until now I can't find any library or method to page break the HTML file.

I think if I can find a library to render the HTML file and provide pagination in memory or at least give  a hint to page break. I found that WeasyPrint seems to meet my requirement because I see the Render() method, The document and the Page object. But as you known, I can iterate over page and can export to .PDF, .png but can not extract information about what point to page break.

I know this using is completly wrong with the purpose of WeasyPrint but I want a try.

Anyway, thank you for reading and answer my question.

**Comment by SimonSapin** [comment]
So from WeasyPrint’s `Page` objects you want to know "where" in the HTML source a page starts and ends? That’s difficult as the internal layout tree has gone through a number of transformations from the source tree, and it’s not well-defined in the presence of [parallel flows](https://drafts.csswg.org/css-break/#parallel-flows) (even through WeasyPrint doesn’t support them well).

But even if you could get that information, what next? WeasyPrint’s layout and page-breaking algorithm is different from the browser’s, so a "print preview" you could show that way would probably not match the actual results if the document is to be printed by the browser rather than by WeasyPrint.

If you have WeasyPrint generate a PDF to be printed however, then you could also generate a PNG of each page to show in the browser.

**Comment by Jim25** [comment]
Thanks for your explanation. I will try to show PNG in the browser as your suggestion.

**Comment by SimonSapin** [comment]
Closing as I don’t think there is something to change in WeasyPrint here.
