### ISSUE TITLE
Dynamic page width .

### ISSUE THREAD

**Issue by crrp88** [Kozea/WeasyPrint#274]
Good morning,
I have a html that is generated dynamically, it is a table, and the columns are being added depending on a selector, when exported to pdf it cuts the last columns.
How I can change this behavior?
It is possible that the width of the pdf changes with the width of all columns so these can fit?

**Comment by SimonSapin** [comment]
Short answer: no, this is not possible. It’s a fairly fundamental principle of CSS layout that widths are the "input" that everything else is normally based on.

That said, maybe you can hack something together. For example:

1. In CSS, use for example `@page { size: 1000000mm 297mm }` with a a very large width
2. In Python, use [`HTML.render()`](http://weasyprint.org/docs/api/#weasyprint.HTML.render) to get a [`Document`](http://weasyprint.org/docs/api/#weasyprint.document.Document) object.
3. Iterate `document.pages` to reach [`Page`](http://weasyprint.org/docs/api/#weasyprint.document.Page) objects.
4. Use `page._page_box` to reach the "box tree". This tree is what layout works on. It roughly corresponds to the tree of HTML elements. The box tree is not part of the public API: it’s not documented, and could in theory change in arbitrary way between versions. That said, since no active development is really happening on WeasyPrint at the moment, radical changes are unlikely. The classes of objects that make up this tree are in [`weasyprint/formatting_structure/boxes.py`](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/formatting_structure/boxes.py). See [`weasyprint/tests/test_layout.py`](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/tests/test_layout.py) for example of code that extracts information from this tree.
5. Find a `TableBox` object in the tree and read its `.width` attribute. It is measured in CSS `px` units.
6. Back on the page object, set *its* `.width` attribute appropriately. I *think* it’s in the same unit. Don’t forget page margins. This attribute was not intended to be set, but this is Python so you can do it and see what happens.
7. Finally, write your modified document with [`document.write_pdf()`](http://weasyprint.org/docs/api/#weasyprint.document.Document.write_pdf).

This effectively renders a very wide document and then cuts it, so anything like `text-align: right` that is based on the right edge is gonna be wrong.

**Comment by sebasmagri** [comment]
Hi! This is the snippet we ended up using:

```
        pdf_doc = pdf_writer.render(
            stylesheets=[styles]
        )

        for page in pdf_doc.pages:
            for children in page._page_box.descendants():
                if isinstance(children, TableBox):
                    needed_width = children.width + \
                        page._page_box.margin_left + \
                        page._page_box.margin_right

                    # Override width only if the table doesn't fit
                    if page.width < needed_width:
                        page._page_box.width = needed_width
                        page.width = needed_width

        pdf_doc.write_pdf(file_alike)
```

The huge width hack in the stylesheet wasn't needed in the end. @crrp88 I believe we may close this one unless @SimonSapin has something to add.

**Comment by SimonSapin** [comment]
https://github.com/Kozea/WeasyPrint/blob/v0.42.3/weasyprint/formatting_structure/boxes.py#L540

**Comment by GMKBabu777** [comment]
I also have a similar problem, I tried many ways, but it does not work. 

Expected pdf output:
![image](https://user-images.githubusercontent.com/47376118/123678198-a5cd7700-d863-11eb-8ef7-4ea50a09934b.png)

Actual output:
![image](https://user-images.githubusercontent.com/47376118/123678759-5b002f00-d864-11eb-84b3-a06a5a9715cd.png)

Can you help me with how to fix this?
