### ISSUE TITLE
Placing images on the outside of page

### ISSUE THREAD

**Issue by mssoftde** [Kozea/WeasyPrint#276]
I'm trying to create a catalogue using WeasyPrint and I need to place images on the outside of each page (float:left on left page and float:right on right page).
Is there any chance to achieve this?

**Comment by SimonSapin** [comment]
WeasyPrint can not do this at the moment.

The difficulty with this is the potential dependency cycles between style and layout: where an element is in the document is based on where other (typically earlier) elements are, and on the value of CSS properties. If the value of properties also depends on which page an element is on (where it is), there is no clear way to compute one after the other in the code, and some cases don’t even have a clear solution. For example, a `float: left` element might be too big to fit on a left page, say if it also has `clear: left` and the page has other `float: left` elements, and needs to be “pushed” to the next page. But if that makes it `float: right` it might fit on the earlier page after all. It’s also bad to keep a result based on which order things where attempted/computed, since different implementations might do different things there.

**Comment by mssoftde** [comment]
Ok, I understand what you mean.
Is there any way for me to implement a "special" version for my use case? E.g. implementing float:outside like Prince does?

**Comment by SimonSapin** [comment]
Hum, I was thinking of a more general feature for arbitrary element styles based on page selectors, but `float: outside` might be more realistic.

It’s easy to add the new keywords to the property [in `css/validation.py`](https://github.com/Kozea/WeasyPrint/blob/0040f4799c9c3d02dd309af36ea44ad22fa15c20/weasyprint/css/validation.py#L804), but then their handling is a bit all over the place in `layout/*.py`. I also don’t remember from the top of my head how to check whether you’re on a left or right page. See what objects created in `layout/pages.py`, and if necessary add stuff to `LayoutContext`.

**Comment by E-M-P-I-R-E** [comment]
Simon, would you do something like this to determine left or right?

right_page = page._page_box.page_type.endswith('right_page')

I just did this recently, by chance (just for testing; displaying some CSS
values in the document so I didn't have to keep track of what document got
what styles).

**Comment by SimonSapin** [comment]
> right_page = page._page_box.page_type.endswith('right_page')

Yeah, that looks ok.

**Comment by mssoftde** [comment]
Thanks for the hints. I'll try to add `float:outside` and `float:inside`the next days.

**Comment by liZe** [comment]
@mssoftde Can't you use `float: left` in `@page:left` and `float: right` in `@page:right`?

**Comment by mssoftde** [comment]
@liZe I tried this approach, but it didn't work.

**Comment by liZe** [comment]
@mssoftde Why?

**Comment by mssoftde** [comment]
@liZe I'm not sure. It's quite some time since I tried this, so I don't remember all the details, but I think WeasyPrint just ignored the float setting.

**Comment by liZe** [comment]
> It's quite some time since I tried this, so I don't remember all the details, but I think WeasyPrint just ignored the float setting.

Of course it did: page rules can change page properties, not properties on their children.

Unfortunately, the two solutions I can think of are not available in specifications:
- Using `float: outside` would be great, but it's not defined in [page floats](https://drafts.csswg.org/css-page-floats/).
- We could also use [media queries](https://www.w3.org/TR/mediaqueries-4/), but there's no media feature to get left/right pages, or page numbers, or page names.

The media query solution would open a large field of useful features, that's probably the way to go. We could add the left/right page media feature. Let's fix #494!

**Comment by liZe** [comment]
Closing, as it would be solved by #494.
