### ISSUE TITLE
SVG getting mangled when I export to pdf

### ISSUE THREAD

**Issue by kennedydane** [Kozea/WeasyPrint#278]
Hi Simon,

I've put my test case [here](https://github.com/kennedydane/IssueWithWeasy). Essentially the html output is from a jinja2 script and the svg is from ggplot (python's one, not R). I can't imagine why it would make a difference, and it didn't, but I used weasyprint in both CLI and in python. The pdf is just fine if I export my image to png (except the png is uglier and bigger).

Thanks for any help you can give,
Dane.

**Comment by SimonSapin** [comment]
@liZe is you cairo patch published somewhere?

**Comment by SimonSapin** [comment]
So, as I mentioned on IRC, this looks like a bug in Cairo that @liZe has investigated before. The PDF backend has an optimization to skip painting things that are invisible as they’re completely outside of their clipping area, but in some cases it uses an incorrect transform matrix somewhere and compare coordinates in different coordinate spaces.

Recompiling cairo with the patch at http://lists.cairographics.org/archives/cairo/2013-May/024301.html should fix the issue.

Alternatively, there’s a work around: change the `width` and `height` attribute of the root `<svg>` element to be smaller (by the same ratio, like 2x or 4x, to preserve the image’s aspect ratio) (the `viewBox` attribute preserves the internal coordinates so that you image will scale rather than crop), then in your document set the `width` or `height` CSS property of the HTML `<img>` element to compensate.

This should give the same rendering, but using a different code path that avoids the bug.

**Comment by kennedydane** [comment]
Super, thanks! I think the latter will be pretty easy to implement.

/me goes and tries.

**Comment by kennedydane** [comment]
Oh, btw, while trying to figure out what was potting I noticed in image.py that quite often you're setting `self.intrinsic_ratio`, where setting `self._intrinsic_ratio` would be more consistent. I couldn't find where intrinsic_ratio was actually used, so it might not even be a problem. But ya. Seemed odd to me.

**Comment by kennedydane** [comment]
Yay, just changing that width and heigh parameter worked like a charm.

**Comment by SimonSapin** [comment]
It’s been a while since I looked at `image.py`. If you think there’s a bug there, please file an issue with details or submit a PR!

**Comment by kennedydane** [comment]
I'm not really confident in my knowledge of the code, but I'll try to make a contribution a bit later in the week.

**Comment by liZe** [comment]
http://lists.cairographics.org/archives/cairo/2013-May/024301.html

I've tried to send the patch twice on the mailing list, and twice directly with the author of the commit.

**Comment by liZe** [comment]
http://lists.cairographics.org/archives/cairo/2015-December/027126.html

**Comment by liZe** [comment]
And one more, sent with git-send-mail after a remark from a member of the mailing list:
http://lists.cairographics.org/archives/cairo/2016-January/027185.html

**Comment by liZe** [comment]
Someone with the same problem:
https://lists.cairographics.org/archives/cairo/2016-April/027371.html

**Comment by liZe** [comment]
Yeah! The patch finally got accepted!

https://cgit.freedesktop.org/cairo/commit/?id=d2f1ebf579ba12b816eec9317f98eb845fbfeb4f

**Comment by kennedydane** [comment]
fantastic :-).

On Sat, Apr 16, 2016 at 12:08 PM, Guillaume Ayoub <notifications@github.com>
wrote:

> Closed #278 <https://github.com/Kozea/WeasyPrint/issues/278>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kozea/WeasyPrint/issues/278#event-629860786>
>



-- 
------------------------------
Dane Kennedy
Mobile: +27 76 313-8235
------------------------------

If you really want something in this life, you have to work for it. Now,
quiet! They're about to announce the lottery numbers
-- Homer Simpson
