### ISSUE TITLE
Margin missing after page break

### ISSUE THREAD

**Issue by damoser** [Kozea/WeasyPrint#279]
Dear all,

I noticed, that there is a small margin between the top-center box and the first element of a page when it's either the first page or a new page after an explicit page break. After an implicit page break this margin is gone. Please see this jupyter notebook for an example: http://nbviewer.ipython.org/gist/anonymous/b2e335d9122978664fc0

As you can see, on the first page of the pdf, there's some space between the top box and the container which is missing on the second page.

Can someone explain this behaviour or is there some way to control this margin?

**Comment by SimonSapin** [comment]
This may be the 8px margin on `<body>` specified by the user-agent stylesheet. What happens if you add `body { margin: 0 }` to the stylesheet?

https://github.com/Kozea/WeasyPrint/blob/0040f4799c9c3d02dd309af36ea44ad22fa15c20/weasyprint/css/html5_ua.css#L215

We got most of that stylesheet from desktop browsers, but since pages also have margins it might make sense to remove that one.

**Comment by damoser** [comment]
Wow.. that was a pretty fast answer. And it hit the mark too!

Thank you very much

**Comment by SimonSapin** [comment]
@liZe, what do you think of removing that margin in `html5_ua.css`? Is it likely to break existing documents?

**Comment by liZe** [comment]
@SimonSapin no problem, it's a good idea.
