### ISSUE TITLE
List markers should be positionned vertically like inline boxes.

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#287]
See example code and PDF

```
<html>
    <head>
        <style>
            body {
                line-height: 1.4em;
            }
        </style>
    </head>
    <body>
        <ol>
            <li> item 1
            <li> item 2
        </ol>
    </body>
</html>

```
[xx.pdf](https://github.com/Kozea/WeasyPrint/files/72756/xx.pdf)

**Comment by SimonSapin** [comment]
Relevant code is [`weasyprint/layout/markers.py`#L40-L43](https://github.com/Kozea/WeasyPrint/blob/c47ed0c8f6/weasyprint/layout/markers.py#L40-L43), which sets the vertical position of list markers so that their top is aligned with the top of the list item. This is undefined in CSS 2.1. [The relevant section of CSS Lists Level 3](https://drafts.csswg.org/css-lists/#positioning-markers) has a big red “not ready for implementation” warning, but what it says on this precise point sounds reasonable:

> The marker’s position in the ancestor list item’s block axis is calculated according to the [normal flow](http://www.w3.org/TR/CSS21/visuren.html#normal-flow).

Currently, the marker is attached to the list item in the box tree (`weasyprint/formatting_structure/boxes.py`) as a special case. It should be in `children` instead and treated mostly like an inline box so that `weasyprint/layout/inline.py` gives it the correct vertical position, accounting for `line-height`.

**Comment by liZe** [comment]
Related to #208.
