### ISSUE TITLE
Unwanted line-breaks in bold text

### ISSUE THREAD

**Issue by zopyx** [Kozea/WeasyPrint#288]
See the attached PDF/screenshot. There is an unwanted line break in the last row of table - likely to the fact that the text is marked as span.bold. 

![screenshot 2015-12-28 10 47 50](https://cloud.githubusercontent.com/assets/594239/12016867/7acf0b48-ad50-11e5-9058-50411424d3e1.png)

[xx.zip](https://github.com/Kozea/WeasyPrint/files/73085/xx.zip)

**Comment by zopyx** [comment]
Removing the first row let the last row render correctly...completely weird...the table width is set 100% ...why would one row less cause a different rendering behavior of subsequent rows?

**Comment by liZe** [comment]
I can't reproduce the bug with simple HTML samples like this one:

```html
<ol>
<li>
  sietua netunars etunare itunr itnause eitu netauie tnauiet rnauetn
  <strong>etasnui tenrau etnrsauet nrauet nrauet</strong> sitenaurset
  auiret nauietnrau et
```

Could you please provide the HTML and CSS used in your examples?

**Comment by zopyx** [comment]
See uploaded xx.zip file

**Comment by zopyx** [comment]
Where is a related (unit)test? How can you ensure that there will not be
any regressions? Do you even have a concept of quality control for
Weasyprint?

2016-01-01 19:37 GMT+01:00 Guillaume Ayoub <notifications@github.com>:

**Comment by liZe** [comment]
> Where is a related (unit)test? How can you ensure that there will not be
> any regressions? Do you even have a concept of quality control for
> Weasyprint?

Thank you for your gratitude.

WeasyPrint has tests, covering 94% of the code. These tests are launched for each commit with 6 different versions of Python, on [Travis](https://travis-ci.org/Kozea/WeasyPrint).

That's all I have to offer as a "concept of quality control".

Writing tests is sometimes hard and long, especially for text-related features of WeasyPrint. For example, I had no layout problem with your sample page, because I don't have Droid or Calibri installed. I had to change random characters to get your problem.

We can use a special font and rely on it to test some features. Actually, that's what we do: we use Ahem, a font specially crafted for tests. It helps, it makes writing some tests go from impossible to quite hard. But it's sometimes not enough: the test testing 'font-stretch' doesn't work on my computer because the default font used for tests has no condensed variant.

I could take the time to create a condensed font. I just don't want to. I prefer spending this time with my family.

And that's sometimes not only a problem of time. This particular bug was caused by a hack introduced because of hinting problems. The way how hinting is done depends on your OS, the versions of the font rendering libraries installed, and your personnal font rendering settings. On some systems, it may even depend on the screens plugged to the device, and on the orientation of these screens. So, if there's a *reliable* way to test hinting-related features for all the versions of the font-rendering libraries installed on these computers, I'd be happy to know it. I've already tried hard, please believe me. But I don't know it yet, making some non-regression tests just impossible to write for me.

If you're interested in WeasyPrint, including in its quality, I'll be really happy to spend some time fixing the bugs you report (even on January 1st), reading your pull requests, merging them and answering your questions. I'd love to see WeasyPrint become better. I'll spend time writing code and tests for free. But I won't be the person writing a test each time a bug is found.
