### ISSUE TITLE
pango-viewer in Debian

### ISSUE THREAD

**Issue by andrecastro0o** [Kozea/WeasyPrint#304]
I am having a hard time figuring out how can pango-viewer be installed in Debian.
As far as I can see, Debian only has in its repositories pago libraries and not pango-viewer, if I understand correctly is essential to know what fonts Weasyprint can use.

Can anyone please tip me on what would be the best way to have pango-viewer running on Debian Jessie?
Thanks!

**Comment by SimonSapin** [comment]
¯\_(ツ)_/¯

**Comment by andrecastro0o** [comment]
@SimonSapin  does that mean that I have to compile pango-viewer from source?

**Comment by SimonSapin** [comment]
It means that I don’t know.

For what it’s worth, I’ve only suggested pango-viewer in the past as a debugging tool in order to convince issue reporters that their issue is not a bug in WeasyPrint. (Other than the bug "someone someday should rewrite all of WeasyPrint’s text handling to use some lower-level API than `PangoLayout`.) I don’t think you actually need it, if you take my word or convince yourself by reading the source that WeasyPrint does nothing with the list of family names from `font-family` property (parsed [per CSS](https://drafts.csswg.org/css-fonts/#propdef-font-family)) than [join it with commas and call `pango_font_description_set_family`](https://github.com/Kozea/WeasyPrint/blob/98b78a1ad8e262b00dcb1c179e7e37aa65f2e0d5/weasyprint/text.py#L304-L307).

**Comment by andrecastro0o** [comment]
unhhg... i see, but how do we know what fonts are available for Weasyprint to use? E.g. are the fonts its ~/.fonts available to it?
I am sorry for the naive questions. I am quite a newbie. For month I have been struggling to find good html to print solution and finding Weasyprint was quite something! now in the middle of project trying to produce a book from a wiki and needing to get most issues working :P will let you know when it becomes completed.

**Comment by SimonSapin** [comment]
> unhhg... i see, but how do we know what fonts are available for Weasyprint to use? E.g. are the fonts its ~/.fonts available to it?

Honestly I don’t know, other than that Pango uses fontconfig on Linux to find fonts, and dealing with fontconfig’s configuration. If you want to list all available fonts, there may be a fontconfig command doing that. If all you care about is using a particular `.ttf` file in WeasyPrint, copying it to `~/.fonts` is probably a good start.

@liZe may have more suggestions.

**Comment by liZe** [comment]
Once again, our favourite search engine will help us to find our way in the maze:
- WeasyPrint uses Pango to render characters,
- [Pango uses fontconfig](http://www.pango.org/),
- [Fontconfig is a library for configuring and customizing font access](https://freedesktop.org/wiki/Software/fontconfig/), that's the library used to list and access fonts!

So, to know the fonts available for WeasyPrint, we need to find the fonts available for fontconfig. Quite easy, [the Wikipedia page for fontconfig](https://en.wikipedia.org/wiki/Fontconfig) gives us a wonderful list of command-line utilities, with the very useful `fc-list` and `fc-match`.

**Comment by andrecastro0o** [comment]
yes. sounds pretty logic. I'll give it a try.
btw @liZe answer sounds like a good addition to the weasyprint documentation for the section fonts. 
thanks!

**Comment by liZe** [comment]
> btw @liZe answer sounds like a good addition to the weasyprint documentation for the section fonts. 
> thanks!

Good idea.
