### ISSUE TITLE
WeasyPrint pdf not displaying characters just display a box per characters on Linux Centos 

### ISSUE THREAD

**Issue by Hollows76** [Kozea/WeasyPrint#314]
Initially WeasyPrint failed to install on Linux Centos but this was resolved by installing python-devel and libffi-devel via the following command:

`sudo yum install python-devel libffi-devel`

Now WeasyPrint pdf will not display characters in the output PDF from simple html input.

The PDF written  just displays a box per character.

I even tried this with a very simple html input like <p>Test</p> and I still get the same boxes and no characters.

Any thoughts?

Chris

**Comment by liZe** [comment]
That's probably because of the default fonts defined on your system. You can try to find the fonts embedded in your output PDF (PDF readers usually provide this feature), I bet it's a [fallback font](https://en.wikipedia.org/wiki/Fallback_font).

The default font defined by WeasyPrint for documents is "serif". This string is then given to Pango and then given to Fontconfig. Fontconfig tries to find the best font corresponding to this name. You can find the font given by Fontconfig for "serif" with `fc-match serif`, and if it's a fallback font, you have to
- configure the fonts used by your system to make "serif" match a real font, or
- define the font you want to use in CSS.

If "serif" gives a good font and you can't solve your problem by defining a font in CSS, then it's a bug elsewhere :fearful:.

**Comment by Hollows76** [comment]
Hi,

Thanks so much for the help on this.

I can confirm the fonts were not installed on the linux vm I was using.

Once installed the characters were visible.

Now I have the problem of fitting the html content to the page.

Thanks
Chris

**Comment by liZe** [comment]
> Now I have the problem of fitting the html content to the page.

That's another problem :). If you need some help about CSS, spending some time reading some of the the CSS specs is a good start, but you'll also find good advices on [IRC](http://weasyprint.org/community/)!

**Comment by apardes** [comment]
@liZe I am running into this same issue on macOS. I've tried playing with the font through custom CSS but still seeing empty boxes throughout the document. Any thoughts? Thanks!

**Comment by liZe** [comment]
@apardes:
- You can try to remove all the `@font-face` and `font-family` rules, install fonts **system-wide** and see if it works.
- Logs can help.
- Using `fc-match` to find which face is used is also a good idea.
- You'll find the list of integrated fonts in your generated PDF.
- Use the 0.41 version!

**Comment by apardes** [comment]
@liZe Thanks for the quick response!

- I am using 0.41 (this started happening after I upgraded from 0.30 to 0.41

- Since the upgrade I am no longer seeing any output from WeasyPrint (I am using WeasyPrint inside Django but I previously was seeing logging in the Django server logs).

- I have tried to see which fonts are in the generated PDF but the output of `strings /path/to/document.pdf | grep -i FontName` is empty. I'm not sure what this indicates.

**Comment by liZe** [comment]
> I am using 0.41 (this started happening after I upgraded from 0.30 to 0.41

Good to know.

> Since the upgrade I am no longer seeing any output from WeasyPrint (I am using WeasyPrint inside Django but I previously was seeing logging in the Django server logs).

Since 0.37, logging is not configured when WeasyPrint is used as a library, according to Python good practices (see #412).  If you want them back, you should add a log handler, as it's done in [`__main__.py`](https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/__main__.py#L168) for example.

> I have tried to see which fonts are in the generated PDF but the output of strings /path/to/document.pdf | grep -i FontName is empty. I'm not sure what this indicates.

It generally means that you only have [standard fonts](https://en.wikipedia.org/wiki/Portable_Document_Format#Standard_Type_1_Fonts_.28Standard_14_Fonts.29) included in your PDF. That's then the responsability of the PDF reader to render them correctly. Could you please provide one of your broken PDF files?

**Comment by liZe** [comment]
> I am running into this same issue on macOS.

Oh, macOS. You really should use `fc-match` (provided by fontconfig that's installed with brew) to find which fonts are available for WeasyPrint.

**Comment by HenryMehta** [comment]
I've got this same issue where it works on my local PC (Ubunutu) but not ElasticBeanstalk instance (also Ubuntu, but server), where I get the fallback font.  Font is in same relative place on both instances.  Any ideas about how to correct?

**Comment by liZe** [comment]
> I've got this same issue where it works on my local PC (Ubunutu) but not ElasticBeanstalk instance (also Ubuntu, but server), where I get the fallback font. Font is in same relative place on both instances. Any ideas about how to correct?

Fonts have to be installed and available for the user launching WeasyPrint. You can launch `fc-list` (with the user launching WeasyPrint) to find which fonts are available on your server.

If you use a `@font-face` rule, you may have errors in your logs.

**Comment by HenryMehta** [comment]
The actual problem here is the WeazyPrint requires Pango > 1.38 but AWS Elastic Beanstalk only installs 1.28 and I cannot find an installation procedure to upgrade it
