### ISSUE TITLE
Cutting lines is broken in page margin boxes

### ISSUE THREAD

**Issue by Kodiologist** [Kozea/WeasyPrint#325]
With WeasyPrint 0.28, rendering the valid HTML5 document

````html
<!DOCTYPE html>
<html><head><title>foo</title><meta charset="utf-8">

<style type="text/css">
@page
   {margin-top: 1in;
    margin-bottom: 1in;
    margin-left: .9in;
    margin-right: .9in;
    size: 6in 9in;
    @top-center
       {content: "this parrot is dead";}}
</style>

</head><body><p>hello world</p></body></html>
````

makes a PDF that looks like this:

![Screenshot](http://i.imgur.com/NYS5Cu4.png)

Note the extra line break after the first word of the header. Whatever the header text, the line break seems to still occur after the first word. Different margin and page sizes can make the line break disappear, but it's not obvious to me what the logic is.

**Comment by SimonSapin** [comment]
I don’t remember the details of the layout algorithm, but my guess is that the contents of `@top-center` is measured to determine its width, and then layout happens with that available width. Somehow, these two phases get slightly different results and the width is just too small for the entire content. I don’t understand why the break is after the first word rather than before the last, though.

Try adding `width: 100%` to `@top-center`?

**Comment by Kodiologist** [comment]
> Try adding `width: 100%` to `@top-center`?

Seems to work! Thanks.

**Comment by liZe** [comment]
I can reproduce the bug with different fonts families and sizes, so it's probably not a shrink-to-fit problem as the "famous" one explained in 3a620db (and that's good news).

The word alone on the first line is really strange, it's probably a dirty bug only happening to page margin boxes.

**Comment by liZe** [comment]
Unfortunately, that's a shrink-to-fit problem, exactly the case given in 3a620db. I can now reproduce it with Ahem, I hope you can too:
`<p style="float: left; margin-left: 0.9in; font-size: 0.6em; font-family: ahem">this parrot is dead`

The reason why it's cut after the first word or before the last word is just an implementation detail, it's actually the same bug. I'll fix it and test it.
