### ISSUE TITLE
media_type parameter not working with Bootstrap

### ISSUE THREAD

**Issue by andrius-senulis** [Kozea/WeasyPrint#340]
Hello,

I'm trying to generate a PDF file using CSS media type "screen":

```python
HTML(html_filepath, media_type="screen")
```

... but the WeasyPrint doesn't seem to respect it - I still get Bootstrap's styling for printing.

What I want to achieve is the same styling in the PDF as it is on the screen. The way around that I found is to download the customized Bootstrap distribution without print media styles. Then I can generate the PDF file with the default `media_type='print'` and I get the styling as in the screen. However, I don't actually want to remove that from Bootstrap.

Am I using WeasyPrint wrong in this case or it really doesn't work?

Cheers,
Andrius

**Comment by liZe** [comment]
Hello,

I've tried:

```python
HTML('http://getbootstrap.com/getting-started/', media_type='screen').write_pdf('/tmp/bootstrap.pdf')
```

It works, I get the same style as on my screen, different from `media_type='print'`.

(It doesn't work on http://getbootstrap.com/ because the CSS URLs have leading `../` that WP doesn't like. But it's probably not related to your bug report.)

Do you have a small example of your problem that we can reproduce?

**Comment by liZe** [comment]
@andrius-senulis Feel free to reopen if there's something new about this.

**Comment by andrius-senulis** [comment]
Thank you for taking a look into it. Probably there is no bug and I was just doing something wrong. Anyway, I took a different approach that didn't require the `media_type`.
