### ISSUE TITLE
Page margins are broken with "body { overflow: auto }" style

### ISSUE THREAD

**Issue by ksaylor** [Kozea/WeasyPrint#35]
I have a CSS file that defines headers and footers using @top-center, @bottom-center, and @top-right. When I use weasyprint the resulting PDF does not have the headers and footers. Here's a snippet from the CSS file:

```
@page
{
    size: letter;
    margin: 27mm 16mm 27mm 16mm;
    counter-increment: page;
    @bottom-center
    {
        content: counter(page);
        white-space: pre;
        color: grey;
        }
    @top-center
    {
        content: 'Strategic Planning Concept';
        color: grey;
        border-bottom: solid 1px grey;
    }
    @top-left
    {
        content: ' \a \a \a ';
        white-space: pre;
        color: grey;
        border-bottom: solid 1px grey;
    }
    @top-right
    {
        content: ' \a \a \a February 6, 2013';
        white-space: pre;
        color: grey;
        border-bottom: solid 1px grey;
    }
}
```

**Comment by dxiao2003** [comment]
For me it didn't work while I had "overflow: auto" on the <body> element. Removing that made the text box appear.

**Comment by liZe** [comment]
> For me it didn't work while I had "overflow: auto" on the <body> element. Removing that made the text box appear.

Great! `body { overflow: auto }` breaks the margins for some reason. Minimal case:

```html
<style>
  @page { @top-left { content: 'test' } }
  body { overflow: auto }
</style>
body
```

**Comment by Tontyna** [comment]
This wasn't a bug. This was intentional :smirk: 

WeasyPrint treats all `overflow` values but `visible` like **`hidden`**.
The [spec tells us](https://www.w3.org/TR/css-overflow-3/#overflow-propagation) that 

> UAs must apply the overflow-* values set on the root element to the viewport.

The *viewport* in our case is the **PageBox** (= all pages) and thus the PageBox is clipped, cutting off every single piece of content outside the page box:

https://github.com/Kozea/WeasyPrint/blob/27c600f18f025d8a7bffb4e5e0f861014881198e/weasyprint/draw.py#L226-L231

Obviously, the actual intent of this *viewport-overflow* is to clip the body, resp. the document content. It should not devour the `@page` margin content.
But when we draw the MarginBoxes (being children of the PageBox) **after** the PageBox has clipped the context to the inner area of the page (`rounded_padding_box`)...

**Comment by liZe** [comment]
> This wasn't a bug. This was intentional

For sure :wink:.

> Obviously, the actual intent of this _viewport-overflow_ is to clip the body, resp. the document content. It should not devour the `@page` margin content.

We have other similar workarounds to draw and clip the viewport background. The special cases needed to draw the viewport (and draw the root element a bit differently) are a mess, just like the mess created by the table wrappers. We have to live with that, I think…
