### ISSUE TITLE
Rendering problem of border-radius in Adobe Reader 

### ISSUE THREAD

**Issue by inuyasha2012** [Kozea/WeasyPrint#360]
when I use border-radius, I find a problem

in browser, like firefox, IE, it rendered right

but in adobe reader, it rendered some strange thin lines

i don't kow why, the pic is below

![p](https://cloud.githubusercontent.com/assets/11623232/18738013/235135d2-80ca-11e6-8d58-c4f6b6fc776c.PNG)

**Comment by liZe** [comment]
Thanks for reporting!

I've tried to reproduce, and some readers seem to have this problem:
- Adobe Reader
- ImageMagick
- Ghostscript

Some other don't:
- Evince
- Foxit
- Firefox
- Chrome
- Edge

As this problem is not visible in all readers and not visible in PNGs generated by Cairo, I suppose that there's a bug in either these readers and/or in Cairo, and a "strange" use of the drawing primitives of Cairo in WeasyPrint. We can try to find and change this "strange" use to fix the problem.
