### ISSUE TITLE
Ordered list (<ol>) start attribute not applied

### ISSUE THREAD

**Issue by aih** [Kozea/WeasyPrint#398]
Using weasyprint 0.32, I'm converting a source with this form:

```
<ol class="arabic" start="3">
    <li>
        <p>The third way to accomplish this is...</p>
    </li>
</ol>
```

And it is being rendered:

```
1. The third way to accomplish this is...
```

The ['start' attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#Using_the_start_attribute) is not being applied.

**Comment by liZe** [comment]
It should be managed by https://github.com/Kozea/WeasyPrint/blob/master/weasyprint/css/__init__.py#L445, I have to check why it's not working (and add a test).

**Comment by liZe** [comment]
It's actually working, but:
- you need to enable the "presentational hints" options (using the `-p` option from the CLI, or setting the `presentational_hints` option of the `render*` methods from the API),
- there's a bug in 0.32 and 0.33 (fixed by 12c297d) that's preventing the presentational hints to be honored when you render PDFs. That's a dirty bug, I'm sorry :disappointed:.

So, you can see that it works right now with 0.32 using `weasyprint -p file.html file.png`. Unfortunately, if you want to generate PDFs, you'll have to wait for 0.34 or backport 12c297d…

**Comment by aih** [comment]
Thank you for your fast work on this!  It may be worth adding a note to the 'presentational hints' section of the documentation-- I did not know what presentational attributes were and didn't think it would be relevant in this case.  Something like:

> Presentational hints include a wide array of attributes that direct styling in html, including font `@color` names and `@size` attribute, list attributes (`@type` and `@start`), various table alignment attributes, and others. If the pdf is missing some of the features you expect from the html, try running weasyprint with  the `-p` option.

**Comment by aih** [comment]
I cloned the repo with  12c297d, installed locally, and can confirm it works. Thanks again!

**Comment by liZe** [comment]
> It may be worth adding a note to the 'presentational hints' section of the documentation.

Done, thank you for the report!
