### ISSUE TITLE
Cannot load library pangocairo-1.0 when trying to get WeasyPrint working on AWS Lambda

### ISSUE THREAD

**Issue by NoneMan** [Kozea/WeasyPrint#401]
I like WeasyPrint, and I try to get it working on AWS Lambda. To meet the dependencies, I copied **libpango-1.0.so** and **libpangocairo-1.0.so** from Amazon Linux environment, and zipped them with my scirpts. But I got an error message when deploying:
```python
module initialization error: cannot load library pangocairo-1.0: pangocairo-1.0: cannot open shared object file: No such file or directory
```
And I find this:
```python
#lib/weasyprint/text.py
pango = dlopen(ffi, 'pango-1.0', 'libpango-1.0-0', 'libpango-1.0.so',
               'libpango-1.0.dylib')
pangocairo = dlopen(ffi, 'pangocairo-1.0', 'libpangocairo-1.0-0',
                    'libpangocairo-1.0.so', 'libpangocairo-1.0.dylib')
```

- Why it can find **libpango-1.0.so** but cannot find **libpangocairo-1.0.so** ? 
- Is there a way to use WeasyPrint on AWS Lambda ?

**Comment by liZe** [comment]
Thanks for reporting!

> Why it can find libpango-1.0.so but cannot find libpangocairo-1.0.so ?

I really don't know how AWS works, I'm afraid I won't be really helpful :cry:. But a reason could be that:
- pango is already installed on your system while pangocairo is not,
- the name used to find pango (let's say it's `libpango-1.0-0`) is wrong for pangocairo (`libpangocairo-1.0-0` instead of something like `libpangocairo-1.0-1`), and other names that work on other systems don't work on AWS.

> Is there a way to use WeasyPrint on AWS Lambda ?

I don't know… @sparrovv is using EC2 in #223, maybe it could help to contact him.

**Comment by liZe** [comment]
@NoneMan can I close this issue?

**Comment by polakala** [comment]
I am seeing the same problem when creating aws lambda function for weasyprint. Did anyone resolved this?

**Comment by y0rd4nis** [comment]
I'm running WeasyPrint on AWS Lambda, the first run of my lambda function fails because it does not find some pango libs, I copied _libpango-1.0.so.0.2800.1_, _libpangocairo-1.0.so.0.2800.1_ and _libpangoft2-1.0.so.0.2800.1_ from Amazon Linux to the root of my lambda function package, I renamed the firt two .so to _pango-1.0_ and _pangocairo-1.0_ and now it is working.

I have had some problems with gif images that can be seen in #428 and my [comment](https://github.com/Kozea/WeasyPrint/issues/428#issuecomment-302597578).

**Comment by liZe** [comment]
Is anyone interested in adding an "AWS" section to the documentation?

**Comment by liZe** [comment]
Closing. See #428 about images and documentation.

**Comment by Prasengupta** [comment]
Guys below is the git link where you can download the weasy print library which works in AWS lambda.

https://github.com/Prasengupta/weasyprint_library_for_awslambda

Will try to upload the full documentation with an example in my git account.

Please raise a ticket if you face any issues.

**Comment by procal** [comment]
Thanks for the lambda support @Prasengupta @liZe . I've tried uploading my WEasyPrint lambda function with your package directory @Prasengupta but I'm still getting an import error.  I've also tried my own zip of packages from pip and imported the3 pango files directly from an Amazon Linux instance (they're still using pango-1.28.1 anyway) but without any success. 

Removed the WEasyPrint import and execution of the lambda function is fine.  I'm out of ideas now unfortunately.  Can you tell me how you pulled that zip file together originally?  Were they all pulled from Amazon Linux? 

Thanks so much,
Ed

**Comment by Prasengupta** [comment]
Hi @procal 

I think you're trying to execute in python3 which the published package is not supported. Please check with python27

I've searched those files in the amazon Linux instance by the command and able to get them. But I don't remember the path.
