### ISSUE TITLE
UserWarning: implicit cast

### ISSUE THREAD

**Issue by Saksow** [Kozea/WeasyPrint#408]
Hello, I have a warning every time I create a pdf file and I cannot locate what part I need to change to get rid of it. Can you please help ?

`/home/vagrant/.pyvenvs/mm35/lib/python3.5/site-packages/cairocffi/surfaces.py:447: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)`

**Comment by liZe** [comment]
Thanks for reporting!

These warnings are just warnings, don't panic! Moreover, they've been fixed in cairocffi's [62b40c0](https://github.com/Kozea/cairocffi/commit/62b40c0a9df4347754b2ead56297500c3f48e685) and [ddac5ae](https://github.com/Kozea/cairocffi/commit/ddac5aecdfce31029b8b81f3b93d261beac00baa). There's no release of cairocffi with these fixes yet, but you can use master if you really want to get rid of the warnings right now.

**Comment by Saksow** [comment]
Thanks!
