### ISSUE TITLE
Weasyprint logging is missconfigured

### ISSUE THREAD

**Issue by PamelaM** [Kozea/WeasyPrint#412]
From the python docs https://docs.python.org/2/howto/logging.html#library-config : 
```
Note It is strongly advised that you do not add any handlers other than NullHandler to your 
library’s loggers. This is because the configuration of handlers is the prerogative of the 
application developer who uses your library. The application developer knows their target 
audience and what handlers are most appropriate for their application: if you add handlers 
‘under the hood’, you might well interfere with their ability to carry out unit tests and 
deliver logs which suit their requirements.
```

The default handler should be the NullHandler.

**Comment by liZe** [comment]
I agree. Silent logs have been asked before (at least #300 and #312) and that should be the default when WeasyPrint used as a library. We should log to stderr only when it's the "normal" way to handle logs, i.e. when WeasyPrint is launched from the CLI.

**Comment by PamelaM** [comment]
For those hitting this problem before it's fixed, here's how I've disabled the weasyprint logging handler - the logger needs to be set up before the first import of weasyprint

```
import logging

logger = logging.getLogger("weasyprint")
if not logger.handlers:
    logger.addHandler(logging.NullHandler())

from weasyprint import HTML
```

**Comment by erichonkanen** [comment]
possibly related, I think all of the `WARNING` messages are coming from this package?

![image](https://cloud.githubusercontent.com/assets/230757/24126902/f8e7956a-0d8d-11e7-895f-3ee79d24ccb3.png)

**Comment by alacret** [comment]
This hack doesn't work for Django applications. Neither in the settings.py nor before the import of the library

**Comment by oleh-smediuk** [comment]
For those who use Django internal LOGGING dict-like config:

```python
LOGGING = {
    'version': 1,
    ...
    'handlers': {
        ...
        'null_handler': {
            'level': 'ERROR',
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        ...
        'weasyprint': {
            'level': 'ERROR',
            'handlers': ['null_handler'],
        },
    }
}
```

**Comment by conformist-mw** [comment]
For those who use Django internal LOGGING dict-like config:

```python
LOGGING = {
    'version': 1,
    ...
    'handlers': {
        ...
        'null_handler': {
            'level': 'ERROR',
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        ...
        'weasyprint': {
            'level': 'ERROR',
            'handlers': ['null_handler'],
        },
    }
}
```

**Comment by florianm** [comment]
I was still getting log messages such as `__init__ glyf pruned`.
The following logging config silences them:
```
LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s"
        },
        "terse": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s"
        },
    },
    "handlers": {
        "null_handler": {
            "level": "ERROR",
            "class": "logging.NullHandler",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "terse",
        },
    },
    "loggers": {
       "root": {
           "level": "INFO",
           "handlers": ["console"]
        },
        "fontTools.subset": {
            "level": "ERROR",
            "handlers": ["null_handler"],
        },
    },
}
```

Salient points:
* The offensively chatty logger's name is `fontTools.subset`, not `weasyprint`.
* I found the offending logger's name by including `%(name)s` in the formatter ([formatter docs](https://docs.python.org/3/library/logging.html#logrecord-attributes)). The default `%(module)s` gave me only the filename `__init__` which was not too useful.

**Comment by mgarbade** [comment]
@florianm: I assume  your suggested solution is to patch the weasyprint module itself? Or can I also fix the chatty fontTools logger before / after importing weasyprint?

**Comment by mgarbade** [comment]
Update: I tried adding this after the logging import:

```
import logging
import logging.config

from weasyprint import HTML

# Setup logging configuration
LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "terse": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s"
        },
    },
    "handlers": {
        "null_handler": {
            "level": "ERROR",
            "class": "logging.NullHandler",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "terse",
        },
    },
    "loggers": {
        "fontTools.subset": {
            "level": "ERROR",
            "handlers": ["null_handler"],
        },
    }
}

logging.config.dictConfig(LOGGING_CONFIG)
```

However, the output is still too chatty (though less chatty than before): 

2025-03-03 09:34:11,604 WARNING __init__.py Ignored min-height: 100vh at 18:13, invalid value.
2025-03-03 09:34:11,693 DEBUG ttFont.py Reading 'maxp' table from disk
2025-03-03 09:34:11,693 DEBUG ttFont.py Decompiling 'maxp' table
2025-03-03 09:34:11,694 DEBUG ttFont.py Reading 'cmap' table from disk
2025-03-03 09:34:11,694 DEBUG ttFont.py Decompiling 'cmap' table
2025-03-03 09:34:11,694 DEBUG ttFont.py Reading 'post' table from disk
2025-03-03 09:34:11,694 DEBUG ttFont.py Decompiling 'post' table
2025-03-03 09:34:11,696 DEBUG ttFont.py Reading 'glyf' table from disk
2025-03-03 09:34:11,696 DEBUG ttFont.py Decompiling 'glyf' table
2025-03-03 09:34:11,696 DEBUG ttFont.py Reading 'loca' table from disk
2025-03-03 09:34:11,696 DEBUG ttFont.py Decompiling 'loca' table
2025-03-03 09:34:11,696 DEBUG ttFont.py Reading 'head' table from disk
2025-03-03 09:34:11,696 DEBUG ttFont.py Decompiling 'head' table
2025-03-03 09:34:11,697 DEBUG ttFont.py Reading 'hmtx' table from disk
2025-03-03 09:34:11,697 DEBUG ttFont.py Decompiling 'hmtx' table
2025-03-03 09:34:11,697 DEBUG ttFont.py Reading 'hhea' table from disk
2025-03-03 09:34:11,698 DEBUG ttFont.py Decompiling 'hhea' table
2025-03-03 09:34:11,698 DEBUG ttFont.py Reading 'GDEF' table from disk
2025-03-03 09:34:11,698 DEBUG ttFont.py Decompiling 'GDEF' table
2025-03-03 09:34:11,699 DEBUG ttFont.py Reading 'OS/2' table from disk
2025-03-03 09:34:11,699 DEBUG ttFont.py Decompiling 'OS/2' table
2025-03-03 09:34:11,700 DEBUG ttFont.py Reading 'name' table from disk
2025-03-03 09:34:11,700 DEBUG ttFont.py Decompiling 'name' table
2025-03-03 09:34:11,700 DEBUG ttFont.py Reading 'gasp' table from disk
2025-03-03 09:34:11,700 DEBUG ttFont.py Decompiling 'gasp' table
2025-03-03 09:34:11,700 DEBUG ttFont.py Reading 'STAT' table from disk
2025-03-03 09:34:11,700 DEBUG ttFont.py Decompiling 'STAT' table
2025-03-03 09:34:11,706 DEBUG ttFont.py Reading 'maxp' table from disk
2025-03-03 09:34:11,706 DEBUG ttFont.py Decompiling 'maxp' table
2025-03-03 09:34:11,707 DEBUG ttFont.py Reading 'cmap' table from disk
2025-03-03 09:34:11,707 DEBUG ttFont.py Decompiling 'cmap' table

**Comment by jedrka** [comment]
Ended up with monkey-patching `weasyprint.pdf.fonts.capture_logs` method with some dummy function to prevent weasyprint from misconfiguring fonttools logger. The thing weasyprint does to loggers feels almost illegal 😂

**Comment by liZe** [comment]
> Ended up with monkey-patching `weasyprint.pdf.fonts.capture_logs` method with some dummy function to prevent weasyprint from misconfiguring fonttools logger. The thing weasyprint does to loggers feels almost illegal 😂

@jedrka What’s your problem, and what would you propose to do in WeasyPrint to fix it?

**Comment by florianm** [comment]
> [@florianm](https://github.com/florianm): I assume your suggested solution is to patch the weasyprint module itself? Or can I also fix the chatty fontTools logger before / after importing weasyprint?

My solution as shown in my code example is entirely confined to my own logger settings and does not modify weasyprint modules in any way. Hope this helps!

**Comment by jedrka** [comment]
> > Ended up with monkey-patching `weasyprint.pdf.fonts.capture_logs` method with some dummy function to prevent weasyprint from misconfiguring fonttools logger. The thing weasyprint does to loggers feels almost illegal 😂
> 
> [@jedrka](https://github.com/jedrka) What’s your problem, and what would you propose to do in WeasyPrint to fix it?

@liZe 
My problem is that I need to use weasyprint in web application, but I can't let it spam with log outputs. At the same time I would like to keep all loggers on level not higher than `WARNING` and do not want to make some some crazy logger setups because _the next guy_ ™ will have to make research in order to understand that. 

weasyprint breaks contract how to use loggers in python - it changes logger configuration (changes levels, modifies handlers) on its own, it is usually reserved for "final" application to make that. Implemented CLI (in `__main__.py` file), which is kind of "final" application, is the only valid place to make such changes to logger configuration. When using weasyprint as a library there should be no call to change level of any logger or modifying its handlers. 

Also (a minor one), there is a convention that every module gets its own logger from logging.getLogger(`__name__`). That makes every log record contain module path where log was produced and that makes finding corresponding code easier. If one would like to make displayed log lines shorter, then it is a valid use case for setting formatter or implementing custom handler, but all that should be done only in a "final" application level (so in this case the implementation of CLI). 

My proposition is:
- Remove `capture_logs` function completely, instead just set `fontTools` logger level to `WARNING` in CLI tool (`__main__.py`).  I think it should give similar results in CLI because (as far I understand that) `capture_logs` just captures log records from `fontTools` with level >= WARNING which are then prefixed with "`fontTools warning when subsetting ...`" (does not sound critical to me) and are resent to logger with level `WARNING`.
- Remove adding `NullHandler` in weasyprint/logger.py:20. If that was necessary for CLI, then move it to `__main__.py`. 

This will allow users of your library decide whats best for them on their own.

I hope that does not sound too harsh, this is a great library I am deeply grateful for being able to use it.

**Comment by liZe** [comment]
> This will allow users of your library decide whats best for them on their own.
> 
> I hope that does not sound too harsh, this is a great library I am deeply grateful for being able to use it.

No problem.

Could you please open a PR so that we can discuss this topic over there?

**Comment by csala** [comment]
100% agreeing with @jedrka about the current WeasyPrint approach to logging being completely wrong.

My application, with logs set to WARNING, is now being spammed with DEBUG level log statements from fontTools because the `capture_logs` wrapper completely messes up the logging configuration.

Has the PR mentioned above been open? I'm happy to give it a shot otherwise.

In the meantime, for anyone interested, capture_logs can be monkey patched to become a no-op:

```python
import contextlib

from weasyprint.pdf import fonts   # Or any other rogue module

@contextlib.contextmanager
def noop(*_, **__):
    yield []

fonts.capture_logs = noop
```

**Comment by liZe** [comment]
> Has the PR mentioned above been open?

No, you can open one so that we can discuss about.
