### ISSUE TITLE
Weasyprint does not create all the pages

### ISSUE THREAD

**Issue by jloyzaga** [Kozea/WeasyPrint#414]
I thought that I would get about 11 pages yet I only got 4. Looking at the HTML it looks like quite a lot of line items were ignored - files are attached - can you tell me why?

I need to make sure all the data comes out

Thanks
Joe
[Res18-23.txt](https://github.com/Kozea/WeasyPrint/files/722652/Res18-23.txt)

**Comment by liZe** [comment]
Thank you for reporting this issue.

This bug is caused by #96, the "steps" listed in your document are in one big `td` that is not split into multiple pages. Fixing #96 would solve your problem, but it is unfortunately really hard to fix.

Not related to this bug but maybe useful for you: there's now a `--presentational-hints` option.
