### ISSUE TITLE
No such file or directory when building PDF

### ISSUE THREAD

**Issue by cchimi** [Kozea/WeasyPrint#420]
I'm trying to run Weasyprint from the command line but I'm not able to generate a PDF. When I try I get this Traceback:

    $ weasyprint my-file.html /builds/my-file-wp.pdf
    Traceback (most recent call last):
      File "/usr/local/bin/weasyprint", line 9, in <module>
        load_entry_point('WeasyPrint==0.34', 'console_scripts', 'weasyprint')()
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/__main__.py", line 164, in main
        getattr(html, 'write_' + format_)(output, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/__init__.py", line 181, in write_pdf
        target, zoom, attachments)
      File "/usr/local/lib/python2.7/dist-packages/weasyprint/document.py", line 515, in write_pdf
        with open(target, 'wb') as fd:
    IOError: [Errno 2] No such file or directory: '/builds/my-file-wp.pdf'

I've also tried the simple test from the Tutorial:
`weasyprint http://weasyprint.org /tmp/weasyprint-website.pdf`

In that case I get the expected font/CSS warnings, no Traceback, but no PDF. If I expand the output location so that it is absolute, I do get the same Traceback as above. I'm running Weasyprint on Ubuntu 16.04.

**Comment by liZe** [comment]
You're maybe a bit lost with folders on Linux :smile:.

`/builds/my-file-wp.pdf` is an absolute path, and you probably don't have a folder called `/builds/`, that's why you get the error. When you try the test from the tutorial, the generated PDF is in the `/tmp/` folder, the folder used for temporary files on Linux. You can go in this folder with your file manager by hitting `Ctrl+L` and typing `/tmp/` in the folder bar. You can also open it by launching `evince /tmp/weasyprint-website.pdf` in the terminal.

If you want to generate the PDF in a folder called `builds` in the same folder of `my-file.html`, you can launch `weasyprint my-file.html builds/my-file-wp.pdf` or `weasyprint my-file.html ./builds/my-file-wp.pdf`.
