### ISSUE TITLE
Get rid of lxml dependency

### ISSUE THREAD

**Issue by jbremer** [Kozea/WeasyPrint#440]
If possible, I think it'd be great to get rid of the dependency on `lxml`. I've found it to be quite annoying to install; on Linux it takes a minute to compile, on Mac OS X the first time it'll take like an hour to compile (due to having to `brew install gcc` as well), and on Windows one by default doesn't have a compiler at hand - leaving you to install a pre-compiled version of `lxml`, but apparently not every version has pre-compiled DLLs in place..
By replacing `lxml` by stdlib `xml` some of this pain (imo) goes away. Of course will need some simple unittests to ensure compatibility remains, but other than that.. :)

**Comment by liZe** [comment]
> By replacing lxml by stdlib xml some of this pain (imo) goes away. Of course will need some simple unittests to ensure compatibility remains, but other than that.. :)

Unfortunately, that's not true. WeasyPrint uses lxml because it supports XPath for CSS selectors coming from cssselect, and there's nothing in the standard library that supports XPath correctly.

lxml has also [lots of wheels](https://pypi.python.org/pypi/lxml/) that should avoid compilation on many platforms.

But yes, avoiding lxml is a good idea. @SimonSapin had started [cssselect2](https://github.com/SimonSapin/cssselect2) to make CSS selectors work without XPath, but it's dead today.

**Comment by jbremer** [comment]
Yes, I see, that does complicate things :( I guess usage of `weasyprint` will have to remain an optional feature for me right now then. Thanks for the feedback!

**Comment by SimonSapin** [comment]
`pip`’s integration/usage of wheel files has made a lot of progress if the last few years. These days `pip install lxml` on Linux uses a pre-compiled wheel that installs quickly.

**Comment by faststare** [comment]
use optional html5lib instead. because lxml dependency will limit your user base.

**Comment by SimonSapin** [comment]
@faststare, see @liZe’s message above:

> WeasyPrint uses lxml because it supports XPath for CSS selectors coming from cssselect

So moving away from lxml first requires moving away from XPath. Which we want to do anyway, but it’ll take more work than "just switch to html5lib".
