### ISSUE TITLE
write_pdf "kills" the process

### ISSUE THREAD

**Issue by jseiller** [Kozea/WeasyPrint#448]
Hi, here is the code:
`from weasyprint import HTML`
`o = HTML('http://weasyprint.org/')`
`print('hello')`
`o.write_pdf('weasyprint-website.pdf')`
`print('goodbye')` 

The output is the following:
`WARNING: There are known rendering problems with Cairo <= 1.14.0`
`WARNING: @font-face is currently not supported on Windows`
`hello`
`WARNING: Ignored transition: color 0.25s at 14:18, unknown property.`
`WARNING: Ignored text-shadow: 1px 1px 1px #111 at 18:125, unknown property.`
`                                                                             `
`C:\some\path>`
And there is no file weasyprint-website.pdf in C:\some\path.
For some reason, entering the function write_pdf (we can see it actually enters the fonction with the 3rd and 4th warnings) just stop the program at some point... without any additional explanation.
For information, I believe WeasyPrint has been installed properly (on Windows 10) following all the instructions.
Anyone has an idea?

**Comment by liZe** [comment]
Do you get an error like #400?

**Comment by jseiller** [comment]
Nope, no error displayed anywhere. Just exactly as in my previous post :( 

Thanks for your quick answer

**Comment by liZe** [comment]
Some random thoughts:
- The 2 warnings after "hello" are the only ones I get, we can assume that it stops after parsing the CSS.
- The warning about Cairo is here mainly because Cairo < 1.14 generates broken text, not because it leads to crashes.
- It's strange to have no error at all.

To find what's going on, you can try to reproduce the bug with a simple local HTML file (just to be sure that it's not related to network). After that, you can try to launch WeasyPrint from the Python CLI with something like `python -m weasyprint test.html test.pdf`, and see if you get a trace. Otherwise, you can try to use a debugger, or add random `print`s to see where it stops.

**Comment by jseiller** [comment]
All tries have led to the same issue, with no trace or error message. 
I have no idea where this could come from.

**Comment by jseiller** [comment]
I am trying a full clean re-installation of weasyprint - keep you up to date

**Comment by jseiller** [comment]
OK - I am on Windows 10 64 bit, I managed to make it work after 2 re-installation using the 32 bits GTK and lxml.

**Comment by liZe** [comment]
Did the crash happen with 64 bit GTK?

**Comment by jseiller** [comment]
It did crash with GTK 64 bit yes and seems not to with the 32 bit version.

**Comment by liZe** [comment]
@jseiller Did you try with recent 64 bit versions of GTK?

**Comment by liZe** [comment]
Feel free to reopen this issue if you have more information.
