### ISSUE TITLE
Table rows not sized evenly when rowspan is used

### ISSUE THREAD

**Issue by impala2** [Kozea/WeasyPrint#459]
Minimal example:

    <table>
        <tr>
            <td style="background: pink;">A</td>
            <td rowspan="3" style="background: blue;">X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X<br>X</td>
        </tr>
        <tr>
            <td style="background: green;">B</td>
        </tr>
        <tr>
            <td style="background: purple;">C</td>
        </tr>
    </table>

Expected result (browser):
![1](https://cloud.githubusercontent.com/assets/6775354/25420913/60c87e6e-2a95-11e7-9cbe-091be31b217f.png)

Actual result:
![2](https://cloud.githubusercontent.com/assets/6775354/25420918/67a20de0-2a95-11e7-80d1-8e2abae7e84b.png)

Python 2.7
Weasyprint 0.36

**Comment by liZe** [comment]
The way rows are sized when rowspan is used is not specified in the CSS specs. I get different results in different browsers:
- Chrome and Firefox give the "expected" result,
- Epiphany and (probably) Safari give the same result as WeasyPrint.

You want to give the extra height evenly, but that's not even what Chrome and Firefox do: they give the extra height to each row relatively to their heights. And I think that we can easily find examples where the current implementation is "better" than the "expected" result.

I don't like to change behaviours that are not specified, as explained in the [mandatory xkcd](https://xkcd.com/1172/), but if you have a good reason why your expected behaviour is **better**™, we can let this issue open as an open feature request :smile:.

**Comment by impala2** [comment]
I'm fine with that not being the default, but I was not able to explicitly force it to have the same behavior either.

**Comment by liZe** [comment]
> I'm fine with that not being the default, but I was not able to explicitly force it to have the same behavior either.

It's just the same for the other browsers :wink:!

**Comment by liZe** [comment]
Having the same rendering as at least one other browser is really good news for unspecified behaviors :smile:. Let’s close!

**Comment by mclemme** [comment]
Stumbled on this as I was having the exact same issue with rowspan and I found a workaround to make weasyprint version 66.0 split the extra height out evenly between the cells.

By adding `line-height: 0` to the content of the `<td>` elements that need rowspan it seems to split the height evenly. For images within the `<td>` elements I had to use CSS `background-image` instead of `<img>` elements.

I don't know if this has odd side effects in use cases that don't match mine (single words/images in table cells), but thought it could be useful for others that end up here :)
