### ISSUE TITLE
Assertion failed: ! scaled_font->cache_frozen, file cairo-scaled-font.c, line 1166

### ISSUE THREAD

**Issue by hackedbellini** [Kozea/WeasyPrint#469]
I'm having a problem on Windows since I migrated my application from gtk2 (pygtk) to gtk3 (pygi). Let me explain the story:

Before the migration, I used the pygtk-aio installer (http://ftp.gnome.org/pub/GNOME/binaries/win32/pygtk/2.24/pygtk-all-in-one-2.24.2.win32-py2.7.msi) to get its runtime and retrieve the `libcairo-2.dll` from it that `cairocffi` needs on Windows. It used to work nicely!

After I migrated my application to pygi, it is still working nice on Linux. I can generate pdfs and print without any problems. But then I went to test it on Windows and got [this error](https://github.com/Kozea/cairocffi/issues/1). Since the pygi-aio installer doesn't have that dll (it appears that `cairo` is compiled statically there), I retrieved it from other sources. One from [this bundle](http://win32builder.gnome.org/) and another one from the `cairocffi` build in [this page](http://www.lfd.uci.edu/~gohlke/pythonlibs/). Both of those dlls seems to be fine. I can even use them to draw some things in my application using caircffi directly.

Now comes the problem. When I call `Document.write_pdf` it get this assertion error and my application crashes:

```
Assertion failed: ! scaled_font->cache_frozen, file cairo-scaled-font.c, line 1166
```

I tried searching for the error and didn't find anything that would provide me a workaround or something like that, I only know that it is somewhat related to fonts... Am I missing something here?

**Comment by liZe** [comment]
It looks like a bug in Cairo, reported [here](https://bugs.freedesktop.org/show_bug.cgi?id=85141) and [here](https://bugs.freedesktop.org/show_bug.cgi?id=78787) for example.

You probably hit this bug because the Cairo version has been updated between the two bundles. There's unfortunately nothing we can do here. My only patch for Cairo has been waiting for 3 years before being accepted (see #278), I won't contribute to Cairo anymore.

As this bug is related to fonts, you can try to change the fonts used in your documents and cross your fingers :crossed_fingers:.

**Comment by hackedbellini** [comment]
CC @romaia
