### ISSUE TITLE
Support relative file URIs in hyperlinks when using CLI

### ISSUE THREAD

**Issue by noverby** [Kozea/WeasyPrint#532]
For example when converting the following html to a pdf, it should be possible to make the hyperlink refer to the relative URI and not the absolute URI:
```html
<a href="external-file.pdf">File</a>
```
What I get: "file://absolute-path/external-file.pdf"
What I want: "external-file.pdf"

I have tried to change the --base-url argument, but it does not remove the absolute path if I set it to ""(empty).

So I looked it up in the code, and it is fairly easy to change, but I just wanted to make sure that there is interest in including this feature. If there are indeed interest I can make a pull request.

Relative file URIs are also what [Prince](https://www.princexml.com/) outputs by default.

**Comment by liZe** [comment]
Hmmm… Really looks like #437, I'll take a look.

**Comment by liZe** [comment]
Unfortunately, what you want is currently impossible using the CLI:
- `HTML` finds `base_url` from the document when using a file,
- the CLI uses `'.'` instead of `None` as default `base_url` value when using stdin, and
- `base_url` is transformed into an absolute path when it's different from `None` (even if it's `''`).

Even if these 3 choices may look strange when looked at carefully, I think that they are actually really good when they're used without thinking (and that's what most CLI users do). I don't want to change this behavior.

So you currently have to use `HTML(string='<a href="external-file.pdf">File</a>')` to get what you want.

A solution would be to transform `--base-url=""` into `base_url = None`, and keep `base_url = '.'` when `--base-url` is not set. You would then be able to get relative URIs using `weasyprint --base-url="" - output.pdf < input.html`. What do you think about that?

**Comment by noverby** [comment]
@liZe That would be nice. Thank you 👍

**Comment by W4RH4WK** [comment]
It seems like this does not work anymore.

I reference another PDF via `<a href="books/anarchy.pdf">` and even when calling weasyprint with `--base-url=""` it still writes an absolute path to the PDF.

**Comment by liZe** [comment]
> It seems like this does not work anymore.

It seems to work for me, when using both `--base-url=""`, and `- output.pdf < input.html` to give no filename hint.

**Comment by liZe** [comment]
> However, style sheets are no longer found:

Of course, they’re not found because there’s no `base-url`.

Handling your use case is not as easy as it looks. Even if we add a new option (something like `keep-local-anchors`), I think that it will be really hard to find a behavior that satisfies everyone.

If you want to get this feature, you can open a new issue so that we can discuss your use case and find a way to solve it in a quite flexible way. I can’t promise that it will be implemented, as the current behavior is already quite complex (even if it’s easy to use in easy cases, as explained above).

**Comment by W4RH4WK** [comment]
Alright. This is currently not high on my priority list. When I come around to this, I might checkout the code and see whether I can come up with something that is viable. I'll open an issue / PR as necessary.

Thank you for the information.
