### ISSUE TITLE
Way to attach resources from python

### ISSUE THREAD

**Issue by djKooks** [Kozea/WeasyPrint#539]
Hello.
This is a question of how-to attach params in python.
[sample.html]
```
<html>
    <head>
    </head>
    <body>
        <div>
           <h1>my_text<h1>
           <img src="my_image"></img>
        </div> 
        <table>
            <tr>repeat list_length</tr>
        </table>
    </body>
</html>
```

[sample.py]
```
page = HTML(filename='sample.html')
...
my_text = 'Title'
my_image = 'screenshot.png'
list_length = len(my_list)
...
page.write_pdf('sample.pdf')
```

What is a good way to put 'Title' and 'screenshot.png' in pdf file, and repeat table row via list length? Or is there a sample to refer?
Thanks.

**Comment by liZe** [comment]
What you're looking for is [built-in string formatting](https://docs.python.org/3.6/library/stdtypes.html#printf-style-string-formatting) or external template engines like [Jinja2](http://jinja.pocoo.org/docs/2.10/intro/#basic-api-usage).

For general questions about Python, you should ask [Reddit](https://www.reddit.com/r/learnpython/) instead of using this specific project issues :wink:.

**Comment by djKooks** [comment]
@liZe Thanks! I'll look on it.
