### ISSUE TITLE
Some diacritics are badly rendered unless html encodings are used (OpenSans)

### ISSUE THREAD

**Issue by mcmayer** [Kozea/WeasyPrint#547]
I encountered an issue with the rendering the diacritic "ä" (German Umlaut): When using [OpenSans](https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans) in a UTF-8 encoded html file the little dots on the "ä" move to the right sometimes. Other diacritics seem fine, though. Standard fonts like Helvetica, Arial, etc., are totally ok, of course.

See here: [page.pdf](https://github.com/Kozea/WeasyPrint/files/1541417/page.pdf)

When I use html encodings "&auml..." instead the problem disappears. 

It's puzzling. There might be a connection with unicode-ranges because until a recent upgrade (?) weasyprint generated error messages when using OpenSans.

Self-contained demonstration: [render-opensans.zip](https://github.com/Kozea/WeasyPrint/files/1541413/render-opensans.zip), tested on Linux and Mac OS, WeasyPrint version 0.41.

**Comment by liZe** [comment]
Thanks for this bug report!

> When I use html encodings "&auml..." instead the problem disappears.

`&auml` generates a 'ä' character (https://unicode-table.com/00E4/, C3-A4 in UTF-8), while your character is 'ä' ('a' + combining diaeresis, https://unicode-table.com/0308/, CC-88 in UTF-8). These characters are equivalent (they should look the same) but are not the same.

According to [this post](https://stackoverflow.com/questions/37271525/mpdf-open-sans-font-cannot-render-some-german-letters), the combining diaeresis character is not present in OpenSans. WeasyPrint uses OpenSans to render the 'a' and a fallback font to render the diaeresis, that's why they don't match.

I have the same problem for this character in my text editor using OpenSans.

> It's puzzling. There might be a connection with unicode-ranges because until a recent upgrade (?) weasyprint generated error messages when using OpenSans.

Unicode ranges are not supported in WeasyPrint (see #378), but that should't be a problem for you.
