### ISSUE TITLE
FontConfiguration is not working

### ISSUE THREAD

**Issue by alexarsh** [Kozea/WeasyPrint#548]
I try to follow the documentation, but the following code is not working for me from the python shell:

```
>>> from weasyprint import HTML, CSS
>>> from weasyprint.fonts import FontConfiguration
>>> font_config = FontConfiguration()
>>> html = HTML(string='<h1>The title111</h1>')
>>> css = CSS(string='''@font-face { font-family:'Titillium Web';src:url(https://fonts.gstatic.com/s/titilliumweb/v6/anMUvcNT0H1YN4FII8wpr6YfJ4wTnNoNUCmOpdh16Tg.woff2);}* {font-family: 'Titillium Web'}''')
>>> html.write_pdf('example.pdf', stylesheets=[css],font_config=font_config)
```

The generated pdf is not using my font.

I use Python 2.7.6, WeasyPrint==0.41, html5lib==1.0.1

**Comment by liZe** [comment]
Hi!

There are 2 different problems in your example:
1. you have to give `font_config` to the `CSS` class constructor (the documentation was wrong about a month ago, but it's OK now :wink:),
2. WeasyPrint doesn't handle WOFF2 fonts (at least on Linux, don't know for other OSes), because FreeType doesn't support them yet.

TIL: Google Fonts serves a different CSS file depending on the browser used, and this CSS has a link to a different font format. Using `@import url('https://fonts.googleapis.com/css?family=Titillium+Web');` as proposed by Google Fonts works in WeasyPrint.

After adding `font_config` and changing the WOFF2 font into TTF, everything seems to work!

**Comment by alexarsh** [comment]
Thanks a lot! 
Can you update the documentation please, with both items?

**Comment by liZe** [comment]
The `font_config` attribute is in the documentation both in the [tutorial](http://weasyprint.readthedocs.io/en/latest/tutorial.html#instantiating-html-and-css-objects) and in the [API](http://weasyprint.readthedocs.io/en/latest/api.html#weasyprint.CSS). Is there another place where's it's missing?

I've also added a couple of lines about supported font formats.
