### ISSUE TITLE
Named pages

### ISSUE THREAD

**Issue by SimonSapin** [Kozea/WeasyPrint#57]
css3-page defines "named pages": http://dev.w3.org/csswg/css3-page/#using-named-pages

The only non-trivial part of this is the cascade. Currently we compute in advance styles for every possible page. With named pages we might want to do this lazily.

**Comment by dmoonfire** [comment]
I'm trying to format books for publishing including all the related complexities with initial chapters and the like. Using named pages seemed like the right way to implement it. I was trying to grok the code to understand the problem so I figured I'd ask questions and make sure my understanding is correct.

Since `make_page` is what figures out the page format to use, it seems like that should have the ability to identify the page based on the first block element that would be on the page. That means we need to keep track of the desired page name through the HTML AST so we can query it from the first element.

> Next, a start page value and end page value is determined for each box as the value (if any) propagated from its first or last child box (respectively), else the used value on the box itself. A child propagates its own start or end page value if and only if the page property applies to it. (css3-page)

Also from the specification, the scope would be important because the "next" page is based on the last item on the page. That way if you have an item that sets a page followed by a second item with a different page, the second page is covered.

```html
<style>
  .p1 { page: page-1; }
  .p2 { page: page-2; }
</style>
<p class='p1'>On first page because no break</p>
<p class='p2'>
  On first page because still no break, if this is the last
  on the page, the next page will be page-2.
</p>
```

So, I would guess that the way to implement this is to:

1. Create two properties on the blocks:
    * `start_page_name`: The name of the page to use for the start of this block.
    * `end_page_name`: The name of the page for the last item in the block.
2. Go through the element tree and calculate the `start_page_name` and `end_page_name`.
    * If an element's selector defines `page`, both `start_page_name` and `end_page_name` would be identical.
    * If the selector doesn't define it, the `start_page_name` would be defined by the previous element's `end_page_name` or blank/undefined for the first page. As the system recurses into the element tree, it keeps track of the last page name of the last item (or parent item). The `end_page_name` would be the `end_page_name` of the last child or `start_page_name` if there is no child element.
3. Change `make_page` to use the `start_page_name` to figure out which page to look up. It won't need `end_page_name` because of previous step.
    * Instead of building up name `first_right_page` for the first page, it would be `first_right_pagename_page`.
    * The `:first` selector applies only to the first page of the document. However, this means that every named page will have to have a first, left, and right style tree to pick up whichever one will actually used.

Using the above rules, from my understanding of the specification, I could do initial chapter pages like this.

```html
<style>
  @page chapter {
    /* No headers, high top margin */
  }
  @page chapter {
    /* Headers, low chapter */
  }
</style>
<div class='chapter'>
  <h1>Chapter 1</h1>
  <p>It was a dark and stormy night...</p>
</div>
<div class='chapter'>
  <h1>Chapter 2</h1>
  <p>It was the best of times, it was the worst...</p>
</div>
```

Does this make sense or seem probable for the code?

**Comment by SimonSapin** [comment]
> ```html
> <style>
>   .p1 { page: page-1; }
>   .p2 { page: page-2; }
> </style>
> <p class='p1'>On first page because no break</p>
> <p class='p2'>
>   On first page because still no break, if this is the last
>   on the page, the next page will be page-2.
> </p>
> ```

This seems wrong. A page break is introduced between elements with a different value for the `page` property, so the second paragraph with be on the second page. (And the first page will have blank space at the bottom.)

https://drafts.csswg.org/css-page/#using-named-pages
> If […] then a page break is forced between the two boxes, and content after the break resumes on a page box of the named type.

**Comment by dmoonfire** [comment]
You are correct, I missed that. I would then amend a step that automatically puts a `page-break-before: always` for any selector element that has `page` and doesn't have a break. I think that would resolve that case.

I do believe the scope on `page` is still correct.

Now, my chapter example is wrong but going over the specification, I suspect it can't be done without a vendor flag since there is no pseudo selector for "first page after a forced page break".

**Comment by SimonSapin** [comment]
The “high top margin” can be on the chapter title rather than on the page. But yes, I believe that css-page level 3 does not provide something flexible enough to inhibit a page-margin box on the first page in a chapter. The only thing I can think of is a huge hack like this to mask it with a white rectangle:

```css
.chapter > h1::before {
    content: "";
    position: absolute;
    /* bottom of this pseudo-element is placed at:
       100% of the page’s height from the page’s bottom
       which is the page’s top. */
    bottom: 100%;
    height: 3cm; /* same a margin-top in @page */
    width: 100%;
    background: white;
}

**Comment by dmoonfire** [comment]
Or just create a vendor pseudo class (`:x-first-named`). I'll see if that hack works for me, I have to get a book formatted by the end of the month but I can do a little drudge work to get around the page number problem (mainly because 93 hasn't been resolved either, I looked at that one also).

Is the overall suggestion reasonable?

**Comment by dmoonfire** [comment]
@SimonSapin: That hack almost worked but it puts the box underneath the text and I can't use `z-index` to get over it. I suspect because the blocks are laid out before the page elements are insert in.

**Comment by SimonSapin** [comment]
GitHub parsed "hope on our long way to close #57." in #485 as "This PR closes #57", which I believe is not the case. @liZe, can you confirm?

**Comment by liZe** [comment]
> @liZe, can you confirm?

Of course, it's not closed (yet).

**Comment by liZe** [comment]
It's closed now!

If anyone is interested (@dmoonfire @hejsan @psmolenski), I'd like to know if it works for your use cases. I've added some unit tests and tried with real-life documents, it fits my needs (and the spec I hope).

There is room for improvements, including tests with page names, pseudo classes and specificity (easy), less stupid code (easy) and lazy style loading (hard). Please ask for help if you want to fix that!

I'll release 0.40 soon if nothing's bad for anyone here.

**Comment by andul** [comment]
@liZe thanks for your great work! We tested the named pages feature and it runs just wonderful! No problems discovered on our test cases.

**Comment by dmoonfire** [comment]
@liZE: I did a quick ad-hoc test for my purposes and the named pages work out very nicely. I was happy to see that the `page: chapter` only applied to the next page and then it went back to the `:right` and `:left` which handled my need for leading chapter pages having a different style from the rest of the chapter.

My hack was to render each chapter twice (leading chapter page and then the rest), then use `pdfcat` to combine the two together. Since I can't reset page numbers, I had to add blank pages to get the page numbers right. It was kind of messy but it worked out good enough for a good-looking book.

With this, it looks like I only need to render stuff twice: once for the front matter which doesn't have page numbers, and once for the main matter using named pages. That should *significantly* reduce the generation time, thank you!

**Comment by liZe** [comment]
Happy to see that this feature is helpful! @dmoonfire I'd love to have HTML and PDF samples of your books if possible, and find what's missing to generate them without `pdfcat`.

**Comment by dmoonfire** [comment]
@liZe: Let me update my `mfgames-writing-weasyprint` package to use named pages and I'll be glad to give you the HTML source. Right now, the system generates 1-2 PDFs per chapter/section and stitches them together, so it's a mess with 37 sections and 74 PDFs. :)

The final result can be seen here, https://fedran.com/sand-and-bone/dmoonfire-100-02-sand-and-bone-1.0.1.pdf (my novel is CC-BY-NC-SA, so no trouble putting it online).

If you want to D/L a version (and have Node), there is a full demo with only a few chapters at https://gitlab.com/mfgames-writing-js/example-frankenstein. Running `./node_modules/.bin/mfgames-writing build pdf` once everything is populated should generate the output with loads of debugging that shows how I stitch everything together today.

For the most part, I just need `counter-reset: page 1;` in a named page to make it be a single generated PDF. This is because page numbers should start at 1 for the first page of the first chapter, not the 10 pages of front matter (legal statements, title pages, dedications, etc.) You see that on page 11 of the PDF.

I haven't checked to see if `content: counter(my-awesome-counter, lower-roman);` works yet. I don't have page numbers in the front matter but those aren't that important. :)

**Comment by SimonSapin** [comment]
> For the most part, I just need `counter-reset: page 1;` in a named page

I think that, if supported, this would reset the counter to 1 on every single page of the group of pages that share that "name". You’d need either:

* Some way to select the first page of a group. `:first` is the first of the entire document.
* Or make `counter-reset: page 1;` work on *elements* (e.g. `h1`, used together with `page-break-before`). This may be tricky to implement.

**Comment by dmoonfire** [comment]
Since the `page: chapter;` only applies to the next page and then it goes back to the normal `:right` and `:left`, I can easily have a `page: first-chapter;` that is only applied to the first chapter to reset the number and then just have a sequence of `:right`, `:left`, and `chapter` pages for the rest of the document.

The problem with `:first` is that the chapter is page 10 and `:first` only applies to page 1.
