### ISSUE TITLE
No images if "https" in the src path, but work if "http".

### ISSUE THREAD

**Issue by albertlidas** [Kozea/WeasyPrint#597]
**WeasyPrint 0.42.2, Ubuntu 14.04**

I'm using WeasyPrint in a django project. 
And the weasyprint doesn't print images if the "https" is in the src path. 
I'm using absolute path rather than relative for the src.
I would appreciate any suggestions. Thanks!

**Comment by liZe** [comment]
> And the weasyprint doesn't print images if the "https" is in the src path.

The problem can be caused by various reasons, here are the ones I can think of:
- accessing your URLs require authentication,
- there's something wrong with your server certificate,
- your list of authorized certificates is outdated.

You can try to reach your HTTPS URL using curl **on your server** and see if there's something wrong. You can also read WeasyPrint [logs](http://weasyprint.readthedocs.io/en/latest/tutorial.html?highlight=logs#logging).

Using [Django-WeasyPrint](https://github.com/fdemmer/django-weasyprint) is also a good idea: it will avoid a lot of useless HTTP requests on your server by automatically replacing HTTP(S) URLs by absolute paths.

**Comment by albertlidas** [comment]
Thank you for reply!
I'll check this out next week. Temporary resolved with data-uri in the image src.
