### ISSUE TITLE
Possibility to pre-process CSS stylesheets once and for all ?

### ISSUE THREAD

**Issue by Zulko** [Kozea/WeasyPrint#618]
Hi there and thank you for an awesome library.

I am writing a [PDF report generation library](https://github.com/Edinburgh-Genome-Foundry/pdf_reports) based on Weasyprint. The library relies on the Semantic UI CSS framework which provides styles and components that play well with PDF documents.

The problem is that Semantic UI is a large library, and every time I generate a PDF, more than 3 seconds are spent in the function ``preprocess_stylesheet`` (and then around 0.3 seconds for the actual PDF generation). Here is some code to reproduce the issue:

```
import cProfile
from pdf_reports import write_report

html = "<p>hello world !</p>"
cProfile.run("""
write_report(html, "example.pdf")
""")
```

I was wondering if there was a way for the Weasyprint user to pre-process the CSS once and for all (and obtain a pre-built PDF renderer using that CSS), and then for all PDF renderings, write pdfs with ``weasyprint.write_pdf`` or equivalent, using that preprocessed CSS. Would that make sense ? Is there already a way to do this ?

Many thanks !

**Comment by liZe** [comment]
> Hi there and thank you for an awesome library.

:smile:

> I was wondering if there was a way for the Weasyprint user to pre-process the CSS once and for all

Yes, you can, but you'll have to use the `CSS` class instead of adding the link to your CSS stylesheet in your HTML file. Following [the tutorial](http://weasyprint.readthedocs.io/en/latest/tutorial.html#as-a-python-library) will probably help you to achieve what you want.

If for some reason you can't edit your HTML file and remove the link to your CSS stylesheet, there are other solutions (like using your own `url_fetcher`). I can explain that too if you want.

**Comment by Zulko** [comment]
Now it works like a charm ! I did go through the docs but missed this somehow. Thanks very much !
