### ISSUE TITLE
Export HTML to PNG  with 300 resolution

### ISSUE THREAD

**Issue by panchaljaimik** [Kozea/WeasyPrint#653]
when i'm export HTML to PNG  without applying resolution in write_png function then image resolution is 96 this default resolution applied in write_png function  
`def write_png(self, target=None, stylesheets=None, resolution=96,
                  presentational_hints=False, font_config=None):`
but when i'm applying resolution = 300 in write_png then exported  image resolution is 96 instead of 300. 
 
from weasyprint import HTML
from weasyprint.fonts import FontConfiguration
font_config = FontConfiguration()
html = HTML(filename='test.html')
html.write_png(
    'test.png',
    font_config=font_config,
    resolution=300
)

[test.zip](https://github.com/Kozea/WeasyPrint/files/2168175/test.zip)

![test](https://user-images.githubusercontent.com/35117526/42347194-be71ee0e-80c2-11e8-84c4-6d8bfcd1c4d5.png)

**Comment by Tontyna** [comment]
It sounds like you expect to influence the, hmm... DPI of the PNG -- as far as I know: there are only dots in the PNG, no inches. Paper or screens have inches, and if you draw pixels on them you get DotsPerInch...

The `resolution` parameter in `write_png()` influences the size of the produced PNG. E.g. with resolution=300 the PNG's size is 1800 x 2700 pixels, instead of the 576 x 864 pixels you get with resolution=96.

**Comment by liZe** [comment]
> It sounds like you expect to influence the, hmm... DPI of the PNG -- as far as I know: there are only dots in the PNG, no inches. Paper or screens have inches, and if you draw pixels on them you get DotsPerInch...

It's true. You can find more about this [on Wikipedia](https://en.wikipedia.org/wiki/Dots_per_inch#DPI_or_PPI_in_digital_image_files).
