### ISSUE TITLE
Problem with image in Docker

### ISSUE THREAD

**Issue by DiegusMiestro** [Kozea/WeasyPrint#707]
Hello,

I'm using WeasyPrint in the Django Framework in Docker environment. When using PDF generation with images, the images do not appear, gives the error:

Failed to load image at "http://127.0.0.1/public/test.jpg" (URLError: <urlopen error [Errno 111] Connection refused>)

I do not know how to solve this problem. Does anyone have any information on how I should resolve?

PS: If I use an image that is hosted on the internet works normal.

**Comment by liZe** [comment]
Hello!

> Failed to load image at "http://127.0.0.1/public/test.jpg" (URLError: <urlopen error [Errno 111] Connection refused>)

It means that your process cannot reach the URL. Is this URL available from your Docker environment, for example with curl?

When using WeasyPrint in web apps, there are many reasons why static files can't be reached, for example:
- static files access needs authentication,
- using one thread/process is not enough to serve both your PDF rendering from a request and a static file from another request,
- different IP or domain resolution from the web server and the web client,
- etc.

That's why you should use [Django-WeasyPrint](https://github.com/fdemmer/django-weasyprint). This library tries to automatically replace URLs to your static files by local file access, avoiding useless extra requests and problems listed above.

**Comment by liZe** [comment]
@DiegusMiestro Did you find the time to try Django-WeasyPrint?

**Comment by liZe** [comment]
Feel free to reopen if there's something new for this issue.
