### ISSUE TITLE
Support for :nth() page selectors

### ISSUE THREAD

**Issue by Smylers** [Kozea/WeasyPrint#724]
WeasyPrint doesn't yet support GCPM's [page selectors and page groups](https://drafts.csswg.org/css-gcpm/#document-page-selectors), for being able to do things like have the first page of each chapter use different page headings and footers.

This is a documented limitation (and this isn't a complaint!). I'm just opening this now so that we have an issue URL to put in the comment of a workaround we've implemented; then any future developer on our code who encounters the workaround can easily check whether it's still necessary.

**Comment by liZe** [comment]
> WeasyPrint doesn't yet support GCPM's [page selectors and page groups](https://drafts.csswg.org/css-gcpm/#document-page-selectors), for being able to do things like have the first page of each chapter use different page headings and footers.

True, but it supports [named pages](https://drafts.csswg.org/css-page/#using-named-pages) that may be helpful for this case.

**Comment by Tontyna** [comment]
`@page :nth` would be a great feature, though a quick reflection about how to implement it results in: "I'm not eager to write the code."

**Comment by LukasKlement** [comment]
I'm having exactly this issue at the moment, where I do not know how it can be solved without the :nth() page selector:

- I am rendering trifold flyer, each page with columned content flowing from one page to the next
- The pages are being merged in the correct order using pdfrw PDFMerge()
- I need bleed to be on the outside borders, but not on the inside (page 1: <>mm <>mm <>mm 0; page 2: <>mm 0 <>mm <>mm; page 3: <>mm 0; etc.)

Since columns flow from one page to the next, I cannot use named pages. Setting a single bleed value will create the bleed also at the fold ... how would you solve this without the @page :nth() feature?

**Comment by liZe** [comment]
> how would you solve this without the @page :nth() feature?

You probably can't, :nth() looks like the perfect solution for that!

The more I think about this feature, the more it seems easy to add… Of course, it's always "not that easy" in the end :smile:. I'll check that soon.

**Comment by liZe** [comment]
`:nth(x)` and `:nth(An+B)` syntaxes have been added in the [`nth-page`](https://github.com/Kozea/WeasyPrint/tree/nth-page) branch. I'd be happy to have some testers!

Does anyone need [page groups](https://drafts.csswg.org/css-gcpm/#document-sequence-selectors) here?

**Comment by liZe** [comment]
@Smylers I'll close this issue when `:nth` support is merged, and change the title accordingly. Would you mind opening a new issue for page groups if you are interested in the issue?
