### ISSUE TITLE
sample report not produced correctly

### ISSUE THREAD

**Issue by daghemo** [Kozea/WeasyPrint#851]
When trying to reproduce the the sample report from samples/report I see something weird on the page break just after the cover:

![WeasyPrint-SampleReportFailing](https://user-images.githubusercontent.com/42886403/56122402-a6271380-5f72-11e9-8077-26ac588f2386.png)

I'm running on a CentOS 7.x using:

```
pip3 install WeasyPrint
git clone -b gh-pages --single-branch https://github.com/Kozea/WeasyPrint.git
weasyprint WeasyPrint/samples/report/report.html /var/www/html/report.pdf

```

**Comment by betafcc** [comment]
Same here, on LinuxMint 19.1, python 3.7.3, with weasyprint 47 and 46, but it does render correctly on 45, possibly a regression? Or maybe the sample was relying on some wrong implementation?

Workaround, downgrade: `pip install weasyprint==45`

**Comment by knixeur** [comment]
I can reproduce the problem.
The expected PDF can be found at https://weasyprint.org/samples/report/report.pdf
It can be fixed by changing html body article#cover address { padding: 1cm 0; } to 0 1cm; but I don't know the expected result from this, if it's something that was fixed like @betafcc said or something that's wrong.

**Comment by liZe** [comment]
Thank you for reporting this issue.

It's a float rounding point error, I can fix it quite easily.
