### ISSUE TITLE
Annoying warning with custom fonts

### ISSUE THREAD

**Issue by GitRon** [Kozea/WeasyPrint#883]
Hi there,

I have a really annonying warning in my system:

I include my fonts like this (in a scss-file):

```
@font-face {
  font-family: 'MyFont Light';
  src: url('static://fonts/MyFont-Light.eot');
  src: url('static://fonts/MyFont-Light.eot?#iefix') format('embedded-opentype'),
  url('static://fonts/MyFont-Light.ttf') format('truetype'),
  url('static://fonts/MyFont-Light.woff') format('woff'),
  url('static://fonts/MyFont-Light.woff2') format('woff2');
}
```

I get on every PDF rendering this error:

> Failed to load font at "static://fonts/MyFont-Light.eot?#iefix" (URLError: <urlopen error [Errno 2] No such file or directory: '/src/project/static/fonts/MyFont-Light.eot?'>)

**Important thing: It works! The font is recognized and everything looks good! It's just about this error messages spamming my logs.**

What I've tried so far:

1) Removing `?#iefix`. No logs but font is not recognized.
2) Leave out the second `src` line at all. No logs but font is not recognized.
3) Have both `src` lines include the same path. No logs but font is not recognized.

Any ideas what I can do? I really don't get why I need the iefix for weasyprint...

Thanks!  
Ronny

**Comment by liZe** [comment]
> Any ideas what I can do? I really don't get why I need the iefix for weasyprint...

You don't.

The logs are actually right, query strings are not allowed here, and there's no `MyFont-Light.eot?` file on your system. See #687.

EOT and WOFF2 file formats are not handled by WeasyPrint, so it probably means that it uses the TTF font. Using this rule should work:
```css
@font-face {
  font-family: 'MyFont Light';
  src: url('static://fonts/MyFont-Light.ttf');
}
```

> What I've tried so far:
> 
> 1. Removing `?#iefix`. No logs but font is not recognized.
> 2. Leave out the second `src` line at all. No logs but font is not recognized.
> 3. Have both `src` lines include the same path. No logs but font is not recognized.

At least your first point should work. The second one doesn't work because EOT fonts are not supported, and the third one may be broken too depending on what you exactly did. It's easy to break this CSS rule because the second `src` descriptor has multiple lines, and because of the commas / semicolons, so maybe there's something wrong in the way you changed it… By the way, using the sample above should work.

**Comment by GitRon** [comment]
Looks good! Thank you so much! Saved me ages of time!
