### ISSUE TITLE
flex-direction: row-reverse; results in 'infinite' pages

### ISSUE THREAD

**Issue by KilianCroese** [Kozea/WeasyPrint#896]
Consider this html file: [flex-direction-row-reverse.html](https://github.com/Kozea/WeasyPrint/files/3373831/flex-direction-row-reverse.txt)

When the contents don't fit on the first page, the rendering is stuck in an infinite loop trying to render pages. Note that there is only content for two pages. See the attached [debug log](https://github.com/Kozea/WeasyPrint/files/3373852/flex-direction-row-reverse-log.txt) for more details. When you remove the flex-direction: row-reverse;  two pages are rendered as expected. If there is not enough content for a second page, then it also works as expected. This can be tested by removing some of the paragraphs.

**Comment by Tontyna** [comment]
Tried to find out what's going wrong here. Therefore experimented with FlexBoxes that spread across pages and ... hm ... as soon as FlexBoxes spread across pages the output is buggy, no matter what the `flex-direction` is. 

That's because WeasyPrint doesn't support parallel flow, as @liZe pointed out in https://github.com/Kozea/WeasyPrint/issues/36#issuecomment-298069436

Nevertheless, WeasyPrint shouldn't loop forever. 
In `flex_layout()` the infinite-loop-situation can be detected by comparing `original_skip_stack` with the to-be-returned `resume_at`.

https://github.com/Kozea/WeasyPrint/blob/87d9e84f285654db3bc25e7c96a542fbed79a216/weasyprint/layout/flex.py#L881

Have no idea but `assert resume_at != original_skip_stack, 'infinite flexbox loop'` -- because at this point the layout is already corrupt (duplicated content)

**Comment by liZe** [comment]
> That's because WeasyPrint doesn't support parallel flow, as @liZe pointed out in [#36 (comment)](https://github.com/Kozea/WeasyPrint/issues/36#issuecomment-298069436)

It's true. the solution used now (with or without `reverse`) is to skip the already rendered flex items. There was a bug in the way the skip stack was used when the order is reversed, we used to keep the children after the current one, but we had to keep the ones before (as the ones after are already rendered).
