### ISSUE TITLE
Resulting PDF only has one page

### ISSUE THREAD

**Issue by mbrochh** [Kozea/WeasyPrint#9]
I just installed weasyprint on Ubuntu. It seems to work great but the resulting PDF only has one page. 

I'm trying to generate a PDF from a Sphinxdoc. WeasyPrint is smart enough to strip away the left hand navigation and only render the real content of the docs but it just stops after the first page. At the very bottom o f the page I can see half of a line of text and then the document just ends.

This seems to a problem specific to Sphinxdocs. I just tried to render the weasyprint website and this works, I get multiple pages. Then I tried to render some sphinxdocs (i.e. weasyprint http://bitmazk-pte-ltd.readthedocs.org/en/latest/code_conventions/python.html test.pdf) and again I end up with just one page.

Do I need to add the -s flag and add some css tricks in order to get proper page breaks?

**Comment by dedesite** [comment]
Hello,
I got the same problem on a recent weasyprint version (57.2) and the workaround doesn't work anymore (I assume `float` is now supported by weasyprint). I know that the problem comes from the css theme used by Sphinxdoc, but there is more than 12000 rules, how can I know the faulty one ? I try to disable the `display: grid` rules without success.

The example given above give the same result (one page only pdf), so it's easy to reproduce.

**Comment by liZe** [comment]
The problem is caused by this rule: `.wy-grid-for-nav { position: absolute }`. Overriding this rule using `.wy-grid-for-nav { position: static !important }` fixes the problem.

**Comment by dedesite** [comment]
Thank you @liZe I wouldn't have found it alone ! This is great !
