### ISSUE TITLE
How to repeat on each page of complex headers (eg, tables)?

### ISSUE THREAD

**Issue by pikhovkin** [Kozea/WeasyPrint#92]
Hello!
Please tell me how to repeat on each page of complex headers (eg, tables) at the top and bottom of the page?

**Comment by jsenecal** [comment]
FWIW, I'm using what @pikhovkin shared and it does wonders. Like @SimonSapin mentionned - it could be nice to document those APIs.

**Comment by doekman** [comment]
Hi, based on the gist of @pikhovkin, I created an extension to Flask-WeasyPrint in [this gist](https://gist.github.com/doekman/4674dd2d05b643ef57e747cfdc81c3c9). It's still a bit rough, but I thought to share it, report my findings and possibly get feedback.

I understand it uses undocumented API's. I take my chances, because I don't know an other way to create the PDF's I need with WeasyPrint. But documenting them would be appreciated a lot!

It uses Jinja2 to render the Overlay HTML (header/footer-HTML), so page number and number of pages can be used in HTML. Custom positioning of content can be done by supplying positions through the context which will be rendered by Jinja2.

The render method shares the `stylesheets` with the Overlay pages to prevent errors like "CAIRO out of memory" (I probably got this error because I used @font-face definitions, and this way, the FontConfiguration is shared).

**Comment by whitelynx** [comment]
Has there been any progress on GCPM in the last 3 years? Is it getting to a stage where we could start implementing something based on it?

**Comment by liZe** [comment]
> Has there been any progress on GCPM in the last 3 years?

Yes, you can check [what the CSSWG did](https://drafts.csswg.org/css-gcpm/).

What we want is [running elements](https://drafts.csswg.org/css-gcpm/#running-elements). With named pages (added in #495), we should be able to repeat complex headers in page margins.

> Is it getting to a stage where we could start implementing something based on it?

Of course. Even if GCPM is "a long story" and "a big mess", running elements can IMHO be added safely to WeasyPrint. The spec didn't really change during the last years, the [only reported issue](https://drafts.csswg.org/css-gcpm/#issue-81a9d129) even includes an interesting alternative syntax to fix it.

Implementing both syntaxes looks like a good idea for me. Even if it's a draft, the feature is useful and having it implemented may even help the CSSWG.

Anyone interested? I'll be happy to help!

**Comment by liZe** [comment]
@doekman

> The render method shares the stylesheets with the Overlay pages to prevent errors like "CAIRO out of memory" (I probably got this error because I used @font-face definitions, and this way, the FontConfiguration is shared).

That's probably fixed now that #441 is fixed.

**Comment by biggosh** [comment]
Hi @liZe.

Is there any planned date for running and element support? I've seen the code and I've noticed there is many parts to touch. If you can give me some suggestions (what to touch and where to insert my code) I can try to start with a simple implementation.

**Comment by liZe** [comment]
> Hi @liZe.

Oh, I'm late…

> Is there any planned date for running and element support?

Unfortunately, no.

> I've seen the code and I've noticed there is many parts to touch. If you can give me some suggestions (what to touch and where to insert my code) I can try to start with a simple implementation.

Currently, I have no idea about how to implement that, but I can help if you're still interested (and I won't wait half a year this time).

**Comment by zilles** [comment]
Just something for the next person to find this thread:
The "content" property you use in the margin boxes (@top-center) can point to an svg file with arbitrarily complex layout.  I used this to create a complex header that would not have been possible with text content.

**Comment by nathandem** [comment]
Hi there,

I recently encountered the same header/footer problem mentioned above by several in this github issue (and elsewhere). Inspired by the examples above, I wrote a solution which is, I think, a little bit more polished and that could/should be integrated in the lib.

Here's the code:
https://gist.github.com/nathandem/63f410d501d200cfa5613b38aaf74c44

Why including this patch in the core?
Disclaimer: it doesn't try to takes into account web standards, but it will solve a major pain point for the lib users who want to create professional looking PDFs.
I had to spend a lot of time searching online plus digging on the internal API to come up with a solution, I'd like to spear this effort/time to the next users :) This is the reason why I think that the feature should be integrated in the core (and visible right away in the doc).

Next steps
If the idea of this patch gets accepted, I'd to receive some guidance from the maintainer to know 1) if there're some elements I could improve to reach the code standard of the lib, 2) where I should put the code. I guess some of it should be part of the public API (the main `weasyprint/__init__.py`), some may be located elsewhere (maybe `weasyprint/layout/pages.py`?). I will then write a PR with tests and documentation, so that everyone can solve this problem quickly from now on!

So, are you interested in me adding support for this feature in Weasyprint? :)

PS : If someone launches himself/herself in a major rewrite to support the newer standards someday (proper support of flexboxes and co), this section of the code (along others) will probably be rewritten. Yet in the meantime (it's been already 6 years!), this will help many!

Cheers!

**Comment by liZe** [comment]
> Here's the code:
> https://gist.github.com/nathandem/63f410d501d200cfa5613b38aaf74c44

Hey, that's really useful :heart:, thanks a lot for sharing this!

> Why including this patch in the core?
> Disclaimer: it doesn't try to takes into account web standards, but it will solve a major pain point for the lib users who want to create professional looking PDFs.

Integrating this in the core may look like a good solution, but I think it's not. WeasyPrint has a long history with web standards, and the golden rule I now know from this history is that we really often have to blindly follow specifications. There's an endless work waiting for us to implement the specs, and each time we've tried to create our own specs it ended in a bad way. Moreover, maintaining this code (ie. fixing bugs, but also adding new features, and keeping it almost forever as it would be in public API, even if it relies on WeasyPrint's internals) is not a work I want to do.

> Next steps
> If the idea of this patch gets accepted, I'd to receive some guidance from the maintainer to know 1) if there're some elements I could improve to reach the code standard of the lib, 2) where I should put the code. I guess some of it should be part of the public API (the main `weasyprint/__init__.py`), some may be located elsewhere (maybe `weasyprint/layout/pages.py`?). I will then write a PR with tests and documentation, so that everyone can solve this problem quickly from now on!

I really appreciate your work, the code is clean and could be really useful to a lot of people. Maybe adding it in the documentation (and probably the whole issue) is the solution for now. It also would be useful to have a place where code snippets (both CSS and Python) could be shared, but I don't know how/where to do this.

> So, are you interested in me adding support for this feature in Weasyprint? :)
> 
> PS : If someone launches himself/herself in a major rewrite to support the newer standards someday (proper support of flexboxes and co), this section of the code (along others) will probably be rewritten. Yet in the meantime (it's been already 6 years!), this will help many!

Actually, supporting running elements doesn't need a major rewrite, and I think that it would be a great way to support this feature in WeasyPrint :smile:. I can help, of course (but it looks like you already know WeasyPrint internals quite well!)

About a proper support of flexbox, the work mainly has to be done in `flex.py` and it wouldn't take a lot of work to improve the current situation (which is not that bad, is it?)

**Comment by nathandem** [comment]
Thanks for your feedback @liZe :)

I understand your point of not wanting to include this hack in the codebase. It'd break the project rules and would have to be maintained.

I didn't actually thought about it first, but including a reference to this snippet in the documentation would in practice (almost) achieve the same result! I say almost because it wouldn't be as straightforward integrate for beginners as importing the lib and calling a method directly. But say 80% of the users should be able to go along without having to digging outside the doc, so that'd already a big improvement!

I'd suggest to add a new section in the documentation entitled "Tips & tricks" (or something along this line). This code would be the first snippet in this new section. I'd also complement it with a little explanation, an example or two and add a short reference from the tutorial part to it. The other snippets you mentioned would then go in the new section too.

Concerning the running elements, I don't want to advance myself on this - because of time, competence and motivation. But if this proposal of this new section of the doc and this code + explanation is deemed interesting, I can do that for this weekend ;)

**Comment by tookas92** [comment]
> 
> Here's the code:
> https://gist.github.com/nathandem/63f410d501d200cfa5613b38aaf74c44
> 

Hey I have problem with this solution. In my header I want to add image and everytime I render pdf instead of header image I have only alt attribute text. Why it might happen?

**Comment by nathandem** [comment]
@tookas92 The problem may come from the fact that you use relative urls in your header and you forgot to provide a `base_url`. (Note: in case you are using Django, you can get the base url easily from your views with `request.build_absolute_uri()`.)

If it doesn't help, please create gists with a copy of the relevant files + your settup and share the links here so that I can have a look ;)

**Comment by liZe** [comment]
Now that the documentation has been updated (thanks @nathandem!), I think that we can close this issue. Don't hesitate to add comments if you find new tricks.

**Comment by cicuz** [comment]
> Just something for the next person to find this thread: The "content" property you use in the margin boxes (@top-center) can point to an svg file with arbitrarily complex layout.

@zilles those tip and snippet seem very interesting, but I wasn't able to get them to work.. do you think they're still valid after these years?

**Comment by prohui** [comment]
I found a new solution by running the element and running function of CSS.
Below code:
CSS part:
```

@page {
  margin: 1.1cm .5cm 2cm .5cm;
  @top-left {
    background: #fbc847;
    content: counter(page);
    height: 1cm;
    text-align: center;
    width: 1cm;
  }
  @top-center {
    background: #fbc847;
    content: '';
    display: block;
    height: .05cm;
    opacity: .5;
    width: 100%;
  }
  @top-right {
    content: element(header);
    font-size: 9pt;
    height: 1cm;
    vertical-align: middle;
  }

  @bottom-left {
    content: element(footer);
    font-size: 9pt;
    height: 1.8cm;
    vertical-align: bottom;
    width: 100%;
  }

}
#page-header {
  position: running(header);
}

#page-footer {
  display: flex;
  justify-content: space-between;
  position: running(footer);
}
```
HTML part:

```
...
<div id="page-header">
a complex header
</div>
<div id="page-footer">
  <div>
  footer
  </div>
  <div style="align-items: baseline">
    <img src="logo.png"/>
  </div>
</div>
...
```
