### ISSUE TITLE
Certain fonts not getting recognized while using WeasyPrint

### ISSUE THREAD

**Issue by naseefo** [Kozea/WeasyPrint#935]
Hi there!

First of all thank you for this great package.

Certain fonts such as "VAG Rounded Std Think", which is an Open Type font (with extension *.otf) does not get recognized in PDF documents created with WeasyPrint. Though it works where the template HTML is loaded directly in the browser.

I have seen from the official documentation that Pango >1.38 needs to be installed for it to detect other types of font, though I am not sure if it applies to font I mentioned above. To my disappointment, I am not able to get Pango anywhere for my 64-bit windows 10. Is there any workaround for this?

**Comment by Tontyna** [comment]
Both [GTK+ libraries mentioned in the docs](https://weasyprint.readthedocs.io/en/stable/install.html#step-4-install-the-gtk-libraries) currently provide Pango 1.43.0.

**Comment by naseefo** [comment]
I had installed GTK+ 64-bit for windows but it was not detecting the font file from the"Windows>font" folder. I had then used the work around mention in another issue posted here by specifying absolute path using @face-font

```
from weasyprint import HTML, CSS
from weasyprint.fonts import FontConfiguration

# few lines of code in this section is not included in this post

css = CSS(string='''
        @font-face {
            font-family: VAG Rounded Std Light;
            src: url(file:/C:/Users/xxx/OneDrive/Desktop/xxx/xxx/Fonts/VAGRoundedStd-Light.otf);          
        }
    ''', font_config=font_config)

    HTML(string=html_out, base_url='.').write_pdf("report.pdf", stylesheets=["PDFTemplates\\Report01\\AppendixTemplate.css", css], font_config=font_config)
```

**Comment by Tontyna** [comment]
@naseefo Since 12 Jun 2018 the GTK+ 64-bit Runtime **should** detect the fonts in the Windows fonts folder. So your workaround with `@font-face` should be obsolete when the "VAG Rounded Std Think" is installed on your system.

Nevertheless: If in your console output you get a warning like `WARNING: Font-face "VAG Rounded Std Light" cannot be loaded` this indicates that the OTF-file doesnt exist or isnt a valid font file at all.
Please verify & double-check the url in your `@font-face` rule.

@liZe I remember there were times when a non-existing font file produced an URLError showing the invalid URL. Ok,  the ERROR was annoying, but knowing the URL is definitely helpful.

**Comment by Tontyna** [comment]
With debug logging the full UrlError is shown:

```Python
weasyprint.LOGGER.setLevel('DEBUG')
```

**Comment by liZe** [comment]
@naseefo Could you please try the `--debug` option to get full URLs?

**Comment by liZe** [comment]
@naseefo Can we close this issue?

**Comment by naseefo** [comment]
Yes. Sorry I did not notice this message. I have got it rectified. Thank you.
