### ISSUE TITLE
Wrong page-break in long lists (regression with version 49)

### ISSUE THREAD

**Issue by viaregio** [Kozea/WeasyPrint#945]
Since version 49 the the following code produces a very unpleasant page-break:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <style>
    @page {
            size: 100mm 100mm;
            margin: 20mm;
        }
    </style>
</head>
<body>
    <p>This is a demonstration of a regression from Weasyprint 48 to 49.</p>
    <ul>
        <li>One</li>
        <li>Two</li>
        <li>Three</li>
        <li>Four</li>
        <li>Five</li>
        <li>Six</li>
        <li>Seven</li>
        <li>Eight</li>
        <li>Nine</li>
        <li>Ten</li>
        <li>Eleven</li>
        <li>Twelve</li>
    </ul>
</body>
</html>
```

**Comment by Tontyna** [comment]
Introduced by 26a0ee5963d15ec41aac71195a3b987a9cf24068

**Comment by liZe** [comment]
Before supporting `::markers`, markers were special cases. They now are common boxes, positioned as absolute boxes by the user agent to display them outside the list item.

As absolute boxes are not in the flow, they can always be displayed on a page, even if they go outside their limits. If an absolute box is the first child of a parent box, it is then always displayed, even if the second child must be displayed on the next page. That's why markers were always displayed at the bottom of the page, and the corresponding contents were on the next page.

We now check that at least one in-flow child has been displayed in a parent box. If it only contains absolute boxes, they are removed and kept for next page.
