### ISSUE TITLE
Improper css var() causes crash

### ISSUE THREAD

**Issue by sureshvv** [Kozea/WeasyPrint#974]
Getting this error when I process this html file
[yy1.txt](https://github.com/Kozea/WeasyPrint/files/3752440/yy1.txt)

**Comment by Tontyna** [comment]
That's a crash with announcement -- do you see the WARNING ``Unsupported computed value `calc(var(--line-height) / var(--line-height-ratio))` set in variable `--font-size` for property `font-size`.``? 

That's because `calc()` isn't implemented in WeasyPrint. Although this shouldn't crash WeasyPrint. 

And indeed, it's not the unsupported `calc`, that crashes WeasyPrint, but the fallback value -- WeasyPrint's `compute` function detects that it cannot replace the `var(--fontsize)` and falls back to the font-size of the parent. Which happens to be a unit-less simple integer or float.
And crashes in the `font_size()` function. We could make `font_size` aware for simple numbers, but then the `length()` function will crash.

@liZe - this fallback to a unit-less parent property is fatal for **all** css properties that designate a length, didn't count the `COMPUTER_FUNCTIONS` that call the `length()` method and the css properties that directly call `length()`...

@sureshvv - even if WeasyPrint was able to calculate your `--line-height` value it would crash because the `calc()` in your css doesn't supply a unit, just plain numbers.

**Comment by sureshvv** [comment]
Browsers seem to handle it well. The html file displays perfectly in all the browsers that I have tested on. wkhtmltopdf also handles the same html file but not as well ;)

**Comment by Tontyna** [comment]
> Browsers seem to handle it well.

Yes, they dont crash. My Browser **ignores** the calculated dimension-less values and falls back to the initial or inherited value.

**Comment by Tontyna** [comment]
> this fallback to a unit-less parent property is fatal for all css properties ...

That's not true. Almost all of the 'lengthy' properties get a sane value from `INITIAL_VALUES` and/or the responsible `@register_computer` function handles the case when this value is an integer.

Looks like only `font-size` and `word-spacing` are affected by the unit-less fallback crash.

**Comment by Tontyna** [comment]
> Looks like only font-size and word-spacing are affected by the unit-less fallback crash.

Minimal example to crash WeasyPrint by `var()`:

```html
<style>
div {
  --value: invalidValue;
  border-spacing: var(--value);
}
</style>
<div>crash</div>
```

The complete list of properties that kill WeasyPrint when defined via an invalid `var()` value is:

 - word-spacing
 - font-size
 - border-spacing                
 - size     
 - content 
 - string-set
 - anchor 
 - link 
 - lang 
 - transform

**Comment by Tontyna** [comment]
@sureshvv would you be so kind and rename this issue to sth like "improper css var() causes crash"?

**Comment by sureshvv** [comment]
Done. Now who wlll fix this? ;)

**Comment by Tontyna** [comment]
> Now who wlll fix this?

- I'm currently preparing a PR to prevent the crash.
- AFAIK nobody is working on #357

**Comment by Tontyna** [comment]
@liZe -- your commit is a lot more elegant than #977 :+1: 

But it doesn't survive invalid values for `font-size` (fixed in `font_size()` by af7817163a073236294c6d7b139899d49d324163) and `transform` (fixed with `try..except` by 0bb4e2c0f09f88f9b06cf739cef648b0cec960aa).

Cf. f0a432fce6e7faac3ba5a5c7b12e833b70bd81a6, the full test for all `KNOWN_VALUES`.

**Comment by liZe** [comment]
> @liZe -- your commit is a lot more elegant than #977

I’ve missed your PR, even with your comment and the bold title below. I don’t know how it’s possible. Maybe it’s time to sleep.

:eyeglasses:

(I’m really sorry…)

> But it doesn't survive invalid values for `font-size` (fixed in `font_size()` by [af78171](https://github.com/Kozea/WeasyPrint/commit/af7817163a073236294c6d7b139899d49d324163)) and `transform` (fixed with `try..except` by [0bb4e2c](https://github.com/Kozea/WeasyPrint/commit/0bb4e2c0f09f88f9b06cf739cef648b0cec960aa)).

:disappointed: 

> Cf. [f0a432f](https://github.com/Kozea/WeasyPrint/commit/f0a432fce6e7faac3ba5a5c7b12e833b70bd81a6), the full test for all `KNOWN_VALUES`.

It’s much better than my little test.

I’ll cherry-pick some of your commits for sure, thanks a lot.

**Comment by liZe** [comment]
I’ve cherry-picked your test (and "parametrize" it, it’s easier to debug).

As you said, `transform` was crashing. I’ve removed (in c21028e1) the `InvalidValues` exception from this validator, as it was the only one doing this.

(But we should probably call `validate_non_shorthand` instead of calling `PROPERTIES[…]`, I don’t know how `initial`/`inherit` are handled now. In this case, we’ll have to cherry-pick 0bb4e2c too.)

`font-size` works well, even without af78171. As the value is already computed, we never call the computer function with integers.

**Comment by Tontyna** [comment]
> font-size works well, even without af78171

You're right, of course -- me needing more sleep, too
