### ISSUE TITLE
uneven letter spacing

### ISSUE THREAD

**Issue by jtauber** [Kozea/WeasyPrint#976]
This is with 49 (I had to revert as 50 was causing errors).

I'm seeing uneven letter spacing like the following:

<img width="134" alt="Screen Shot 2019-10-23 at 10 52 57 AM" src="https://user-images.githubusercontent.com/24426/67406063-94f33b00-f583-11e9-9bfd-2349caffe876.png">
<img width="214" alt="Screen Shot 2019-10-23 at 10 53 17 AM" src="https://user-images.githubusercontent.com/24426/67406070-97559500-f583-11e9-882d-38de0a6cf64c.png">
<img width="169" alt="Screen Shot 2019-10-23 at 10 53 31 AM" src="https://user-images.githubusercontent.com/24426/67406077-99b7ef00-f583-11e9-9f1c-a9e3df5510ea.png">
<img width="346" alt="Screen Shot 2019-10-23 at 10 55 47 AM" src="https://user-images.githubusercontent.com/24426/67406146-b18f7300-f583-11e9-970c-8465f1d49d2a.png">

Has anyone seen similar issues? Is this a problem with the metrics in the font file?

**Comment by jtauber** [comment]
I should add that these spacing issues do not appear in any browser I've tried.

**Comment by liZe** [comment]
> Has anyone seen similar issues? Is this a problem with the metrics in the font file?

That's hard to know for sure where the problem comes from, but I think that it's a problem with the kerning rules used by Pango.

Could you please tell us what is your OS, the version of Pango and Cairo you're using (if you know them), and with which output formats (PDF or PNG) you get this problem? I'd also like to test the font you're using if it's possible.

> This is with 49 (I had to revert as 50 was causing errors).

Is this error reported or fixed in current master branch? I would love to see you use version 51 when it's out :smile:.

**Comment by jtauber** [comment]
I'm traveling at the moment so can't check version numbers on my desktop machine but next week will be happy to provide all the details plus trying to replicate on the smallest file possible and share that.

**Comment by jtauber** [comment]
And yes, the error I saw with 50 was a known issue reported here and the fix suggested was to revert to 49 which is what I did.

**Comment by liZe** [comment]
@jtauber Ping? :smile:

**Comment by liZe** [comment]
Feel free to reopen if you can reproduce the error.
